/*
 * App URI: app/exam/design/guide/utils/Color
 * Source Location: app/exam/design/guide/utils/Color.clx
 *
 * This file was generated by eXbuilder6 compiler, Don't edit manually.
 */
(function(){
	var app = new cpr.core.App("app/exam/design/guide/utils/Color", {
		onPrepare: function(loader){
		},
		onCreate: function(/* cpr.core.AppInstance */ app, exports){
			var linker = {};
			// Start - User Script
			/************************************************
			 * Color.js
			 * Created at 2020. 5. 11. 오후 1:25:19.
			 *
			 * @author ryu
			 ************************************************/
			 
			 /************************************************
			 * 공통 모듈 선언
			 ************************************************/
			 
			 /************************************************
			 * 전역 변수 선언
			 ************************************************/
			 
			 /************************************************
			 * 사용자 정의 함수
			 ************************************************/
			  
			  
			 /************************************************
			 * 컨트롤 이벤트
			 ************************************************/;
			// End - User Script
			
			// Header
			
			app.supportMedia("all and (min-width: 1024px)", "default");
			app.supportMedia("all and (min-width: 850px) and (max-width: 1023px)", "tablet");
			app.supportMedia("all and (max-width: 849px)", "mobile");
			
			// Configure root container
			var container = app.getContainer();
			container.style.css({
				"width" : "100%",
				"top" : "0px",
				"height" : "100%",
				"left" : "0px"
			});
			
			// Layout
			var verticalLayout_1 = new cpr.controls.layouts.VerticalLayout();
			verticalLayout_1.spacing = 20;
			verticalLayout_1.leftMargin = 20;
			verticalLayout_1.rightMargin = 20;
			verticalLayout_1.topMargin = 20;
			verticalLayout_1.bottomMargin = 20;
			container.setLayout(verticalLayout_1);
			
			// UI Configuration
			var group_1 = new cpr.controls.Container();
			// Layout
			var formLayout_1 = new cpr.controls.layouts.FormLayout();
			formLayout_1.setColumns(["1fr", "30px"]);
			formLayout_1.setColumnAutoSizing(1, true);
			formLayout_1.setRows(["1fr"]);
			group_1.setLayout(formLayout_1);
			(function(container){
				var output_1 = new cpr.controls.Output();
				output_1.value = "Color Systems";
				output_1.style.setClasses(["h3"]);
				container.addChild(output_1, {
					"colIndex": 0,
					"rowIndex": 0
				});
				var userDefinedControl_1 = new udc.template.Breadcrumb("breadcrumb1");
				userDefinedControl_1.values = "DESIGN GUIDE,UTILS,COLOR SYSTEMS";
				container.addChild(userDefinedControl_1, {
					"colIndex": 1,
					"rowIndex": 0
				});
			})(group_1);
			container.addChild(group_1, {
				"autoSize": "none",
				"width": "984px",
				"height": "26px"
			});
			
			var output_2 = new cpr.controls.Output();
			output_2.value = "Background Color";
			output_2.style.setClasses(["h6"]);
			container.addChild(output_2, {
				"autoSize": "none",
				"width": "984px",
				"height": "25px"
			});
			
			var group_2 = new cpr.controls.Container();
			group_2.style.setClasses(["card", "card-bordered"]);
			// Layout
			var verticalLayout_2 = new cpr.controls.layouts.VerticalLayout();
			verticalLayout_2.spacing = 10;
			verticalLayout_2.leftMargin = 20;
			verticalLayout_2.rightMargin = 20;
			verticalLayout_2.topMargin = 20;
			verticalLayout_2.bottomMargin = 20;
			group_2.setLayout(verticalLayout_2);
			(function(container){
				var output_3 = new cpr.controls.Output();
				output_3.value = "THEME COLOR";
				container.addChild(output_3, {
					"width": "100px",
					"height": "25px"
				});
				var group_3 = new cpr.controls.Container();
				// Layout
				var flowLayout_1 = new cpr.controls.layouts.FlowLayout();
				flowLayout_1.scrollable = false;
				flowLayout_1.horizontalSpacing = 0;
				flowLayout_1.verticalSpacing = 0;
				group_3.setLayout(flowLayout_1);
				(function(container){
					var output_4 = new cpr.controls.Output();
					output_4.value = "primary";
					output_4.style.setClasses(["text-center", "text-white", "bg-primary"]);
					container.addChild(output_4, {
						"width": "100px",
						"height": "35px"
					});
					var output_5 = new cpr.controls.Output();
					output_5.value = "secondary";
					output_5.style.setClasses(["text-center", "text-white", "bg-secondary"]);
					container.addChild(output_5, {
						"width": "100px",
						"height": "35px"
					});
					var output_6 = new cpr.controls.Output();
					output_6.value = "dark";
					output_6.style.setClasses(["text-center", "text-white", "bg-dark"]);
					container.addChild(output_6, {
						"width": "100px",
						"height": "35px"
					});
					var output_7 = new cpr.controls.Output();
					output_7.value = "gray";
					output_7.style.setClasses(["text-center", "text-white", "bg-gray"]);
					container.addChild(output_7, {
						"width": "100px",
						"height": "35px"
					});
					var output_8 = new cpr.controls.Output();
					output_8.value = "success";
					output_8.style.setClasses(["text-center", "text-white", "bg-success"]);
					container.addChild(output_8, {
						"width": "100px",
						"height": "35px"
					});
					var output_9 = new cpr.controls.Output();
					output_9.value = "danger";
					output_9.style.setClasses(["text-center", "text-white", "bg-danger"]);
					container.addChild(output_9, {
						"width": "100px",
						"height": "35px"
					});
					var output_10 = new cpr.controls.Output();
					output_10.value = "warning";
					output_10.style.setClasses(["text-center", "bg-warning"]);
					container.addChild(output_10, {
						"width": "100px",
						"height": "35px"
					});
					var output_11 = new cpr.controls.Output();
					output_11.value = "info";
					output_11.style.setClasses(["text-center", "text-white", "bg-info"]);
					container.addChild(output_11, {
						"width": "100px",
						"height": "35px"
					});
				})(group_3);
				container.addChild(group_3, {
					"width": "400px",
					"height": "35px"
				});
				var output_12 = new cpr.controls.Output();
				output_12.value = "THEME PALE COLOR";
				container.addChild(output_12, {
					"width": "100px",
					"height": "25px"
				});
				var group_4 = new cpr.controls.Container();
				// Layout
				var flowLayout_2 = new cpr.controls.layouts.FlowLayout();
				flowLayout_2.scrollable = false;
				flowLayout_2.horizontalSpacing = 0;
				flowLayout_2.verticalSpacing = 0;
				group_4.setLayout(flowLayout_2);
				(function(container){
					var output_13 = new cpr.controls.Output();
					output_13.value = "primary";
					output_13.style.setClasses(["text-center", "text-primary", "bg-primary-dim"]);
					container.addChild(output_13, {
						"width": "100px",
						"height": "35px"
					});
					var output_14 = new cpr.controls.Output();
					output_14.value = "secondary";
					output_14.style.setClasses(["text-center", "text-secondary", "bg-secondary-dim"]);
					container.addChild(output_14, {
						"width": "100px",
						"height": "35px"
					});
					var output_15 = new cpr.controls.Output();
					output_15.value = "dark";
					output_15.style.setClasses(["text-center", "text-dark", "bg-dark-dim"]);
					container.addChild(output_15, {
						"width": "100px",
						"height": "35px"
					});
					var output_16 = new cpr.controls.Output();
					output_16.value = "gray";
					output_16.style.setClasses(["text-center", "text-gray", "bg-gray-dim"]);
					container.addChild(output_16, {
						"width": "100px",
						"height": "35px"
					});
					var output_17 = new cpr.controls.Output();
					output_17.value = "success";
					output_17.style.setClasses(["text-center", "text-success", "bg-success-dim"]);
					container.addChild(output_17, {
						"width": "100px",
						"height": "35px"
					});
					var output_18 = new cpr.controls.Output();
					output_18.value = "danger";
					output_18.style.setClasses(["text-center", "text-danger", "bg-danger-dim"]);
					container.addChild(output_18, {
						"width": "100px",
						"height": "35px"
					});
					var output_19 = new cpr.controls.Output();
					output_19.value = "warning";
					output_19.style.setClasses(["text-center", "text-warning", "bg-warning-dim"]);
					container.addChild(output_19, {
						"width": "100px",
						"height": "35px"
					});
					var output_20 = new cpr.controls.Output();
					output_20.value = "info";
					output_20.style.setClasses(["text-center", "text-info", "bg-info-dim"]);
					container.addChild(output_20, {
						"width": "100px",
						"height": "35px"
					});
				})(group_4);
				container.addChild(group_4, {
					"width": "400px",
					"height": "35px"
				});
				var output_21 = new cpr.controls.Output();
				output_21.value = "THEME LIGHTEN COLOR";
				container.addChild(output_21, {
					"width": "100px",
					"height": "25px"
				});
				var group_5 = new cpr.controls.Container();
				// Layout
				var flowLayout_3 = new cpr.controls.layouts.FlowLayout();
				flowLayout_3.scrollable = false;
				flowLayout_3.horizontalSpacing = 0;
				flowLayout_3.verticalSpacing = 0;
				group_5.setLayout(flowLayout_3);
				(function(container){
					var output_22 = new cpr.controls.Output();
					output_22.value = "light";
					output_22.style.setClasses(["text-center", "bg-light"]);
					container.addChild(output_22, {
						"width": "100px",
						"height": "35px"
					});
					var output_23 = new cpr.controls.Output();
					output_23.value = "lighter";
					output_23.style.setClasses(["text-center", "bg-lighter"]);
					container.addChild(output_23, {
						"width": "100px",
						"height": "35px"
					});
					var output_24 = new cpr.controls.Output();
					output_24.value = "white";
					output_24.style.setClasses(["text-center", "border", "bg-white"]);
					container.addChild(output_24, {
						"width": "100px",
						"height": "35px"
					});
				})(group_5);
				container.addChild(group_5, {
					"width": "400px",
					"height": "35px"
				});
			})(group_2);
			container.addChild(group_2, {
				"autoSize": "height",
				"width": "400px",
				"height": "267px"
			});
			
			var group_6 = new cpr.controls.Container();
			group_6.style.setClasses(["card", "card-bordered"]);
			// Layout
			var verticalLayout_3 = new cpr.controls.layouts.VerticalLayout();
			verticalLayout_3.spacing = 10;
			verticalLayout_3.leftMargin = 20;
			verticalLayout_3.rightMargin = 20;
			verticalLayout_3.topMargin = 20;
			verticalLayout_3.bottomMargin = 20;
			group_6.setLayout(verticalLayout_3);
			(function(container){
				var output_25 = new cpr.controls.Output();
				output_25.value = "THEME COLOR";
				container.addChild(output_25, {
					"width": "100px",
					"height": "25px"
				});
				var group_7 = new cpr.controls.Container();
				// Layout
				var flowLayout_4 = new cpr.controls.layouts.FlowLayout();
				flowLayout_4.scrollable = false;
				flowLayout_4.horizontalSpacing = 0;
				flowLayout_4.verticalSpacing = 0;
				group_7.setLayout(flowLayout_4);
				(function(container){
					var output_26 = new cpr.controls.Output();
					output_26.value = "blue";
					output_26.style.setClasses(["text-center", "text-white", "bg-blue"]);
					container.addChild(output_26, {
						"width": "100px",
						"height": "35px"
					});
					var output_27 = new cpr.controls.Output();
					output_27.value = "azure";
					output_27.style.setClasses(["text-center", "text-white", "bg-azure"]);
					container.addChild(output_27, {
						"width": "100px",
						"height": "35px"
					});
					var output_28 = new cpr.controls.Output();
					output_28.value = "indigo";
					output_28.style.setClasses(["text-center", "text-white", "bg-indigo"]);
					container.addChild(output_28, {
						"width": "100px",
						"height": "35px"
					});
					var output_29 = new cpr.controls.Output();
					output_29.value = "purple";
					output_29.style.setClasses(["text-center", "text-white", "bg-purple"]);
					container.addChild(output_29, {
						"width": "100px",
						"height": "35px"
					});
					var output_30 = new cpr.controls.Output();
					output_30.value = "pink";
					output_30.style.setClasses(["text-center", "text-white", "bg-pink"]);
					container.addChild(output_30, {
						"width": "100px",
						"height": "35px"
					});
					var output_31 = new cpr.controls.Output();
					output_31.value = "orange";
					output_31.style.setClasses(["text-center", "text-white", "bg-orange"]);
					container.addChild(output_31, {
						"width": "100px",
						"height": "35px"
					});
					var output_32 = new cpr.controls.Output();
					output_32.value = "teal";
					output_32.style.setClasses(["text-center", "text-white", "bg-teal"]);
					container.addChild(output_32, {
						"width": "100px",
						"height": "35px"
					});
				})(group_7);
				container.addChild(group_7, {
					"width": "400px",
					"height": "35px"
				});
				var output_33 = new cpr.controls.Output();
				output_33.value = "THEME PALE COLOR";
				container.addChild(output_33, {
					"width": "100px",
					"height": "25px"
				});
				var group_8 = new cpr.controls.Container();
				// Layout
				var flowLayout_5 = new cpr.controls.layouts.FlowLayout();
				flowLayout_5.scrollable = false;
				flowLayout_5.horizontalSpacing = 0;
				flowLayout_5.verticalSpacing = 0;
				group_8.setLayout(flowLayout_5);
				(function(container){
					var output_34 = new cpr.controls.Output();
					output_34.value = "blue";
					output_34.style.setClasses(["text-center", "text-blue", "bg-blue-dim"]);
					container.addChild(output_34, {
						"width": "100px",
						"height": "35px"
					});
					var output_35 = new cpr.controls.Output();
					output_35.value = "azure";
					output_35.style.setClasses(["text-center", "text-azure", "bg-azure-dim"]);
					container.addChild(output_35, {
						"width": "100px",
						"height": "35px"
					});
					var output_36 = new cpr.controls.Output();
					output_36.value = "indigo";
					output_36.style.setClasses(["text-center", "text-indigo", "bg-indigo-dim"]);
					container.addChild(output_36, {
						"width": "100px",
						"height": "35px"
					});
					var output_37 = new cpr.controls.Output();
					output_37.value = "purple";
					output_37.style.setClasses(["text-center", "text-purple", "bg-purple-dim"]);
					container.addChild(output_37, {
						"width": "100px",
						"height": "35px"
					});
					var output_38 = new cpr.controls.Output();
					output_38.value = "pink";
					output_38.style.setClasses(["text-center", "text-pink", "bg-pink-dim"]);
					container.addChild(output_38, {
						"width": "100px",
						"height": "35px"
					});
					var output_39 = new cpr.controls.Output();
					output_39.value = "orange";
					output_39.style.setClasses(["text-center", "text-orange", "bg-orange-dim"]);
					container.addChild(output_39, {
						"width": "100px",
						"height": "35px"
					});
					var output_40 = new cpr.controls.Output();
					output_40.value = "teal";
					output_40.style.setClasses(["text-center", "text-teal", "bg-teal-dim"]);
					container.addChild(output_40, {
						"width": "100px",
						"height": "35px"
					});
				})(group_8);
				container.addChild(group_8, {
					"width": "400px",
					"height": "35px"
				});
			})(group_6);
			container.addChild(group_6, {
				"autoSize": "height",
				"width": "400px",
				"height": "193px"
			});
			
			var group_9 = new cpr.controls.Container();
			group_9.style.setClasses(["card", "card-bordered"]);
			// Layout
			var formLayout_2 = new cpr.controls.layouts.FormLayout();
			formLayout_2.topMargin = "5px";
			formLayout_2.rightMargin = "20px";
			formLayout_2.bottomMargin = "5px";
			formLayout_2.leftMargin = "20px";
			formLayout_2.horizontalSpacing = "10px";
			formLayout_2.verticalSpacing = "10px";
			formLayout_2.horizontalSeparatorWidth = 1;
			formLayout_2.setColumns(["150px", "1fr"]);
			formLayout_2.setRows(["25px", "30px", "30px", "30px", "30px", "30px", "30px", "30px", "30px"]);
			formLayout_2.setUseRowShade(0, true);
			group_9.setLayout(formLayout_2);
			(function(container){
				var output_41 = new cpr.controls.Output();
				output_41.value = "CLASS REFERENCE";
				output_41.style.setClasses(["overline-title"]);
				container.addChild(output_41, {
					"colIndex": 0,
					"rowIndex": 0
				});
				var output_42 = new cpr.controls.Output();
				output_42.value = "DETAILS";
				output_42.style.setClasses(["overline-title"]);
				container.addChild(output_42, {
					"colIndex": 1,
					"rowIndex": 0
				});
				var output_43 = new cpr.controls.Output();
				output_43.value = ".bg-{theme}";
				output_43.style.setClasses(["code"]);
				container.addChild(output_43, {
					"colIndex": 0,
					"rowIndex": 1
				});
				var output_44 = new cpr.controls.Output();
				output_44.value = "primary | secondary | success | info | warning | danger | dark | gray";
				container.addChild(output_44, {
					"colIndex": 1,
					"rowIndex": 1
				});
				var output_45 = new cpr.controls.Output();
				output_45.value = ".bg-{theme}-dim";
				output_45.style.setClasses(["code"]);
				container.addChild(output_45, {
					"colIndex": 0,
					"rowIndex": 2
				});
				var output_46 = new cpr.controls.Output();
				output_46.value = "Use for pale/dim color and {theme} same as above";
				container.addChild(output_46, {
					"colIndex": 1,
					"rowIndex": 2
				});
				var output_47 = new cpr.controls.Output();
				output_47.value = ".bg-{color}";
				output_47.style.setClasses(["code"]);
				container.addChild(output_47, {
					"colIndex": 0,
					"rowIndex": 3
				});
				var output_48 = new cpr.controls.Output();
				output_48.value = "blue | azure | indigo | purple | pink | orange | teal";
				container.addChild(output_48, {
					"colIndex": 1,
					"rowIndex": 3
				});
				var output_49 = new cpr.controls.Output();
				output_49.value = ".bg-{color}-dim";
				output_49.style.setClasses(["code"]);
				container.addChild(output_49, {
					"colIndex": 0,
					"rowIndex": 4
				});
				var output_50 = new cpr.controls.Output();
				output_50.value = "Use for pale/dim color and {color} same as above";
				container.addChild(output_50, {
					"colIndex": 1,
					"rowIndex": 4
				});
				var output_51 = new cpr.controls.Output();
				output_51.value = ".bg-light";
				output_51.style.setClasses(["code"]);
				container.addChild(output_51, {
					"colIndex": 0,
					"rowIndex": 5
				});
				var output_52 = new cpr.controls.Output();
				output_52.value = "Use for light background";
				container.addChild(output_52, {
					"colIndex": 1,
					"rowIndex": 5
				});
				var output_53 = new cpr.controls.Output();
				output_53.value = ".bg-lighter";
				output_53.style.setClasses(["code"]);
				container.addChild(output_53, {
					"colIndex": 0,
					"rowIndex": 6
				});
				var output_54 = new cpr.controls.Output();
				output_54.value = "Use for extra light background";
				container.addChild(output_54, {
					"colIndex": 1,
					"rowIndex": 6
				});
				var output_55 = new cpr.controls.Output();
				output_55.value = ".bg-white";
				output_55.style.setClasses(["code"]);
				container.addChild(output_55, {
					"colIndex": 0,
					"rowIndex": 7
				});
				var output_56 = new cpr.controls.Output();
				output_56.value = "Use for white background";
				container.addChild(output_56, {
					"colIndex": 1,
					"rowIndex": 7
				});
				var output_57 = new cpr.controls.Output();
				output_57.value = ".bg-transparent";
				output_57.style.setClasses(["code"]);
				container.addChild(output_57, {
					"colIndex": 0,
					"rowIndex": 8
				});
				var output_58 = new cpr.controls.Output();
				output_58.value = "Use for transparent background";
				container.addChild(output_58, {
					"colIndex": 1,
					"rowIndex": 8
				});
			})(group_9);
			container.addChild(group_9, {
				"autoSize": "none",
				"width": "984px",
				"height": "357px"
			});
			
			var output_59 = new cpr.controls.Output();
			output_59.value = "Gray & Dark Color";
			output_59.style.setClasses(["h6"]);
			container.addChild(output_59, {
				"autoSize": "none",
				"width": "984px",
				"height": "25px"
			});
			
			var group_10 = new cpr.controls.Container();
			group_10.style.setClasses(["card", "card-bordered"]);
			// Layout
			var verticalLayout_4 = new cpr.controls.layouts.VerticalLayout();
			verticalLayout_4.spacing = 10;
			verticalLayout_4.leftMargin = 20;
			verticalLayout_4.rightMargin = 20;
			verticalLayout_4.topMargin = 20;
			verticalLayout_4.bottomMargin = 20;
			group_10.setLayout(verticalLayout_4);
			(function(container){
				var group_11 = new cpr.controls.Container();
				// Layout
				var flowLayout_6 = new cpr.controls.layouts.FlowLayout();
				flowLayout_6.scrollable = false;
				flowLayout_6.horizontalSpacing = 0;
				flowLayout_6.verticalSpacing = 0;
				group_11.setLayout(flowLayout_6);
				(function(container){
					var output_60 = new cpr.controls.Output();
					output_60.value = "100";
					output_60.style.setClasses(["text-center", "bg-gray-100"]);
					container.addChild(output_60, {
						"width": "100px",
						"height": "35px"
					});
					var output_61 = new cpr.controls.Output();
					output_61.value = "200";
					output_61.style.setClasses(["text-center", "bg-gray-200"]);
					container.addChild(output_61, {
						"width": "100px",
						"height": "35px"
					});
					var output_62 = new cpr.controls.Output();
					output_62.value = "300";
					output_62.style.setClasses(["text-center", "bg-gray-300"]);
					container.addChild(output_62, {
						"width": "100px",
						"height": "35px"
					});
					var output_63 = new cpr.controls.Output();
					output_63.value = "400";
					output_63.style.setClasses(["text-center", "bg-gray-400"]);
					container.addChild(output_63, {
						"width": "100px",
						"height": "35px"
					});
					var output_64 = new cpr.controls.Output();
					output_64.value = "500";
					output_64.style.setClasses(["text-center", "text-white", "bg-gray-500"]);
					container.addChild(output_64, {
						"width": "100px",
						"height": "35px"
					});
					var output_65 = new cpr.controls.Output();
					output_65.value = "600";
					output_65.style.setClasses(["text-center", "text-white", "bg-gray-600"]);
					container.addChild(output_65, {
						"width": "100px",
						"height": "35px"
					});
					var output_66 = new cpr.controls.Output();
					output_66.value = "700";
					output_66.style.setClasses(["text-center", "text-white", "bg-gray-700"]);
					container.addChild(output_66, {
						"width": "100px",
						"height": "35px"
					});
					var output_67 = new cpr.controls.Output();
					output_67.value = "800";
					output_67.style.setClasses(["text-center", "text-white", "bg-gray-800"]);
					container.addChild(output_67, {
						"width": "100px",
						"height": "35px"
					});
					var output_68 = new cpr.controls.Output();
					output_68.value = "900";
					output_68.style.setClasses(["text-center", "text-white", "bg-gray-900"]);
					container.addChild(output_68, {
						"width": "100px",
						"height": "35px"
					});
				})(group_11);
				container.addChild(group_11, {
					"width": "400px",
					"height": "35px"
				});
			})(group_10);
			container.addChild(group_10, {
				"autoSize": "height",
				"width": "984px",
				"height": "76px"
			});
			
			var group_12 = new cpr.controls.Container();
			group_12.style.setClasses(["card", "card-bordered"]);
			// Layout
			var formLayout_3 = new cpr.controls.layouts.FormLayout();
			formLayout_3.topMargin = "5px";
			formLayout_3.rightMargin = "20px";
			formLayout_3.bottomMargin = "5px";
			formLayout_3.leftMargin = "20px";
			formLayout_3.horizontalSpacing = "10px";
			formLayout_3.verticalSpacing = "10px";
			formLayout_3.horizontalSeparatorWidth = 1;
			formLayout_3.setColumns(["150px", "1fr"]);
			formLayout_3.setRows(["25px", "30px"]);
			formLayout_3.setUseRowShade(0, true);
			group_12.setLayout(formLayout_3);
			(function(container){
				var output_69 = new cpr.controls.Output();
				output_69.value = "CLASS REFERENCE";
				output_69.style.setClasses(["overline-title"]);
				container.addChild(output_69, {
					"colIndex": 0,
					"rowIndex": 0
				});
				var output_70 = new cpr.controls.Output();
				output_70.value = "DETAILS";
				output_70.style.setClasses(["overline-title"]);
				container.addChild(output_70, {
					"colIndex": 1,
					"rowIndex": 0
				});
				var output_71 = new cpr.controls.Output();
				output_71.value = ".bg-gray-{value}";
				output_71.style.setClasses(["code"]);
				container.addChild(output_71, {
					"colIndex": 0,
					"rowIndex": 1
				});
				var output_72 = new cpr.controls.Output();
				output_72.value = "100 | 200 | 300 | 400 | 500 | 600 | 700 | 800 | 900";
				container.addChild(output_72, {
					"colIndex": 1,
					"rowIndex": 1
				});
			})(group_12);
			container.addChild(group_12, {
				"autoSize": "none",
				"width": "984px",
				"height": "77px"
			});
			
			var output_73 = new cpr.controls.Output();
			output_73.value = "Text Color";
			output_73.style.setClasses(["h6"]);
			container.addChild(output_73, {
				"autoSize": "none",
				"width": "984px",
				"height": "25px"
			});
			
			var group_13 = new cpr.controls.Container();
			group_13.style.setClasses(["card", "card-bordered"]);
			// Layout
			var formLayout_4 = new cpr.controls.layouts.FormLayout();
			formLayout_4.topMargin = "5px";
			formLayout_4.rightMargin = "20px";
			formLayout_4.bottomMargin = "5px";
			formLayout_4.leftMargin = "20px";
			formLayout_4.horizontalSpacing = "10px";
			formLayout_4.verticalSpacing = "10px";
			formLayout_4.horizontalSeparatorWidth = 1;
			formLayout_4.setColumns(["150px", "1fr"]);
			formLayout_4.setRows(["25px", "30px", "30px", "30px", "30px", "30px", "30px", "30px", "30px", "30px", "30px", "40px", "40px"]);
			formLayout_4.setUseRowShade(0, true);
			group_13.setLayout(formLayout_4);
			(function(container){
				var output_74 = new cpr.controls.Output();
				output_74.value = "CLASS REFERENCE";
				output_74.style.setClasses(["overline-title"]);
				container.addChild(output_74, {
					"colIndex": 0,
					"rowIndex": 0
				});
				var output_75 = new cpr.controls.Output();
				output_75.value = "PREVIEW";
				output_75.style.setClasses(["overline-title"]);
				container.addChild(output_75, {
					"colIndex": 1,
					"rowIndex": 0
				});
				var output_76 = new cpr.controls.Output();
				output_76.value = ".text-primary";
				output_76.style.setClasses(["code"]);
				container.addChild(output_76, {
					"colIndex": 0,
					"rowIndex": 1
				});
				var output_77 = new cpr.controls.Output();
				output_77.value = "Text in primary color";
				output_77.style.setClasses(["text-primary"]);
				container.addChild(output_77, {
					"colIndex": 1,
					"rowIndex": 1
				});
				var output_78 = new cpr.controls.Output();
				output_78.value = ".text-secondary";
				output_78.style.setClasses(["code"]);
				container.addChild(output_78, {
					"colIndex": 0,
					"rowIndex": 2
				});
				var output_79 = new cpr.controls.Output();
				output_79.value = ".text-success";
				output_79.style.setClasses(["code"]);
				container.addChild(output_79, {
					"colIndex": 0,
					"rowIndex": 3
				});
				var output_80 = new cpr.controls.Output();
				output_80.value = ".text-danger";
				output_80.style.setClasses(["code"]);
				container.addChild(output_80, {
					"colIndex": 0,
					"rowIndex": 4
				});
				var output_81 = new cpr.controls.Output();
				output_81.value = ".text-warning";
				output_81.style.setClasses(["code"]);
				container.addChild(output_81, {
					"colIndex": 0,
					"rowIndex": 5
				});
				var output_82 = new cpr.controls.Output();
				output_82.value = ".text-info";
				output_82.style.setClasses(["code"]);
				container.addChild(output_82, {
					"colIndex": 0,
					"rowIndex": 6
				});
				var output_83 = new cpr.controls.Output();
				output_83.value = ".text-dark";
				output_83.style.setClasses(["code"]);
				container.addChild(output_83, {
					"colIndex": 0,
					"rowIndex": 7
				});
				var output_84 = new cpr.controls.Output();
				output_84.value = ".text-light";
				output_84.style.setClasses(["code"]);
				container.addChild(output_84, {
					"colIndex": 0,
					"rowIndex": 8
				});
				var output_85 = new cpr.controls.Output();
				output_85.value = ".text-lighter";
				output_85.style.setClasses(["code"]);
				container.addChild(output_85, {
					"colIndex": 0,
					"rowIndex": 9
				});
				var output_86 = new cpr.controls.Output();
				output_86.value = ".text-white";
				output_86.style.setClasses(["code"]);
				container.addChild(output_86, {
					"colIndex": 0,
					"rowIndex": 10
				});
				var output_87 = new cpr.controls.Output();
				output_87.value = ".text-{theme}\r\n.text-{theme}-dim";
				output_87.style.setClasses(["code"]);
				container.addChild(output_87, {
					"colIndex": 0,
					"rowIndex": 11
				});
				var output_88 = new cpr.controls.Output();
				output_88.value = ".text-{color}\r\n.text-{color}-dim";
				output_88.style.setClasses(["code"]);
				container.addChild(output_88, {
					"colIndex": 0,
					"rowIndex": 12
				});
				var output_89 = new cpr.controls.Output();
				output_89.value = "Text in secondary color";
				output_89.style.setClasses(["text-secondary"]);
				container.addChild(output_89, {
					"colIndex": 1,
					"rowIndex": 2
				});
				var output_90 = new cpr.controls.Output();
				output_90.value = "Text in success color";
				output_90.style.setClasses(["text-success"]);
				container.addChild(output_90, {
					"colIndex": 1,
					"rowIndex": 3
				});
				var output_91 = new cpr.controls.Output();
				output_91.value = "Text in danger color";
				output_91.style.setClasses(["text-danger"]);
				container.addChild(output_91, {
					"colIndex": 1,
					"rowIndex": 4
				});
				var output_92 = new cpr.controls.Output();
				output_92.value = "Text in warning color";
				output_92.style.setClasses(["text-warning"]);
				container.addChild(output_92, {
					"colIndex": 1,
					"rowIndex": 5
				});
				var output_93 = new cpr.controls.Output();
				output_93.value = "Text in info color";
				output_93.style.setClasses(["text-info"]);
				container.addChild(output_93, {
					"colIndex": 1,
					"rowIndex": 6
				});
				var output_94 = new cpr.controls.Output();
				output_94.value = "Text in dark color";
				output_94.style.setClasses(["text-dark"]);
				container.addChild(output_94, {
					"colIndex": 1,
					"rowIndex": 7
				});
				var output_95 = new cpr.controls.Output();
				output_95.value = "Text in light color";
				output_95.style.setClasses(["bg-dark", "text-light"]);
				container.addChild(output_95, {
					"colIndex": 1,
					"rowIndex": 8
				});
				var output_96 = new cpr.controls.Output();
				output_96.value = "Text in lighter color";
				output_96.style.setClasses(["bg-dark", "text-lighter"]);
				container.addChild(output_96, {
					"colIndex": 1,
					"rowIndex": 9
				});
				var output_97 = new cpr.controls.Output();
				output_97.value = "Text in white color";
				output_97.style.setClasses(["bg-dark", "text-white"]);
				container.addChild(output_97, {
					"colIndex": 1,
					"rowIndex": 10
				});
				var output_98 = new cpr.controls.Output();
				output_98.value = "Use for text color & -dim user for pale color.\r\n{theme} use as primary, secondary, success, info, warning, danger, dark, gray";
				container.addChild(output_98, {
					"colIndex": 1,
					"rowIndex": 11
				});
				var output_99 = new cpr.controls.Output();
				output_99.value = "Use for text color & -dim user for pale color.\r\n{color} use as blue, azure, indigo, purple, pink, orange, teal";
				container.addChild(output_99, {
					"colIndex": 1,
					"rowIndex": 12
				});
			})(group_13);
			container.addChild(group_13, {
				"autoSize": "none",
				"width": "984px",
				"height": "537px"
			});
		}
	});
	app.title = "Color";
	cpr.core.Platform.INSTANCE.register(app);
})();
