/*
 * App URI: app/exam/controls/Slider
 * Source Location: app/exam/controls/Slider.clx
 *
 * This file was generated by eXbuilder6 compiler, Don't edit manually.
 */
(function(){
	var app = new cpr.core.App("app/exam/controls/Slider", {
		onPrepare: function(loader){
		},
		onCreate: function(/* cpr.core.AppInstance */ app, exports){
			var linker = {};
			// Start - User Script
			/************************************************
			 * Slider.js
			 * Created at 2022. 3. 11. 오전 9:15:09.
			 *
			 * @author 1amthomas
			 ************************************************/
			
			/*
			 * "실행" 버튼(btnInit)에서 click 이벤트 발생 시 호출.
			 * 사용자가 컨트롤을 클릭할 때 발생하는 이벤트.
			 */
			function onBtnInitClick(e){
				var select = app.lookup("sampleCmb1").value;
				if(select == null){
					alert("입력값을 먼저 선택하세요");
					return false;
				}
				if(select == "50"){
					app.lookup("sampleSld1").value = "50";
				}else{
					app.lookup("sampleSld1").range = true;
					app.lookup("sampleSld1").value = "50,70";
				}
				app.lookup("sampleSld1").redraw();	
			}
			
			/*
			 * "실행" 버튼(btnInit2)에서 click 이벤트 발생 시 호출.
			 * 사용자가 컨트롤을 클릭할 때 발생하는 이벤트.
			 */
			function onBtnInit2Click(e){
				var select = app.lookup("sampleCmb2").value;
				if(select == null){
					alert("입력값을 먼저 선택하세요");
					return false;
				}
				app.lookup("sampleSld2").direction = select;
			}
			
			/*
			 * "실행" 버튼(btnInit3)에서 click 이벤트 발생 시 호출.
			 * 사용자가 컨트롤을 클릭할 때 발생하는 이벤트.
			 */
			function onBtnInit3Click(e){
				var select = app.lookup("sampleCmb3").value;
				if(select == null){
					alert("입력값을 먼저 선택하세요");
					return false;
				}
				if(select == "true"){
					app.lookup("sampleSld3").range = true;		
				}else{
					app.lookup("sampleSld3").range = false;
				}
				app.lookup("sampleSld3").redraw();	
				
			}
			
			/*
			 * "실행" 버튼(btnInit4)에서 click 이벤트 발생 시 호출.
			 * 사용자가 컨트롤을 클릭할 때 발생하는 이벤트.
			 */
			function onBtnInit4Click(e){
				var select = app.lookup("sampleCmb4").value;
				if(select == null){
					alert("입력값을 먼저 선택하세요");
					return false;
				}
				app.lookup("sampleSld4").orientation = select;
				app.lookup("sampleSld4").redraw();
			}
			
			/*
			 * "실행" 버튼(btnInit5)에서 click 이벤트 발생 시 호출.
			 * 사용자가 컨트롤을 클릭할 때 발생하는 이벤트.
			 */
			function onBtnInit5Click(e){
				var select = app.lookup("sampleCmb5").value;
				if(select == null){
					alert("입력값을 먼저 선택하세요");
					return false;
				}
				app.lookup("sampleSld5").step = Number(select);
				app.lookup("sampleSld5").redraw();
			}
			
			/*
			 * 슬라이더에서 value-change 이벤트 발생 시 호출.
			 * 값이 변경된 후 발생하는 이벤트
			 */
			function onSampleSld5ValueChange(e){
				var sampleSld5 = e.control;
				var vsStep = sampleSld5.step;
				console.log(vsStep);
				app.lookup("optRslt").value = "step 이동값 : "+vsStep;
			};
			// End - User Script
			
			// Header
			
			app.supportMedia("all and (min-width: 1320px)", "eXFrame");
			app.supportMedia("all and (min-width: 1020px) and (max-width: 1319px)", "default");
			app.supportMedia("all and (min-width: 760px) and (max-width: 1019px)", "tablet");
			app.supportMedia("all and (max-width: 759px)", "mobile");
			
			// Configure root container
			var container = app.getContainer();
			container.style.css({
				"width" : "100%",
				"height" : "100%"
			});
			
			// Layout
			var verticalLayout_1 = new cpr.controls.layouts.VerticalLayout();
			container.setLayout(verticalLayout_1);
			
			// UI Configuration
			var group_1 = new cpr.controls.Container("grpHeader");
			// Layout
			var verticalLayout_2 = new cpr.controls.layouts.VerticalLayout();
			verticalLayout_2.spacing = 0;
			group_1.setLayout(verticalLayout_2);
			(function(container){
				var userDefinedControl_1 = new udc.com.appHeader("appheader1");
				userDefinedControl_1.initializeYn = "N";
				userDefinedControl_1.searchBoxId = "grpHeader";
				container.addChild(userDefinedControl_1, {
					"width": "500px",
					"height": "30px"
				});
			})(group_1);
			container.addChild(group_1, {
				"autoSize": "height",
				"width": "400px",
				"height": "30px"
			});
			
			var group_2 = new cpr.controls.Container("grpData");
			// Layout
			var verticalLayout_3 = new cpr.controls.layouts.VerticalLayout();
			verticalLayout_3.spacing = 20;
			verticalLayout_3.leftMargin = 50;
			verticalLayout_3.rightMargin = 50;
			verticalLayout_3.topMargin = 20;
			verticalLayout_3.bottomMargin = 60;
			group_2.setLayout(verticalLayout_3);
			(function(container){
				var group_3 = new cpr.controls.Container();
				// Layout
				var verticalLayout_4 = new cpr.controls.layouts.VerticalLayout();
				verticalLayout_4.spacing = 30;
				verticalLayout_4.leftMargin = 0;
				verticalLayout_4.rightMargin = 0;
				verticalLayout_4.topMargin = 20;
				verticalLayout_4.bottomMargin = 40;
				group_3.setLayout(verticalLayout_4);
				(function(container){
					var output_1 = new cpr.controls.Output();
					output_1.value = "슬라이더";
					output_1.style.css({
						"font-weight" : "700",
						"font-size" : "2.5rem",
						"font-family" : "sans-serif , 'Malgun Gothic' , 'Noto Sans KR'"
					});
					container.addChild(output_1, {
						"autoSize": "height",
						"width": "100px",
						"height": "45px"
					});
					var output_2 = new cpr.controls.Output();
					output_2.value = "범위 조절이 가능한 슬라이더 컨트롤입니다.\r\n\r\n진행 상태를 시각적으로 표현할 수 있습니다.\r\n슬라이더 range 속성이 true가 되었을 때 handle로 범위를 지정할 수 있습니다.";
					output_2.style.setClasses(["opt-tmpl"]);
					output_2.style.css({
						"font-family" : "sans-serif , 'Malgun Gothic' , 'Noto Sans KR'"
					});
					container.addChild(output_2, {
						"autoSize": "height",
						"width": "100px",
						"height": "150px"
					});
					var group_4 = new cpr.controls.Container();
					group_4.style.setClasses(["attach-box"]);
					group_4.style.css({
						"border-right-style" : "solid",
						"border-top-width" : "1px",
						"border-bottom-color" : "#babfc7",
						"border-right-width" : "1px",
						"border-left-color" : "#babfc7",
						"border-right-color" : "#babfc7",
						"border-left-width" : "1px",
						"border-top-style" : "solid",
						"background-color" : "#e9e9e9",
						"border-left-style" : "solid",
						"border-bottom-width" : "1px",
						"border-top-color" : "#babfc7",
						"border-bottom-style" : "solid"
					});
					// Layout
					var flowLayout_1 = new cpr.controls.layouts.FlowLayout();
					flowLayout_1.scrollable = false;
					flowLayout_1.horizontalSpacing = 40;
					flowLayout_1.verticalSpacing = 20;
					flowLayout_1.horizontalAlign = "center";
					flowLayout_1.verticalAlign = "middle";
					flowLayout_1.leftMargin = 20;
					flowLayout_1.rightMargin = 20;
					flowLayout_1.topMargin = 20;
					flowLayout_1.bottomMargin = 20;
					group_4.setLayout(flowLayout_1);
					(function(container){
						var group_5 = new cpr.controls.Container();
						// Layout
						var formLayout_1 = new cpr.controls.layouts.FormLayout();
						formLayout_1.topMargin = "0px";
						formLayout_1.rightMargin = "0px";
						formLayout_1.bottomMargin = "0px";
						formLayout_1.leftMargin = "0px";
						formLayout_1.horizontalSpacing = "5px";
						formLayout_1.verticalSpacing = "5px";
						formLayout_1.setColumns(["1fr"]);
						formLayout_1.setRows(["1fr", "20px"]);
						group_5.setLayout(formLayout_1);
						(function(container){
							var output_3 = new cpr.controls.Output();
							output_3.value = "<기본 슬라이더 컨트롤>";
							output_3.style.setClasses(["text-center"]);
							container.addChild(output_3, {
								"colIndex": 0,
								"rowIndex": 1
							});
							var slider_1 = new cpr.controls.Slider("defaultSld");
							slider_1.max = 50.0;
							slider_1.step = 10.0;
							container.addChild(slider_1, {
								"colIndex": 0,
								"rowIndex": 0
							});
						})(group_5);
						container.addChild(group_5, {
							"autoSize": "none",
							"width": "200px",
							"height": "50px"
						});
						var group_6 = new cpr.controls.Container();
						// Layout
						var formLayout_2 = new cpr.controls.layouts.FormLayout();
						formLayout_2.scrollable = true;
						formLayout_2.topMargin = "0px";
						formLayout_2.rightMargin = "0px";
						formLayout_2.bottomMargin = "0px";
						formLayout_2.leftMargin = "0px";
						formLayout_2.horizontalSpacing = "5px";
						formLayout_2.verticalSpacing = "5px";
						formLayout_2.setColumns(["1fr"]);
						formLayout_2.setRows(["1fr", "20px"]);
						group_6.setLayout(formLayout_2);
						(function(container){
							var output_4 = new cpr.controls.Output();
							output_4.value = "<컨트롤 동적 생성 코드>";
							output_4.style.setClasses(["text-center"]);
							container.addChild(output_4, {
								"colIndex": 0,
								"rowIndex": 1
							});
							var userDefinedControl_2 = new udc.tmp.Ace("ace1");
							userDefinedControl_2.value = "var Slider_1 = new cpr.controls.Slider(\"sld1\");\r\n\r\n/* 슬라이더 최댓값 설정 */\r\nSlider_1.max = 50;\r\n\r\n/* 슬라이더 증가 값 설정 */\r\nSlider_1.step = 10;";
							container.addChild(userDefinedControl_2, {
								"colIndex": 0,
								"rowIndex": 0
							});
						})(group_6);
						container.addChild(group_6, {
							"autoSize": "both",
							"width": "450px",
							"height": "300px"
						});
					})(group_4);
					container.addChild(group_4, {
						"autoSize": "height",
						"width": "1220px",
						"height": "381px"
					});
				})(group_3);
				container.addChild(group_3, {
					"autoSize": "height",
					"width": "400px",
					"height": "700px"
				});
				var group_7 = new cpr.controls.Container();
				group_7.style.setClasses(["card-inner"]);
				// Layout
				var verticalLayout_5 = new cpr.controls.layouts.VerticalLayout();
				verticalLayout_5.spacing = 30;
				verticalLayout_5.leftMargin = 0;
				verticalLayout_5.rightMargin = 0;
				verticalLayout_5.topMargin = 20;
				verticalLayout_5.bottomMargin = 40;
				group_7.setLayout(verticalLayout_5);
				(function(container){
					var output_5 = new cpr.controls.Output();
					output_5.value = "자주 사용되는 속성";
					output_5.style.setClasses(["h1", "pl-3", "bg-primary", "text-white"]);
					output_5.style.css({
						"font-weight" : "700",
						"font-size" : "26px",
						"font-family" : "sans-serif , 'Malgun Gothic' , 'Noto Sans KR'"
					});
					container.addChild(output_5, {
						"autoSize": "none",
						"width": "1220px",
						"height": "38px"
					});
					var output_6 = new cpr.controls.Output();
					output_6.value = "자주 사용되는 속성과 시나리오를 통한 예제를 확인할 수 있습니다. 자세한 사항은 Help Contents를 참조하시기 바랍니다.";
					container.addChild(output_6, {
						"autoSize": "height",
						"width": "100px",
						"height": "141px"
					});
					var group_8 = new cpr.controls.Container();
					group_8.style.setClasses(["card-inner"]);
					// Layout
					var verticalLayout_6 = new cpr.controls.layouts.VerticalLayout();
					verticalLayout_6.spacing = 15;
					verticalLayout_6.leftMargin = 40;
					verticalLayout_6.rightMargin = 40;
					verticalLayout_6.topMargin = 20;
					verticalLayout_6.bottomMargin = 40;
					group_8.setLayout(verticalLayout_6);
					(function(container){
						var output_7 = new cpr.controls.Output();
						output_7.value = "value";
						output_7.style.css({
							"color" : "#2263b3",
							"font-weight" : "700",
							"font-size" : "20px",
							"font-family" : "sans-serif , 'Malgun Gothic' , 'Noto Sans KR'"
						});
						container.addChild(output_7, {
							"autoSize": "none",
							"width": "1220px",
							"height": "38px"
						});
						var group_9 = new cpr.controls.Container();
						group_9.style.css({
							"background-color" : "#e9eff7",
							"background-image" : "none"
						});
						// Layout
						var verticalLayout_7 = new cpr.controls.layouts.VerticalLayout();
						verticalLayout_7.leftMargin = 30;
						verticalLayout_7.rightMargin = 30;
						verticalLayout_7.topMargin = 20;
						verticalLayout_7.bottomMargin = 20;
						group_9.setLayout(verticalLayout_7);
						(function(container){
							var output_8 = new cpr.controls.Output();
							output_8.value = "슬라이더의 값을 설정할 수 있는 속성입니다. 슬라이더는 1개 이상의 value값을 설정할 수 있습니다.";
							output_8.style.setClasses(["opt-tmpl"]);
							output_8.style.css({
								"font-weight" : "700"
							});
							container.addChild(output_8, {
								"autoSize": "height",
								"width": "100px",
								"height": "40px"
							});
						})(group_9);
						container.addChild(group_9, {
							"autoSize": "height",
							"width": "1140px",
							"height": "80px"
						});
						var group_10 = new cpr.controls.Container();
						group_10.style.setClasses(["form-box", "vertical"]);
						// Layout
						var formLayout_3 = new cpr.controls.layouts.FormLayout();
						formLayout_3.topMargin = "5px";
						formLayout_3.rightMargin = "5px";
						formLayout_3.bottomMargin = "5px";
						formLayout_3.leftMargin = "5px";
						formLayout_3.horizontalSpacing = "10px";
						formLayout_3.verticalSpacing = "10px";
						formLayout_3.horizontalSeparatorWidth = 1;
						formLayout_3.verticalSeparatorWidth = 1;
						formLayout_3.setColumns(["1fr", "2fr"]);
						formLayout_3.setCustomColumnShade(0, "#edeff6");
						formLayout_3.setRows(["30px", "30px", "30px"]);
						formLayout_3.setRowAutoSizing(1, true);
						formLayout_3.setRowAutoSizing(2, true);
						group_10.setLayout(formLayout_3);
						(function(container){
							var output_9 = new cpr.controls.Output();
							output_9.value = "type";
							output_9.style.setClasses(["label"]);
							output_9.style.css({
								"border-right-style" : "none",
								"background-color" : "transparent",
								"border-left-style" : "none",
								"border-bottom-style" : "none",
								"border-top-style" : "none",
								"text-align" : "center"
							});
							container.addChild(output_9, {
								"colIndex": 0,
								"rowIndex": 0
							});
							var output_10 = new cpr.controls.Output();
							output_10.value = "String";
							output_10.style.css({
								"background-color" : "transparent",
								"border-right-style" : "none",
								"border-left-style" : "none",
								"border-bottom-style" : "none",
								"border-top-style" : "none",
								"text-align" : "center"
							});
							container.addChild(output_10, {
								"colIndex": 1,
								"rowIndex": 0
							});
							var output_11 = new cpr.controls.Output();
							output_11.value = "get";
							output_11.style.setClasses(["label"]);
							output_11.style.css({
								"border-right-style" : "none",
								"background-color" : "transparent",
								"border-left-style" : "none",
								"border-bottom-style" : "none",
								"border-top-style" : "none",
								"text-align" : "center"
							});
							container.addChild(output_11, {
								"colIndex": 0,
								"rowIndex": 1
							});
							var output_12 = new cpr.controls.Output();
							output_12.value = "set";
							output_12.style.setClasses(["label"]);
							output_12.style.css({
								"border-right-style" : "none",
								"background-color" : "transparent",
								"border-left-style" : "none",
								"border-bottom-style" : "none",
								"border-top-style" : "none",
								"text-align" : "center"
							});
							container.addChild(output_12, {
								"colIndex": 0,
								"rowIndex": 2
							});
							var output_13 = new cpr.controls.Output();
							output_13.value = "컨트롤의 값을 반환합니다.";
							output_13.style.css({
								"background-color" : "transparent",
								"border-right-style" : "none",
								"border-left-style" : "none",
								"border-bottom-style" : "none",
								"border-top-style" : "none",
								"text-align" : "center"
							});
							container.addChild(output_13, {
								"colIndex": 1,
								"rowIndex": 1
							});
							var output_14 = new cpr.controls.Output();
							output_14.value = "컨트롤의 값을 설정하고, value-change이벤트가 발생됩니다. ";
							output_14.style.css({
								"background-color" : "transparent",
								"border-right-style" : "none",
								"border-left-style" : "none",
								"border-bottom-style" : "none",
								"border-top-style" : "none",
								"text-align" : "center"
							});
							container.addChild(output_14, {
								"colIndex": 1,
								"rowIndex": 2
							});
						})(group_10);
						container.addChild(group_10, {
							"autoSize": "height",
							"width": "1220px",
							"height": "125px"
						});
						var group_11 = new cpr.controls.Container();
						group_11.style.setClasses(["form-box", "vertical"]);
						// Layout
						var formLayout_4 = new cpr.controls.layouts.FormLayout();
						formLayout_4.topMargin = "5px";
						formLayout_4.rightMargin = "5px";
						formLayout_4.bottomMargin = "5px";
						formLayout_4.leftMargin = "5px";
						formLayout_4.horizontalSpacing = "10px";
						formLayout_4.verticalSpacing = "10px";
						formLayout_4.horizontalSeparatorWidth = 1;
						formLayout_4.verticalSeparatorWidth = 1;
						formLayout_4.setColumns(["1fr", "200px", "80px"]);
						formLayout_4.setRows(["30px", "30px"]);
						formLayout_4.setCustomRowShade(0, "#edeff6");
						formLayout_4.setRowAutoSizing(1, true);
						group_11.setLayout(formLayout_4);
						(function(container){
							var output_15 = new cpr.controls.Output();
							output_15.value = "시나리오";
							output_15.style.setClasses(["label"]);
							output_15.style.css({
								"border-right-style" : "none",
								"background-color" : "transparent",
								"border-left-style" : "none",
								"padding-left" : "15px",
								"border-bottom-style" : "none",
								"border-top-style" : "none",
								"text-align" : "left"
							});
							container.addChild(output_15, {
								"colIndex": 0,
								"rowIndex": 0
							});
							var output_16 = new cpr.controls.Output();
							output_16.value = "입력값";
							output_16.style.setClasses(["label"]);
							output_16.style.css({
								"border-right-style" : "none",
								"background-color" : "transparent",
								"border-left-style" : "none",
								"border-bottom-style" : "none",
								"border-top-style" : "none",
								"text-align" : "center"
							});
							container.addChild(output_16, {
								"colIndex": 1,
								"rowIndex": 0
							});
							var output_17 = new cpr.controls.Output();
							output_17.value = "기능확인";
							output_17.style.setClasses(["label"]);
							output_17.style.css({
								"border-right-style" : "none",
								"background-color" : "transparent",
								"border-left-style" : "none",
								"border-bottom-style" : "none",
								"border-top-style" : "none",
								"text-align" : "center"
							});
							container.addChild(output_17, {
								"colIndex": 2,
								"rowIndex": 0
							});
							var button_1 = new cpr.controls.Button("btnInit");
							button_1.value = "실행";
							button_1.style.setClasses(["btn-primary"]);
							if(typeof onBtnInitClick == "function") {
								button_1.addEventListener("click", onBtnInitClick);
							}
							container.addChild(button_1, {
								"colIndex": 2,
								"rowIndex": 1,
								"verticalAlign": "center",
								"height": 30
							});
							var comboBox_1 = new cpr.controls.ComboBox("sampleCmb1");
							comboBox_1.value = "1";
							(function(comboBox_1){
								comboBox_1.addItem(new cpr.controls.Item("50", "50"));
								comboBox_1.addItem(new cpr.controls.Item("50,70", "1"));
							})(comboBox_1);
							container.addChild(comboBox_1, {
								"colIndex": 1,
								"rowIndex": 1
							});
							var output_18 = new cpr.controls.Output();
							output_18.value = "입력값을 선택하고 실행 버튼을 누르면, 하단의 슬라이더 컨트롤에서 해당 속성의 기능을 확인할 수 있습니다. ";
							output_18.style.setClasses(["opt-tmpl"]);
							output_18.style.css({
								"background-color" : "transparent",
								"border-right-style" : "none",
								"border-left-style" : "none",
								"padding-left" : "15px",
								"border-bottom-style" : "none",
								"border-top-style" : "none",
								"text-align" : "left"
							});
							container.addChild(output_18, {
								"colIndex": 0,
								"rowIndex": 1
							});
						})(group_11);
						container.addChild(group_11, {
							"autoSize": "height",
							"width": "1220px",
							"height": "80px"
						});
						var group_12 = new cpr.controls.Container();
						group_12.style.setClasses(["attach-box"]);
						group_12.style.css({
							"border-right-style" : "solid",
							"border-top-width" : "1px",
							"border-bottom-color" : "#babfc7",
							"border-right-width" : "1px",
							"border-left-color" : "#babfc7",
							"border-right-color" : "#babfc7",
							"border-left-width" : "1px",
							"border-top-style" : "solid",
							"background-color" : "#e9e9e9",
							"border-left-style" : "solid",
							"border-bottom-width" : "1px",
							"border-top-color" : "#babfc7",
							"border-bottom-style" : "solid",
							"background-image" : "none"
						});
						// Layout
						var flowLayout_2 = new cpr.controls.layouts.FlowLayout();
						flowLayout_2.scrollable = false;
						flowLayout_2.horizontalSpacing = 20;
						flowLayout_2.verticalSpacing = 20;
						flowLayout_2.horizontalAlign = "center";
						flowLayout_2.verticalAlign = "middle";
						flowLayout_2.leftMargin = 20;
						flowLayout_2.rightMargin = 20;
						flowLayout_2.topMargin = 20;
						flowLayout_2.bottomMargin = 20;
						group_12.setLayout(flowLayout_2);
						(function(container){
							var group_13 = new cpr.controls.Container();
							// Layout
							var formLayout_5 = new cpr.controls.layouts.FormLayout();
							formLayout_5.topMargin = "0px";
							formLayout_5.rightMargin = "0px";
							formLayout_5.bottomMargin = "0px";
							formLayout_5.leftMargin = "0px";
							formLayout_5.horizontalSpacing = "5px";
							formLayout_5.verticalSpacing = "5px";
							formLayout_5.setColumns(["1fr"]);
							formLayout_5.setRows(["1fr", "20px"]);
							group_13.setLayout(formLayout_5);
							(function(container){
								var output_19 = new cpr.controls.Output();
								output_19.value = "<기능 확인 컨트롤>";
								output_19.style.setClasses(["text-center"]);
								container.addChild(output_19, {
									"colIndex": 0,
									"rowIndex": 1
								});
								var slider_2 = new cpr.controls.Slider("sampleSld1");
								container.addChild(slider_2, {
									"colIndex": 0,
									"rowIndex": 0
								});
							})(group_13);
							container.addChild(group_13, {
								"autoSize": "height",
								"width": "300px",
								"height": "50px"
							});
						})(group_12);
						container.addChild(group_12, {
							"autoSize": "height",
							"width": "1220px",
							"height": "337px"
						});
					})(group_8);
					container.addChild(group_8, {
						"autoSize": "height",
						"width": "1220px",
						"height": "780px"
					});
					var group_14 = new cpr.controls.Container();
					group_14.style.setClasses(["card-inner"]);
					// Layout
					var verticalLayout_8 = new cpr.controls.layouts.VerticalLayout();
					verticalLayout_8.spacing = 15;
					verticalLayout_8.leftMargin = 40;
					verticalLayout_8.rightMargin = 40;
					verticalLayout_8.topMargin = 20;
					verticalLayout_8.bottomMargin = 40;
					group_14.setLayout(verticalLayout_8);
					(function(container){
						var output_20 = new cpr.controls.Output();
						output_20.value = "direction";
						output_20.style.css({
							"color" : "#2263b3",
							"font-weight" : "700",
							"font-size" : "20px",
							"font-family" : "sans-serif , 'Malgun Gothic' , 'Noto Sans KR'"
						});
						container.addChild(output_20, {
							"autoSize": "none",
							"width": "1220px",
							"height": "38px"
						});
						var group_15 = new cpr.controls.Container();
						group_15.style.css({
							"background-color" : "#e9eff7",
							"background-image" : "none"
						});
						// Layout
						var verticalLayout_9 = new cpr.controls.layouts.VerticalLayout();
						verticalLayout_9.leftMargin = 30;
						verticalLayout_9.rightMargin = 30;
						verticalLayout_9.topMargin = 20;
						verticalLayout_9.bottomMargin = 20;
						group_15.setLayout(verticalLayout_9);
						(function(container){
							var output_21 = new cpr.controls.Output();
							output_21.value = "슬라이더의 이동 방향을 설정할 수 있는 속성입니다. 기본값은 forward이며, backward로 변경 시 역순으로 이동합니다.\r\n- forward : 순방향\r\n- backward : 역방향";
							output_21.style.setClasses(["opt-tmpl"]);
							output_21.style.css({
								"font-weight" : "700"
							});
							container.addChild(output_21, {
								"autoSize": "height",
								"width": "100px",
								"height": "40px"
							});
						})(group_15);
						container.addChild(group_15, {
							"autoSize": "height",
							"width": "1140px",
							"height": "80px"
						});
						var group_16 = new cpr.controls.Container();
						group_16.style.setClasses(["form-box", "vertical"]);
						// Layout
						var formLayout_6 = new cpr.controls.layouts.FormLayout();
						formLayout_6.topMargin = "5px";
						formLayout_6.rightMargin = "5px";
						formLayout_6.bottomMargin = "5px";
						formLayout_6.leftMargin = "5px";
						formLayout_6.horizontalSpacing = "10px";
						formLayout_6.verticalSpacing = "10px";
						formLayout_6.horizontalSeparatorWidth = 1;
						formLayout_6.verticalSeparatorWidth = 1;
						formLayout_6.setColumns(["1fr", "2fr"]);
						formLayout_6.setCustomColumnShade(0, "#edeff6");
						formLayout_6.setRows(["30px", "30px", "30px"]);
						formLayout_6.setRowAutoSizing(1, true);
						formLayout_6.setRowAutoSizing(2, true);
						group_16.setLayout(formLayout_6);
						(function(container){
							var output_22 = new cpr.controls.Output();
							output_22.value = "type";
							output_22.style.setClasses(["label"]);
							output_22.style.css({
								"border-right-style" : "none",
								"background-color" : "transparent",
								"border-left-style" : "none",
								"border-bottom-style" : "none",
								"border-top-style" : "none",
								"text-align" : "center"
							});
							container.addChild(output_22, {
								"colIndex": 0,
								"rowIndex": 0
							});
							var output_23 = new cpr.controls.Output();
							output_23.value = "\"backward\" | \"forward\"";
							output_23.style.css({
								"background-color" : "transparent",
								"border-right-style" : "none",
								"border-left-style" : "none",
								"border-bottom-style" : "none",
								"border-top-style" : "none",
								"text-align" : "center"
							});
							container.addChild(output_23, {
								"colIndex": 1,
								"rowIndex": 0
							});
							var output_24 = new cpr.controls.Output();
							output_24.value = "get";
							output_24.style.setClasses(["label"]);
							output_24.style.css({
								"border-right-style" : "none",
								"background-color" : "transparent",
								"border-left-style" : "none",
								"border-bottom-style" : "none",
								"border-top-style" : "none",
								"text-align" : "center"
							});
							container.addChild(output_24, {
								"colIndex": 0,
								"rowIndex": 1
							});
							var output_25 = new cpr.controls.Output();
							output_25.value = "set";
							output_25.style.setClasses(["label"]);
							output_25.style.css({
								"border-right-style" : "none",
								"background-color" : "transparent",
								"border-left-style" : "none",
								"border-bottom-style" : "none",
								"border-top-style" : "none",
								"text-align" : "center"
							});
							container.addChild(output_25, {
								"colIndex": 0,
								"rowIndex": 2
							});
							var output_26 = new cpr.controls.Output();
							output_26.value = "Slider의 이동방향을 반환합니다.";
							output_26.style.css({
								"background-color" : "transparent",
								"border-right-style" : "none",
								"border-left-style" : "none",
								"border-bottom-style" : "none",
								"border-top-style" : "none",
								"text-align" : "center"
							});
							container.addChild(output_26, {
								"colIndex": 1,
								"rowIndex": 1
							});
							var output_27 = new cpr.controls.Output();
							output_27.value = "Slider의 이동방향을 설정합니다.";
							output_27.style.css({
								"background-color" : "transparent",
								"border-right-style" : "none",
								"border-left-style" : "none",
								"border-bottom-style" : "none",
								"border-top-style" : "none",
								"text-align" : "center"
							});
							container.addChild(output_27, {
								"colIndex": 1,
								"rowIndex": 2
							});
						})(group_16);
						container.addChild(group_16, {
							"autoSize": "height",
							"width": "1220px",
							"height": "125px"
						});
						var group_17 = new cpr.controls.Container();
						group_17.style.setClasses(["form-box", "vertical"]);
						// Layout
						var formLayout_7 = new cpr.controls.layouts.FormLayout();
						formLayout_7.topMargin = "5px";
						formLayout_7.rightMargin = "5px";
						formLayout_7.bottomMargin = "5px";
						formLayout_7.leftMargin = "5px";
						formLayout_7.horizontalSpacing = "10px";
						formLayout_7.verticalSpacing = "10px";
						formLayout_7.horizontalSeparatorWidth = 1;
						formLayout_7.verticalSeparatorWidth = 1;
						formLayout_7.setColumns(["1fr", "200px", "80px"]);
						formLayout_7.setRows(["30px", "30px"]);
						formLayout_7.setCustomRowShade(0, "#edeff6");
						formLayout_7.setRowAutoSizing(1, true);
						group_17.setLayout(formLayout_7);
						(function(container){
							var output_28 = new cpr.controls.Output();
							output_28.value = "시나리오";
							output_28.style.setClasses(["label"]);
							output_28.style.css({
								"border-right-style" : "none",
								"background-color" : "transparent",
								"border-left-style" : "none",
								"padding-left" : "15px",
								"border-bottom-style" : "none",
								"border-top-style" : "none",
								"text-align" : "left"
							});
							container.addChild(output_28, {
								"colIndex": 0,
								"rowIndex": 0
							});
							var output_29 = new cpr.controls.Output();
							output_29.value = "입력값";
							output_29.style.setClasses(["label"]);
							output_29.style.css({
								"border-right-style" : "none",
								"background-color" : "transparent",
								"border-left-style" : "none",
								"border-bottom-style" : "none",
								"border-top-style" : "none",
								"text-align" : "center"
							});
							container.addChild(output_29, {
								"colIndex": 1,
								"rowIndex": 0
							});
							var output_30 = new cpr.controls.Output();
							output_30.value = "기능확인";
							output_30.style.setClasses(["label"]);
							output_30.style.css({
								"border-right-style" : "none",
								"background-color" : "transparent",
								"border-left-style" : "none",
								"border-bottom-style" : "none",
								"border-top-style" : "none",
								"text-align" : "center"
							});
							container.addChild(output_30, {
								"colIndex": 2,
								"rowIndex": 0
							});
							var button_2 = new cpr.controls.Button("btnInit2");
							button_2.value = "실행";
							button_2.style.setClasses(["btn-primary"]);
							if(typeof onBtnInit2Click == "function") {
								button_2.addEventListener("click", onBtnInit2Click);
							}
							container.addChild(button_2, {
								"colIndex": 2,
								"rowIndex": 1,
								"verticalAlign": "center",
								"height": 30
							});
							var output_31 = new cpr.controls.Output();
							output_31.value = "입력값을 선택하고 실행 버튼을 누르면, 하단의 슬라이더 컨트롤에서 해당 속성의 기능을 확인할 수 있습니다. ";
							output_31.style.setClasses(["opt-tmpl"]);
							output_31.style.css({
								"background-color" : "transparent",
								"border-right-style" : "none",
								"border-left-style" : "none",
								"padding-left" : "15px",
								"border-bottom-style" : "none",
								"border-top-style" : "none",
								"text-align" : "left"
							});
							container.addChild(output_31, {
								"colIndex": 0,
								"rowIndex": 1
							});
							var comboBox_2 = new cpr.controls.ComboBox("sampleCmb2");
							comboBox_2.value = "backward";
							(function(comboBox_2){
								comboBox_2.addItem(new cpr.controls.Item("forward", "forward"));
								comboBox_2.addItem(new cpr.controls.Item("bacekward", "backward"));
							})(comboBox_2);
							container.addChild(comboBox_2, {
								"colIndex": 1,
								"rowIndex": 1
							});
						})(group_17);
						container.addChild(group_17, {
							"autoSize": "height",
							"width": "1220px",
							"height": "80px"
						});
						var group_18 = new cpr.controls.Container();
						group_18.style.setClasses(["attach-box"]);
						group_18.style.css({
							"border-right-style" : "solid",
							"border-top-width" : "1px",
							"border-bottom-color" : "#babfc7",
							"border-right-width" : "1px",
							"border-left-color" : "#babfc7",
							"border-right-color" : "#babfc7",
							"border-left-width" : "1px",
							"border-top-style" : "solid",
							"background-color" : "#e9e9e9",
							"border-left-style" : "solid",
							"border-bottom-width" : "1px",
							"border-top-color" : "#babfc7",
							"border-bottom-style" : "solid",
							"background-image" : "none"
						});
						// Layout
						var flowLayout_3 = new cpr.controls.layouts.FlowLayout();
						flowLayout_3.scrollable = false;
						flowLayout_3.horizontalSpacing = 20;
						flowLayout_3.verticalSpacing = 20;
						flowLayout_3.horizontalAlign = "center";
						flowLayout_3.verticalAlign = "middle";
						flowLayout_3.leftMargin = 20;
						flowLayout_3.rightMargin = 20;
						flowLayout_3.topMargin = 20;
						flowLayout_3.bottomMargin = 20;
						group_18.setLayout(flowLayout_3);
						(function(container){
							var group_19 = new cpr.controls.Container();
							// Layout
							var formLayout_8 = new cpr.controls.layouts.FormLayout();
							formLayout_8.topMargin = "0px";
							formLayout_8.rightMargin = "0px";
							formLayout_8.bottomMargin = "0px";
							formLayout_8.leftMargin = "0px";
							formLayout_8.horizontalSpacing = "5px";
							formLayout_8.verticalSpacing = "5px";
							formLayout_8.setColumns(["1fr"]);
							formLayout_8.setRows(["1fr", "20px"]);
							group_19.setLayout(formLayout_8);
							(function(container){
								var output_32 = new cpr.controls.Output();
								output_32.value = "<기능 확인 컨트롤>";
								output_32.style.setClasses(["text-center"]);
								container.addChild(output_32, {
									"colIndex": 0,
									"rowIndex": 1
								});
								var slider_3 = new cpr.controls.Slider("sampleSld2");
								slider_3.value = "70";
								container.addChild(slider_3, {
									"colIndex": 0,
									"rowIndex": 0
								});
							})(group_19);
							container.addChild(group_19, {
								"autoSize": "height",
								"width": "300px",
								"height": "50px"
							});
						})(group_18);
						container.addChild(group_18, {
							"autoSize": "height",
							"width": "1220px",
							"height": "337px"
						});
					})(group_14);
					container.addChild(group_14, {
						"autoSize": "height",
						"width": "1220px",
						"height": "780px"
					});
					var group_20 = new cpr.controls.Container();
					group_20.style.setClasses(["card-inner"]);
					// Layout
					var verticalLayout_10 = new cpr.controls.layouts.VerticalLayout();
					verticalLayout_10.spacing = 15;
					verticalLayout_10.leftMargin = 40;
					verticalLayout_10.rightMargin = 40;
					verticalLayout_10.topMargin = 20;
					verticalLayout_10.bottomMargin = 40;
					group_20.setLayout(verticalLayout_10);
					(function(container){
						var output_33 = new cpr.controls.Output();
						output_33.value = "range";
						output_33.style.css({
							"color" : "#2263b3",
							"font-weight" : "700",
							"font-size" : "20px",
							"font-family" : "sans-serif , 'Malgun Gothic' , 'Noto Sans KR'"
						});
						container.addChild(output_33, {
							"autoSize": "none",
							"width": "1220px",
							"height": "38px"
						});
						var group_21 = new cpr.controls.Container();
						group_21.style.css({
							"background-color" : "#e9eff7",
							"background-image" : "none"
						});
						// Layout
						var verticalLayout_11 = new cpr.controls.layouts.VerticalLayout();
						verticalLayout_11.leftMargin = 30;
						verticalLayout_11.rightMargin = 30;
						verticalLayout_11.topMargin = 20;
						verticalLayout_11.bottomMargin = 20;
						group_21.setLayout(verticalLayout_11);
						(function(container){
							var output_34 = new cpr.controls.Output();
							output_34.value = "슬라이더 값의 범위를 조절할 수 있도록 슬라이더 값을 2개로 변경할 수 있는 설정입니다. 기본값은 false이며, true로 변경할 수 있습니다.";
							output_34.style.setClasses(["opt-tmpl"]);
							output_34.style.css({
								"font-weight" : "700"
							});
							container.addChild(output_34, {
								"autoSize": "height",
								"width": "100px",
								"height": "40px"
							});
						})(group_21);
						container.addChild(group_21, {
							"autoSize": "height",
							"width": "1140px",
							"height": "80px"
						});
						var group_22 = new cpr.controls.Container();
						group_22.style.setClasses(["form-box", "vertical"]);
						// Layout
						var formLayout_9 = new cpr.controls.layouts.FormLayout();
						formLayout_9.topMargin = "5px";
						formLayout_9.rightMargin = "5px";
						formLayout_9.bottomMargin = "5px";
						formLayout_9.leftMargin = "5px";
						formLayout_9.horizontalSpacing = "10px";
						formLayout_9.verticalSpacing = "10px";
						formLayout_9.horizontalSeparatorWidth = 1;
						formLayout_9.verticalSeparatorWidth = 1;
						formLayout_9.setColumns(["1fr", "2fr"]);
						formLayout_9.setCustomColumnShade(0, "#edeff6");
						formLayout_9.setRows(["30px", "30px", "30px"]);
						formLayout_9.setRowAutoSizing(1, true);
						formLayout_9.setRowAutoSizing(2, true);
						group_22.setLayout(formLayout_9);
						(function(container){
							var output_35 = new cpr.controls.Output();
							output_35.value = "type";
							output_35.style.setClasses(["label"]);
							output_35.style.css({
								"border-right-style" : "none",
								"background-color" : "transparent",
								"border-left-style" : "none",
								"font-size" : "16px",
								"border-bottom-style" : "none",
								"border-top-style" : "none",
								"text-align" : "center"
							});
							container.addChild(output_35, {
								"colIndex": 0,
								"rowIndex": 0
							});
							var output_36 = new cpr.controls.Output();
							output_36.value = "Boolean ( Default : false )";
							output_36.style.css({
								"background-color" : "transparent",
								"border-right-style" : "none",
								"border-left-style" : "none",
								"border-bottom-style" : "none",
								"border-top-style" : "none",
								"text-align" : "center"
							});
							container.addChild(output_36, {
								"colIndex": 1,
								"rowIndex": 0
							});
							var output_37 = new cpr.controls.Output();
							output_37.value = "get";
							output_37.style.setClasses(["label"]);
							output_37.style.css({
								"border-right-style" : "none",
								"background-color" : "transparent",
								"border-left-style" : "none",
								"font-size" : "16px",
								"border-bottom-style" : "none",
								"border-top-style" : "none",
								"text-align" : "center"
							});
							container.addChild(output_37, {
								"colIndex": 0,
								"rowIndex": 1
							});
							var output_38 = new cpr.controls.Output();
							output_38.value = "set";
							output_38.style.setClasses(["label"]);
							output_38.style.css({
								"border-right-style" : "none",
								"background-color" : "transparent",
								"border-left-style" : "none",
								"font-size" : "16px",
								"border-bottom-style" : "none",
								"border-top-style" : "none",
								"text-align" : "center"
							});
							container.addChild(output_38, {
								"colIndex": 0,
								"rowIndex": 2
							});
							var output_39 = new cpr.controls.Output();
							output_39.value = "값의 범위를 조정하는 모드 적용 여부를 반환합니다.";
							output_39.style.css({
								"background-color" : "transparent",
								"border-right-style" : "none",
								"border-left-style" : "none",
								"border-bottom-style" : "none",
								"border-top-style" : "none",
								"text-align" : "center"
							});
							container.addChild(output_39, {
								"colIndex": 1,
								"rowIndex": 1
							});
							var output_40 = new cpr.controls.Output();
							output_40.value = "값의 범위를 조정하는 모드 적용 여부를 설정합니다.";
							output_40.style.css({
								"background-color" : "transparent",
								"border-right-style" : "none",
								"border-left-style" : "none",
								"border-bottom-style" : "none",
								"border-top-style" : "none",
								"text-align" : "center"
							});
							container.addChild(output_40, {
								"colIndex": 1,
								"rowIndex": 2
							});
						})(group_22);
						container.addChild(group_22, {
							"autoSize": "height",
							"width": "1220px",
							"height": "125px"
						});
						var group_23 = new cpr.controls.Container();
						group_23.style.setClasses(["form-box", "vertical"]);
						// Layout
						var formLayout_10 = new cpr.controls.layouts.FormLayout();
						formLayout_10.topMargin = "5px";
						formLayout_10.rightMargin = "5px";
						formLayout_10.bottomMargin = "5px";
						formLayout_10.leftMargin = "5px";
						formLayout_10.horizontalSpacing = "10px";
						formLayout_10.verticalSpacing = "10px";
						formLayout_10.horizontalSeparatorWidth = 1;
						formLayout_10.verticalSeparatorWidth = 1;
						formLayout_10.setColumns(["1fr", "200px", "80px"]);
						formLayout_10.setRows(["30px", "30px"]);
						formLayout_10.setCustomRowShade(0, "#edeff6");
						formLayout_10.setRowAutoSizing(1, true);
						group_23.setLayout(formLayout_10);
						(function(container){
							var output_41 = new cpr.controls.Output();
							output_41.value = "시나리오";
							output_41.style.setClasses(["label"]);
							output_41.style.css({
								"border-right-style" : "none",
								"background-color" : "transparent",
								"border-left-style" : "none",
								"padding-left" : "15px",
								"border-bottom-style" : "none",
								"border-top-style" : "none",
								"text-align" : "left"
							});
							container.addChild(output_41, {
								"colIndex": 0,
								"rowIndex": 0
							});
							var output_42 = new cpr.controls.Output();
							output_42.value = "입력값";
							output_42.style.setClasses(["label"]);
							output_42.style.css({
								"border-right-style" : "none",
								"background-color" : "transparent",
								"border-left-style" : "none",
								"border-bottom-style" : "none",
								"border-top-style" : "none",
								"text-align" : "center"
							});
							container.addChild(output_42, {
								"colIndex": 1,
								"rowIndex": 0
							});
							var output_43 = new cpr.controls.Output();
							output_43.value = "기능확인";
							output_43.style.setClasses(["label"]);
							output_43.style.css({
								"border-right-style" : "none",
								"background-color" : "transparent",
								"border-left-style" : "none",
								"border-bottom-style" : "none",
								"border-top-style" : "none",
								"text-align" : "center"
							});
							container.addChild(output_43, {
								"colIndex": 2,
								"rowIndex": 0
							});
							var button_3 = new cpr.controls.Button("btnInit3");
							button_3.value = "실행";
							button_3.style.setClasses(["btn-primary"]);
							if(typeof onBtnInit3Click == "function") {
								button_3.addEventListener("click", onBtnInit3Click);
							}
							container.addChild(button_3, {
								"colIndex": 2,
								"rowIndex": 1,
								"verticalAlign": "center",
								"height": 30
							});
							var comboBox_3 = new cpr.controls.ComboBox("sampleCmb3");
							comboBox_3.value = "true";
							(function(comboBox_3){
								comboBox_3.addItem(new cpr.controls.Item("true", "true"));
								comboBox_3.addItem(new cpr.controls.Item("false", "false"));
							})(comboBox_3);
							container.addChild(comboBox_3, {
								"colIndex": 1,
								"rowIndex": 1
							});
							var output_44 = new cpr.controls.Output();
							output_44.value = "입력값을 선택하고 실행 버튼을 누르면, 하단의 슬라이더 컨트롤에서 해당 속성의 기능을 확인할 수 있습니다. ";
							output_44.style.setClasses(["opt-tmpl"]);
							output_44.style.css({
								"background-color" : "transparent",
								"border-right-style" : "none",
								"border-left-style" : "none",
								"padding-left" : "15px",
								"border-bottom-style" : "none",
								"border-top-style" : "none",
								"text-align" : "left"
							});
							container.addChild(output_44, {
								"colIndex": 0,
								"rowIndex": 1
							});
						})(group_23);
						container.addChild(group_23, {
							"autoSize": "height",
							"width": "1220px",
							"height": "80px"
						});
						var group_24 = new cpr.controls.Container();
						group_24.style.setClasses(["attach-box"]);
						group_24.style.css({
							"border-right-style" : "solid",
							"border-top-width" : "1px",
							"border-bottom-color" : "#babfc7",
							"border-right-width" : "1px",
							"border-left-color" : "#babfc7",
							"border-right-color" : "#babfc7",
							"border-left-width" : "1px",
							"border-top-style" : "solid",
							"background-color" : "#e9e9e9",
							"border-left-style" : "solid",
							"border-bottom-width" : "1px",
							"border-top-color" : "#babfc7",
							"border-bottom-style" : "solid",
							"background-image" : "none"
						});
						// Layout
						var flowLayout_4 = new cpr.controls.layouts.FlowLayout();
						flowLayout_4.scrollable = false;
						flowLayout_4.horizontalSpacing = 20;
						flowLayout_4.verticalSpacing = 20;
						flowLayout_4.horizontalAlign = "center";
						flowLayout_4.verticalAlign = "middle";
						flowLayout_4.leftMargin = 20;
						flowLayout_4.rightMargin = 20;
						flowLayout_4.topMargin = 20;
						flowLayout_4.bottomMargin = 20;
						group_24.setLayout(flowLayout_4);
						(function(container){
							var group_25 = new cpr.controls.Container();
							// Layout
							var formLayout_11 = new cpr.controls.layouts.FormLayout();
							formLayout_11.topMargin = "0px";
							formLayout_11.rightMargin = "0px";
							formLayout_11.bottomMargin = "0px";
							formLayout_11.leftMargin = "0px";
							formLayout_11.horizontalSpacing = "5px";
							formLayout_11.verticalSpacing = "5px";
							formLayout_11.setColumns(["1fr"]);
							formLayout_11.setRows(["1fr", "20px"]);
							group_25.setLayout(formLayout_11);
							(function(container){
								var output_45 = new cpr.controls.Output();
								output_45.value = "<기능 확인 컨트롤>";
								output_45.style.setClasses(["text-center"]);
								container.addChild(output_45, {
									"colIndex": 0,
									"rowIndex": 1
								});
								var slider_4 = new cpr.controls.Slider("sampleSld3");
								slider_4.value = "30";
								container.addChild(slider_4, {
									"colIndex": 0,
									"rowIndex": 0
								});
							})(group_25);
							container.addChild(group_25, {
								"autoSize": "none",
								"width": "300px",
								"height": "50px"
							});
						})(group_24);
						container.addChild(group_24, {
							"autoSize": "height",
							"width": "1220px",
							"height": "337px"
						});
					})(group_20);
					container.addChild(group_20, {
						"autoSize": "height",
						"width": "1220px",
						"height": "780px"
					});
					var group_26 = new cpr.controls.Container();
					group_26.style.setClasses(["card-inner"]);
					// Layout
					var verticalLayout_12 = new cpr.controls.layouts.VerticalLayout();
					verticalLayout_12.spacing = 15;
					verticalLayout_12.leftMargin = 40;
					verticalLayout_12.rightMargin = 40;
					verticalLayout_12.topMargin = 20;
					verticalLayout_12.bottomMargin = 40;
					group_26.setLayout(verticalLayout_12);
					(function(container){
						var output_46 = new cpr.controls.Output();
						output_46.value = "orientation";
						output_46.style.css({
							"color" : "#2263b3",
							"font-weight" : "700",
							"font-size" : "20px",
							"font-family" : "sans-serif , 'Malgun Gothic' , 'Noto Sans KR'"
						});
						container.addChild(output_46, {
							"autoSize": "none",
							"width": "1220px",
							"height": "38px"
						});
						var group_27 = new cpr.controls.Container();
						group_27.style.css({
							"background-color" : "#e9eff7",
							"background-image" : "none"
						});
						// Layout
						var verticalLayout_13 = new cpr.controls.layouts.VerticalLayout();
						verticalLayout_13.leftMargin = 30;
						verticalLayout_13.rightMargin = 30;
						verticalLayout_13.topMargin = 20;
						verticalLayout_13.bottomMargin = 20;
						group_27.setLayout(verticalLayout_13);
						(function(container){
							var output_47 = new cpr.controls.Output();
							output_47.value = "슬라이더의 방향을 결정하는 속성입니다. 기본값은 horizontal이며, vertical로 변경 시 세로로 모양이 변경됩니다.\r\n- horizontal : 가로 방향\r\n- vertical : 세로 방향";
							output_47.style.setClasses(["opt-tmpl"]);
							output_47.style.css({
								"font-weight" : "700"
							});
							container.addChild(output_47, {
								"autoSize": "height",
								"width": "100px",
								"height": "40px"
							});
						})(group_27);
						container.addChild(group_27, {
							"autoSize": "height",
							"width": "1140px",
							"height": "80px"
						});
						var group_28 = new cpr.controls.Container();
						group_28.style.setClasses(["form-box", "vertical"]);
						// Layout
						var formLayout_12 = new cpr.controls.layouts.FormLayout();
						formLayout_12.topMargin = "5px";
						formLayout_12.rightMargin = "5px";
						formLayout_12.bottomMargin = "5px";
						formLayout_12.leftMargin = "5px";
						formLayout_12.horizontalSpacing = "10px";
						formLayout_12.verticalSpacing = "10px";
						formLayout_12.horizontalSeparatorWidth = 1;
						formLayout_12.verticalSeparatorWidth = 1;
						formLayout_12.setColumns(["1fr", "2fr"]);
						formLayout_12.setCustomColumnShade(0, "#edeff6");
						formLayout_12.setRows(["30px", "30px", "30px"]);
						formLayout_12.setRowAutoSizing(1, true);
						formLayout_12.setRowAutoSizing(2, true);
						group_28.setLayout(formLayout_12);
						(function(container){
							var output_48 = new cpr.controls.Output();
							output_48.value = "type";
							output_48.style.setClasses(["label"]);
							output_48.style.css({
								"border-right-style" : "none",
								"background-color" : "transparent",
								"border-left-style" : "none",
								"font-size" : "16px",
								"border-bottom-style" : "none",
								"border-top-style" : "none",
								"text-align" : "center"
							});
							container.addChild(output_48, {
								"colIndex": 0,
								"rowIndex": 0
							});
							var output_49 = new cpr.controls.Output();
							output_49.value = "\"horizontal\" | \"vertical\"";
							output_49.style.css({
								"background-color" : "transparent",
								"border-right-style" : "none",
								"border-left-style" : "none",
								"border-bottom-style" : "none",
								"border-top-style" : "none",
								"text-align" : "center"
							});
							container.addChild(output_49, {
								"colIndex": 1,
								"rowIndex": 0
							});
							var output_50 = new cpr.controls.Output();
							output_50.value = "get";
							output_50.style.setClasses(["label"]);
							output_50.style.css({
								"border-right-style" : "none",
								"background-color" : "transparent",
								"border-left-style" : "none",
								"font-size" : "16px",
								"border-bottom-style" : "none",
								"border-top-style" : "none",
								"text-align" : "center"
							});
							container.addChild(output_50, {
								"colIndex": 0,
								"rowIndex": 1
							});
							var output_51 = new cpr.controls.Output();
							output_51.value = "set";
							output_51.style.setClasses(["label"]);
							output_51.style.css({
								"border-right-style" : "none",
								"background-color" : "transparent",
								"border-left-style" : "none",
								"font-size" : "16px",
								"border-bottom-style" : "none",
								"border-top-style" : "none",
								"text-align" : "center"
							});
							container.addChild(output_51, {
								"colIndex": 0,
								"rowIndex": 2
							});
							var output_52 = new cpr.controls.Output();
							output_52.value = "Slider의 방향을 반환합니다.";
							output_52.style.css({
								"background-color" : "transparent",
								"border-right-style" : "none",
								"border-left-style" : "none",
								"border-bottom-style" : "none",
								"border-top-style" : "none",
								"text-align" : "center"
							});
							container.addChild(output_52, {
								"colIndex": 1,
								"rowIndex": 1
							});
							var output_53 = new cpr.controls.Output();
							output_53.value = "Slider의 방향을 설정합니다.";
							output_53.style.css({
								"background-color" : "transparent",
								"border-right-style" : "none",
								"border-left-style" : "none",
								"border-bottom-style" : "none",
								"border-top-style" : "none",
								"text-align" : "center"
							});
							container.addChild(output_53, {
								"colIndex": 1,
								"rowIndex": 2
							});
						})(group_28);
						container.addChild(group_28, {
							"autoSize": "height",
							"width": "1220px",
							"height": "125px"
						});
						var group_29 = new cpr.controls.Container();
						group_29.style.setClasses(["form-box", "vertical"]);
						// Layout
						var formLayout_13 = new cpr.controls.layouts.FormLayout();
						formLayout_13.topMargin = "5px";
						formLayout_13.rightMargin = "5px";
						formLayout_13.bottomMargin = "5px";
						formLayout_13.leftMargin = "5px";
						formLayout_13.horizontalSpacing = "10px";
						formLayout_13.verticalSpacing = "10px";
						formLayout_13.horizontalSeparatorWidth = 1;
						formLayout_13.verticalSeparatorWidth = 1;
						formLayout_13.setColumns(["1fr", "200px", "80px"]);
						formLayout_13.setRows(["30px", "30px"]);
						formLayout_13.setCustomRowShade(0, "#edeff6");
						formLayout_13.setRowAutoSizing(1, true);
						group_29.setLayout(formLayout_13);
						(function(container){
							var output_54 = new cpr.controls.Output();
							output_54.value = "시나리오";
							output_54.style.setClasses(["label"]);
							output_54.style.css({
								"border-right-style" : "none",
								"background-color" : "transparent",
								"border-left-style" : "none",
								"padding-left" : "15px",
								"border-bottom-style" : "none",
								"border-top-style" : "none",
								"text-align" : "left"
							});
							container.addChild(output_54, {
								"colIndex": 0,
								"rowIndex": 0
							});
							var output_55 = new cpr.controls.Output();
							output_55.value = "입력값";
							output_55.style.setClasses(["label"]);
							output_55.style.css({
								"border-right-style" : "none",
								"background-color" : "transparent",
								"border-left-style" : "none",
								"border-bottom-style" : "none",
								"border-top-style" : "none",
								"text-align" : "center"
							});
							container.addChild(output_55, {
								"colIndex": 1,
								"rowIndex": 0
							});
							var output_56 = new cpr.controls.Output();
							output_56.value = "기능확인";
							output_56.style.setClasses(["label"]);
							output_56.style.css({
								"border-right-style" : "none",
								"background-color" : "transparent",
								"border-left-style" : "none",
								"border-bottom-style" : "none",
								"border-top-style" : "none",
								"text-align" : "center"
							});
							container.addChild(output_56, {
								"colIndex": 2,
								"rowIndex": 0
							});
							var button_4 = new cpr.controls.Button("btnInit4");
							button_4.value = "실행";
							button_4.style.setClasses(["btn-primary"]);
							if(typeof onBtnInit4Click == "function") {
								button_4.addEventListener("click", onBtnInit4Click);
							}
							container.addChild(button_4, {
								"colIndex": 2,
								"rowIndex": 1,
								"verticalAlign": "center",
								"height": 30
							});
							var output_57 = new cpr.controls.Output();
							output_57.value = "입력값을 선택하고 실행 버튼을 누르면, 하단의 슬라이더 컨트롤에서 해당 속성의 기능을 확인할 수 있습니다. ";
							output_57.style.setClasses(["opt-tmpl"]);
							output_57.style.css({
								"background-color" : "transparent",
								"border-right-style" : "none",
								"border-left-style" : "none",
								"padding-left" : "15px",
								"border-bottom-style" : "none",
								"border-top-style" : "none",
								"text-align" : "left"
							});
							container.addChild(output_57, {
								"colIndex": 0,
								"rowIndex": 1
							});
							var comboBox_4 = new cpr.controls.ComboBox("sampleCmb4");
							comboBox_4.value = "vertical";
							(function(comboBox_4){
								comboBox_4.addItem(new cpr.controls.Item("horizontal", "horizontal"));
								comboBox_4.addItem(new cpr.controls.Item("vertical", "vertical"));
							})(comboBox_4);
							container.addChild(comboBox_4, {
								"colIndex": 1,
								"rowIndex": 1
							});
						})(group_29);
						container.addChild(group_29, {
							"autoSize": "height",
							"width": "1220px",
							"height": "80px"
						});
						var group_30 = new cpr.controls.Container();
						group_30.style.setClasses(["attach-box"]);
						group_30.style.css({
							"border-right-style" : "solid",
							"border-top-width" : "1px",
							"border-bottom-color" : "#babfc7",
							"border-right-width" : "1px",
							"border-left-color" : "#babfc7",
							"border-right-color" : "#babfc7",
							"border-left-width" : "1px",
							"border-top-style" : "solid",
							"background-color" : "#e9e9e9",
							"border-left-style" : "solid",
							"border-bottom-width" : "1px",
							"border-top-color" : "#babfc7",
							"border-bottom-style" : "solid",
							"background-image" : "none"
						});
						// Layout
						var flowLayout_5 = new cpr.controls.layouts.FlowLayout();
						flowLayout_5.scrollable = false;
						flowLayout_5.horizontalSpacing = 20;
						flowLayout_5.verticalSpacing = 20;
						flowLayout_5.horizontalAlign = "center";
						flowLayout_5.verticalAlign = "middle";
						flowLayout_5.leftMargin = 20;
						flowLayout_5.rightMargin = 20;
						flowLayout_5.topMargin = 20;
						flowLayout_5.bottomMargin = 20;
						group_30.setLayout(flowLayout_5);
						(function(container){
							var group_31 = new cpr.controls.Container();
							// Layout
							var formLayout_14 = new cpr.controls.layouts.FormLayout();
							formLayout_14.topMargin = "0px";
							formLayout_14.rightMargin = "0px";
							formLayout_14.bottomMargin = "0px";
							formLayout_14.leftMargin = "0px";
							formLayout_14.horizontalSpacing = "5px";
							formLayout_14.verticalSpacing = "5px";
							formLayout_14.setColumns(["1fr"]);
							formLayout_14.setRows(["1fr", "20px"]);
							group_31.setLayout(formLayout_14);
							(function(container){
								var output_58 = new cpr.controls.Output();
								output_58.value = "<기능 확인 컨트롤>";
								output_58.style.setClasses(["text-center"]);
								container.addChild(output_58, {
									"colIndex": 0,
									"rowIndex": 1
								});
								var slider_5 = new cpr.controls.Slider("sampleSld4");
								slider_5.value = "30";
								container.addChild(slider_5, {
									"colIndex": 0,
									"rowIndex": 0
								});
							})(group_31);
							container.addChild(group_31, {
								"autoSize": "none",
								"width": "300px",
								"height": "300px"
							});
						})(group_30);
						container.addChild(group_30, {
							"autoSize": "height",
							"width": "1220px",
							"height": "337px"
						});
					})(group_26);
					container.addChild(group_26, {
						"autoSize": "height",
						"width": "1220px",
						"height": "780px"
					});
					var group_32 = new cpr.controls.Container();
					group_32.style.setClasses(["card-inner"]);
					// Layout
					var verticalLayout_14 = new cpr.controls.layouts.VerticalLayout();
					verticalLayout_14.spacing = 15;
					verticalLayout_14.leftMargin = 40;
					verticalLayout_14.rightMargin = 40;
					verticalLayout_14.topMargin = 20;
					verticalLayout_14.bottomMargin = 40;
					group_32.setLayout(verticalLayout_14);
					(function(container){
						var output_59 = new cpr.controls.Output();
						output_59.value = "step";
						output_59.style.css({
							"color" : "#2263b3",
							"font-weight" : "700",
							"font-size" : "20px",
							"font-family" : "sans-serif , 'Malgun Gothic' , 'Noto Sans KR'"
						});
						container.addChild(output_59, {
							"autoSize": "none",
							"width": "1220px",
							"height": "38px"
						});
						var group_33 = new cpr.controls.Container();
						group_33.style.css({
							"background-color" : "#e9eff7",
							"background-image" : "none"
						});
						// Layout
						var verticalLayout_15 = new cpr.controls.layouts.VerticalLayout();
						verticalLayout_15.leftMargin = 30;
						verticalLayout_15.rightMargin = 30;
						verticalLayout_15.topMargin = 20;
						verticalLayout_15.bottomMargin = 20;
						group_33.setLayout(verticalLayout_15);
						(function(container){
							var output_60 = new cpr.controls.Output();
							output_60.value = "슬라이더의 이동 값을 설정하는 속성입니다.";
							output_60.style.setClasses(["opt-tmpl"]);
							output_60.style.css({
								"font-weight" : "700"
							});
							container.addChild(output_60, {
								"autoSize": "height",
								"width": "100px",
								"height": "40px"
							});
						})(group_33);
						container.addChild(group_33, {
							"autoSize": "height",
							"width": "1140px",
							"height": "80px"
						});
						var group_34 = new cpr.controls.Container();
						group_34.style.setClasses(["form-box", "vertical"]);
						// Layout
						var formLayout_15 = new cpr.controls.layouts.FormLayout();
						formLayout_15.topMargin = "5px";
						formLayout_15.rightMargin = "5px";
						formLayout_15.bottomMargin = "5px";
						formLayout_15.leftMargin = "5px";
						formLayout_15.horizontalSpacing = "10px";
						formLayout_15.verticalSpacing = "10px";
						formLayout_15.horizontalSeparatorWidth = 1;
						formLayout_15.verticalSeparatorWidth = 1;
						formLayout_15.setColumns(["1fr", "2fr"]);
						formLayout_15.setCustomColumnShade(0, "#edeff6");
						formLayout_15.setRows(["30px", "30px", "30px"]);
						formLayout_15.setRowAutoSizing(1, true);
						formLayout_15.setRowAutoSizing(2, true);
						group_34.setLayout(formLayout_15);
						(function(container){
							var output_61 = new cpr.controls.Output();
							output_61.value = "type";
							output_61.style.setClasses(["label"]);
							output_61.style.css({
								"border-right-style" : "none",
								"background-color" : "transparent",
								"border-left-style" : "none",
								"font-size" : "16px",
								"border-bottom-style" : "none",
								"border-top-style" : "none",
								"text-align" : "center"
							});
							container.addChild(output_61, {
								"colIndex": 0,
								"rowIndex": 0
							});
							var output_62 = new cpr.controls.Output();
							output_62.value = "Number";
							output_62.style.css({
								"background-color" : "transparent",
								"border-right-style" : "none",
								"border-left-style" : "none",
								"border-bottom-style" : "none",
								"border-top-style" : "none",
								"text-align" : "center"
							});
							container.addChild(output_62, {
								"colIndex": 1,
								"rowIndex": 0
							});
							var output_63 = new cpr.controls.Output();
							output_63.value = "get";
							output_63.style.setClasses(["label"]);
							output_63.style.css({
								"border-right-style" : "none",
								"background-color" : "transparent",
								"border-left-style" : "none",
								"font-size" : "16px",
								"border-bottom-style" : "none",
								"border-top-style" : "none",
								"text-align" : "center"
							});
							container.addChild(output_63, {
								"colIndex": 0,
								"rowIndex": 1
							});
							var output_64 = new cpr.controls.Output();
							output_64.value = "set";
							output_64.style.setClasses(["label"]);
							output_64.style.css({
								"border-right-style" : "none",
								"background-color" : "transparent",
								"border-left-style" : "none",
								"font-size" : "16px",
								"border-bottom-style" : "none",
								"border-top-style" : "none",
								"text-align" : "center"
							});
							container.addChild(output_64, {
								"colIndex": 0,
								"rowIndex": 2
							});
							var output_65 = new cpr.controls.Output();
							output_65.value = "증가 값을 반환합니다.";
							output_65.style.css({
								"background-color" : "transparent",
								"border-right-style" : "none",
								"border-left-style" : "none",
								"border-bottom-style" : "none",
								"border-top-style" : "none",
								"text-align" : "center"
							});
							container.addChild(output_65, {
								"colIndex": 1,
								"rowIndex": 1
							});
							var output_66 = new cpr.controls.Output();
							output_66.value = "증가 값을 설정합니다.";
							output_66.style.css({
								"background-color" : "transparent",
								"border-right-style" : "none",
								"border-left-style" : "none",
								"border-bottom-style" : "none",
								"border-top-style" : "none",
								"text-align" : "center"
							});
							container.addChild(output_66, {
								"colIndex": 1,
								"rowIndex": 2
							});
						})(group_34);
						container.addChild(group_34, {
							"autoSize": "height",
							"width": "1220px",
							"height": "125px"
						});
						var group_35 = new cpr.controls.Container();
						group_35.style.setClasses(["form-box", "vertical"]);
						// Layout
						var formLayout_16 = new cpr.controls.layouts.FormLayout();
						formLayout_16.topMargin = "5px";
						formLayout_16.rightMargin = "5px";
						formLayout_16.bottomMargin = "5px";
						formLayout_16.leftMargin = "5px";
						formLayout_16.horizontalSpacing = "10px";
						formLayout_16.verticalSpacing = "10px";
						formLayout_16.horizontalSeparatorWidth = 1;
						formLayout_16.verticalSeparatorWidth = 1;
						formLayout_16.setColumns(["1fr", "200px", "80px"]);
						formLayout_16.setRows(["30px", "30px"]);
						formLayout_16.setCustomRowShade(0, "#edeff6");
						formLayout_16.setRowAutoSizing(1, true);
						group_35.setLayout(formLayout_16);
						(function(container){
							var output_67 = new cpr.controls.Output();
							output_67.value = "시나리오";
							output_67.style.setClasses(["label"]);
							output_67.style.css({
								"border-right-style" : "none",
								"background-color" : "transparent",
								"border-left-style" : "none",
								"padding-left" : "15px",
								"border-bottom-style" : "none",
								"border-top-style" : "none",
								"text-align" : "left"
							});
							container.addChild(output_67, {
								"colIndex": 0,
								"rowIndex": 0
							});
							var output_68 = new cpr.controls.Output();
							output_68.value = "입력값";
							output_68.style.setClasses(["label"]);
							output_68.style.css({
								"border-right-style" : "none",
								"background-color" : "transparent",
								"border-left-style" : "none",
								"border-bottom-style" : "none",
								"border-top-style" : "none",
								"text-align" : "center"
							});
							container.addChild(output_68, {
								"colIndex": 1,
								"rowIndex": 0
							});
							var output_69 = new cpr.controls.Output();
							output_69.value = "기능확인";
							output_69.style.setClasses(["label"]);
							output_69.style.css({
								"border-right-style" : "none",
								"background-color" : "transparent",
								"border-left-style" : "none",
								"border-bottom-style" : "none",
								"border-top-style" : "none",
								"text-align" : "center"
							});
							container.addChild(output_69, {
								"colIndex": 2,
								"rowIndex": 0
							});
							var button_5 = new cpr.controls.Button("btnInit5");
							button_5.value = "실행";
							button_5.style.setClasses(["btn-primary"]);
							if(typeof onBtnInit5Click == "function") {
								button_5.addEventListener("click", onBtnInit5Click);
							}
							container.addChild(button_5, {
								"colIndex": 2,
								"rowIndex": 1,
								"verticalAlign": "center",
								"height": 30
							});
							var comboBox_5 = new cpr.controls.ComboBox("sampleCmb5");
							comboBox_5.value = "30";
							(function(comboBox_5){
								comboBox_5.addItem(new cpr.controls.Item("10", "10"));
								comboBox_5.addItem(new cpr.controls.Item("20", "20"));
								comboBox_5.addItem(new cpr.controls.Item("30", "30"));
							})(comboBox_5);
							container.addChild(comboBox_5, {
								"colIndex": 1,
								"rowIndex": 1
							});
							var output_70 = new cpr.controls.Output();
							output_70.value = "우측 입력값을 선택하고 실행 버튼을 누르면, 하단의 슬라이더 컨트롤에서 해당 속성의 기능을 확인할 수 있습니다.";
							output_70.style.setClasses(["opt-tmpl"]);
							output_70.style.css({
								"background-color" : "transparent",
								"border-right-style" : "none",
								"border-left-style" : "none",
								"padding-left" : "15px",
								"border-bottom-style" : "none",
								"border-top-style" : "none",
								"text-align" : "left"
							});
							container.addChild(output_70, {
								"colIndex": 0,
								"rowIndex": 1
							});
						})(group_35);
						container.addChild(group_35, {
							"autoSize": "height",
							"width": "1220px",
							"height": "80px"
						});
						var group_36 = new cpr.controls.Container();
						group_36.style.setClasses(["attach-box"]);
						group_36.style.css({
							"border-right-style" : "solid",
							"border-top-width" : "1px",
							"border-bottom-color" : "#babfc7",
							"border-right-width" : "1px",
							"border-left-color" : "#babfc7",
							"border-right-color" : "#babfc7",
							"border-left-width" : "1px",
							"border-top-style" : "solid",
							"background-color" : "#e9e9e9",
							"border-left-style" : "solid",
							"border-bottom-width" : "1px",
							"border-top-color" : "#babfc7",
							"border-bottom-style" : "solid",
							"background-image" : "none"
						});
						// Layout
						var flowLayout_6 = new cpr.controls.layouts.FlowLayout();
						flowLayout_6.scrollable = false;
						flowLayout_6.horizontalSpacing = 20;
						flowLayout_6.verticalSpacing = 20;
						flowLayout_6.horizontalAlign = "center";
						flowLayout_6.verticalAlign = "middle";
						flowLayout_6.leftMargin = 20;
						flowLayout_6.rightMargin = 20;
						flowLayout_6.topMargin = 20;
						flowLayout_6.bottomMargin = 20;
						group_36.setLayout(flowLayout_6);
						(function(container){
							var group_37 = new cpr.controls.Container();
							// Layout
							var formLayout_17 = new cpr.controls.layouts.FormLayout();
							formLayout_17.topMargin = "0px";
							formLayout_17.rightMargin = "0px";
							formLayout_17.bottomMargin = "0px";
							formLayout_17.leftMargin = "0px";
							formLayout_17.horizontalSpacing = "5px";
							formLayout_17.verticalSpacing = "5px";
							formLayout_17.setColumns(["1fr"]);
							formLayout_17.setRows(["1fr", "20px"]);
							group_37.setLayout(formLayout_17);
							(function(container){
								var output_71 = new cpr.controls.Output();
								output_71.value = "<기능 확인 컨트롤>";
								output_71.style.setClasses(["text-center"]);
								container.addChild(output_71, {
									"colIndex": 0,
									"rowIndex": 1
								});
								var slider_6 = new cpr.controls.Slider("sampleSld5");
								slider_6.value = "30";
								if(typeof onSampleSld5ValueChange == "function") {
									slider_6.addEventListener("value-change", onSampleSld5ValueChange);
								}
								container.addChild(slider_6, {
									"colIndex": 0,
									"rowIndex": 0
								});
							})(group_37);
							container.addChild(group_37, {
								"autoSize": "none",
								"width": "300px",
								"height": "50px"
							});
							var group_38 = new cpr.controls.Container();
							// Layout
							var formLayout_18 = new cpr.controls.layouts.FormLayout();
							formLayout_18.topMargin = "0px";
							formLayout_18.rightMargin = "0px";
							formLayout_18.bottomMargin = "0px";
							formLayout_18.leftMargin = "0px";
							formLayout_18.horizontalSpacing = "5px";
							formLayout_18.verticalSpacing = "5px";
							formLayout_18.setColumns(["1fr"]);
							formLayout_18.setRows(["1fr", "20px"]);
							group_38.setLayout(formLayout_18);
							(function(container){
								var output_72 = new cpr.controls.Output();
								output_72.value = "<step 값 확인 아웃풋>";
								output_72.style.setClasses(["text-center"]);
								container.addChild(output_72, {
									"colIndex": 0,
									"rowIndex": 1
								});
								var output_73 = new cpr.controls.Output("optRslt");
								output_73.value = "step 이동값 : ";
								output_73.style.css({
									"text-align" : "center"
								});
								container.addChild(output_73, {
									"colIndex": 0,
									"rowIndex": 0
								});
							})(group_38);
							container.addChild(group_38, {
								"autoSize": "none",
								"width": "300px",
								"height": "50px"
							});
						})(group_36);
						container.addChild(group_36, {
							"autoSize": "height",
							"width": "1220px",
							"height": "337px"
						});
					})(group_32);
					container.addChild(group_32, {
						"autoSize": "height",
						"width": "1220px",
						"height": "780px"
					});
					var group_39 = new cpr.controls.Container();
					group_39.style.setClasses(["card-inner"]);
					// Layout
					var verticalLayout_16 = new cpr.controls.layouts.VerticalLayout();
					verticalLayout_16.spacing = 15;
					verticalLayout_16.leftMargin = 40;
					verticalLayout_16.rightMargin = 40;
					verticalLayout_16.topMargin = 20;
					verticalLayout_16.bottomMargin = 40;
					group_39.setLayout(verticalLayout_16);
					(function(container){
						var output_74 = new cpr.controls.Output();
						output_74.value = "max";
						output_74.style.css({
							"color" : "#2263b3",
							"font-weight" : "700",
							"font-size" : "20px",
							"font-family" : "sans-serif , 'Malgun Gothic' , 'Noto Sans KR'"
						});
						container.addChild(output_74, {
							"autoSize": "none",
							"width": "1220px",
							"height": "38px"
						});
						var group_40 = new cpr.controls.Container();
						group_40.style.css({
							"background-color" : "#e9eff7",
							"background-image" : "none"
						});
						// Layout
						var verticalLayout_17 = new cpr.controls.layouts.VerticalLayout();
						verticalLayout_17.leftMargin = 30;
						verticalLayout_17.rightMargin = 30;
						verticalLayout_17.topMargin = 20;
						verticalLayout_17.bottomMargin = 20;
						group_40.setLayout(verticalLayout_17);
						(function(container){
							var output_75 = new cpr.controls.Output();
							output_75.value = "슬라이더의 최댓값을 설정하는 속성입니다.";
							output_75.style.setClasses(["opt-tmpl"]);
							output_75.style.css({
								"font-weight" : "700"
							});
							container.addChild(output_75, {
								"autoSize": "height",
								"width": "100px",
								"height": "40px"
							});
						})(group_40);
						container.addChild(group_40, {
							"autoSize": "height",
							"width": "1140px",
							"height": "80px"
						});
						var output_76 = new cpr.controls.Output();
						output_76.value = "min";
						output_76.style.css({
							"color" : "#2263b3",
							"font-weight" : "700",
							"font-size" : "20px",
							"font-family" : "sans-serif , 'Malgun Gothic' , 'Noto Sans KR'"
						});
						container.addChild(output_76, {
							"autoSize": "none",
							"width": "1140px",
							"height": "38px"
						});
						var group_41 = new cpr.controls.Container();
						group_41.style.css({
							"background-color" : "#e9eff7",
							"background-image" : "none"
						});
						// Layout
						var verticalLayout_18 = new cpr.controls.layouts.VerticalLayout();
						verticalLayout_18.leftMargin = 30;
						verticalLayout_18.rightMargin = 30;
						verticalLayout_18.topMargin = 20;
						verticalLayout_18.bottomMargin = 20;
						group_41.setLayout(verticalLayout_18);
						(function(container){
							var output_77 = new cpr.controls.Output();
							output_77.value = "슬라이더의 최솟값을 설정하는 속성입니다.";
							output_77.style.setClasses(["opt-tmpl"]);
							output_77.style.css({
								"font-weight" : "700"
							});
							container.addChild(output_77, {
								"autoSize": "height",
								"width": "100px",
								"height": "40px"
							});
						})(group_41);
						container.addChild(group_41, {
							"autoSize": "height",
							"width": "1140px",
							"height": "80px"
						});
						var group_42 = new cpr.controls.Container();
						group_42.style.setClasses(["form-box", "vertical"]);
						// Layout
						var formLayout_19 = new cpr.controls.layouts.FormLayout();
						formLayout_19.topMargin = "5px";
						formLayout_19.rightMargin = "5px";
						formLayout_19.bottomMargin = "5px";
						formLayout_19.leftMargin = "5px";
						formLayout_19.horizontalSpacing = "10px";
						formLayout_19.verticalSpacing = "10px";
						formLayout_19.horizontalSeparatorWidth = 1;
						formLayout_19.verticalSeparatorWidth = 1;
						formLayout_19.setColumns(["1fr", "200px", "80px"]);
						formLayout_19.setRows(["30px", "30px"]);
						formLayout_19.setCustomRowShade(0, "#edeff6");
						formLayout_19.setRowAutoSizing(1, true);
						group_42.setLayout(formLayout_19);
						(function(container){
							var output_78 = new cpr.controls.Output();
							output_78.value = "시나리오";
							output_78.style.setClasses(["label"]);
							output_78.style.css({
								"border-right-style" : "none",
								"background-color" : "transparent",
								"border-left-style" : "none",
								"padding-left" : "15px",
								"border-bottom-style" : "none",
								"border-top-style" : "none",
								"text-align" : "left"
							});
							container.addChild(output_78, {
								"colIndex": 0,
								"rowIndex": 0
							});
							var output_79 = new cpr.controls.Output();
							output_79.value = "입력값";
							output_79.style.setClasses(["label"]);
							output_79.style.css({
								"border-right-style" : "none",
								"background-color" : "transparent",
								"border-left-style" : "none",
								"border-bottom-style" : "none",
								"border-top-style" : "none",
								"text-align" : "center"
							});
							container.addChild(output_79, {
								"colIndex": 1,
								"rowIndex": 0
							});
							var output_80 = new cpr.controls.Output();
							output_80.value = "기능확인";
							output_80.style.setClasses(["label"]);
							output_80.style.css({
								"border-right-style" : "none",
								"background-color" : "transparent",
								"border-left-style" : "none",
								"border-bottom-style" : "none",
								"border-top-style" : "none",
								"text-align" : "center"
							});
							container.addChild(output_80, {
								"colIndex": 2,
								"rowIndex": 0
							});
							var button_6 = new cpr.controls.Button("btnInit6");
							button_6.value = "실행";
							button_6.style.setClasses(["btn-primary"]);
							container.addChild(button_6, {
								"colIndex": 2,
								"rowIndex": 1,
								"verticalAlign": "center",
								"height": 30
							});
							var output_81 = new cpr.controls.Output();
							output_81.value = "1) 하단의 컨트롤에서 우측의 입력값이 적용된 컨트롤을 확인할 수 있습니다.\r\n2) 슬라이더의 최솟값이 20, 최댓값이 80인 것을 확인할 수 있습니다.\r\n* 슬라이더는 양옆으로 끝까지 이동 가능합니다.";
							output_81.style.setClasses(["opt-tmpl"]);
							output_81.style.css({
								"background-color" : "transparent",
								"border-right-style" : "none",
								"border-left-style" : "none",
								"padding-left" : "15px",
								"border-bottom-style" : "none",
								"border-top-style" : "none",
								"text-align" : "left"
							});
							container.addChild(output_81, {
								"colIndex": 0,
								"rowIndex": 1
							});
							var output_82 = new cpr.controls.Output();
							output_82.value = "min = 20.0\r\nmax = 80.0";
							output_82.style.setClasses(["opt-tmpl"]);
							output_82.style.css({
								"background-color" : "transparent",
								"border-right-style" : "none",
								"border-left-style" : "none",
								"padding-left" : "15px",
								"border-bottom-style" : "none",
								"border-top-style" : "none",
								"text-align" : "left"
							});
							container.addChild(output_82, {
								"colIndex": 1,
								"rowIndex": 1
							});
						})(group_42);
						container.addChild(group_42, {
							"autoSize": "height",
							"width": "1220px",
							"height": "80px"
						});
						var group_43 = new cpr.controls.Container();
						group_43.style.setClasses(["attach-box"]);
						group_43.style.css({
							"border-right-style" : "solid",
							"border-top-width" : "1px",
							"border-bottom-color" : "#babfc7",
							"border-right-width" : "1px",
							"border-left-color" : "#babfc7",
							"border-right-color" : "#babfc7",
							"border-left-width" : "1px",
							"border-top-style" : "solid",
							"background-color" : "#e9e9e9",
							"border-left-style" : "solid",
							"border-bottom-width" : "1px",
							"border-top-color" : "#babfc7",
							"border-bottom-style" : "solid",
							"background-image" : "none"
						});
						// Layout
						var flowLayout_7 = new cpr.controls.layouts.FlowLayout();
						flowLayout_7.scrollable = false;
						flowLayout_7.horizontalSpacing = 20;
						flowLayout_7.verticalSpacing = 20;
						flowLayout_7.horizontalAlign = "center";
						flowLayout_7.verticalAlign = "middle";
						flowLayout_7.leftMargin = 20;
						flowLayout_7.rightMargin = 20;
						flowLayout_7.topMargin = 20;
						flowLayout_7.bottomMargin = 20;
						group_43.setLayout(flowLayout_7);
						(function(container){
							var group_44 = new cpr.controls.Container();
							// Layout
							var formLayout_20 = new cpr.controls.layouts.FormLayout();
							formLayout_20.topMargin = "0px";
							formLayout_20.rightMargin = "0px";
							formLayout_20.bottomMargin = "0px";
							formLayout_20.leftMargin = "0px";
							formLayout_20.horizontalSpacing = "5px";
							formLayout_20.verticalSpacing = "5px";
							formLayout_20.setColumns(["1fr"]);
							formLayout_20.setRows(["1fr", "20px"]);
							group_44.setLayout(formLayout_20);
							(function(container){
								var output_83 = new cpr.controls.Output();
								output_83.value = "<기능 확인 컨트롤>";
								output_83.style.setClasses(["text-center"]);
								container.addChild(output_83, {
									"colIndex": 0,
									"rowIndex": 1
								});
								var slider_7 = new cpr.controls.Slider("sampleSld6");
								slider_7.value = "30";
								slider_7.min = 20.0;
								slider_7.max = 80.0;
								container.addChild(slider_7, {
									"colIndex": 0,
									"rowIndex": 0
								});
							})(group_44);
							container.addChild(group_44, {
								"autoSize": "none",
								"width": "260px",
								"height": "50px"
							});
						})(group_43);
						container.addChild(group_43, {
							"autoSize": "height",
							"width": "1220px",
							"height": "337px"
						});
					})(group_39);
					container.addChild(group_39, {
						"autoSize": "height",
						"width": "1220px",
						"height": "780px"
					});
				})(group_7);
				container.addChild(group_7, {
					"autoSize": "height",
					"width": "1100px",
					"height": "5500px"
				});
			})(group_2);
			container.addChild(group_2, {
				"autoSize": "height",
				"width": "400px",
				"height": "6300px"
			});
		}
	});
	app.title = "슬라이더 관련 속성";
	cpr.core.Platform.INSTANCE.register(app);
})();
