/*
 * App URI: app/exam/controls/UIControlShell
 * Source Location: app/exam/controls/UIControlShell.clx
 *
 * This file was generated by eXbuilder6 compiler, Don't edit manually.
 */
(function(){
	var app = new cpr.core.App("app/exam/controls/UIControlShell", {
		onPrepare: function(loader){
			loader.addScript("thirdparty/echarts/echarts.min.js");
		},
		onCreate: function(/* cpr.core.AppInstance */ app, exports){
			var linker = {};
			// Start - User Script
			/************************************************
			 * UIControlShell2.js
			 * Created at 2022. 3. 11. 오전 9:09:21.
			 *
			 * @author aaajd
			 ************************************************/
			
			/*
			 * 쉘에서 load 이벤트 발생 시 호출.
			 */
			function onShl1Load(e){
				var shl1 = e.control;
				
				var input = document.createElement("input");
				input.value = Math.round(Math.random() * 100);
				e.content.appendChild(input);
			}
			
			/*
			 * 쉘에서 load 이벤트 발생 시 호출.
			 */
			function onShl2Load(e){
				var shl2 = e.control;
				var shellDiv = e.content
				var myChart = echarts.init(shellDiv);
				myChart.resize();
				var option = {
					title : {
						text : 'ECharts 연동 예제'
					},
					tooltip : {},
					legend : {
						data : [ 'Sales' , 'Marketing', "R&D"]
					},
					xAxis : {
						data : [ "shirt", "cardign", "chiffon shirt", "pants", "heels", "socks" ]
					},
					yAxis : {},
					series : [ {
						name : 'Sales',
						type : 'bar',
						data : [ 5, 20, 36, 10, 10, 20 ]
					},
					{
						name : 'Marketing',
						type : 'line',
						data : [ 15, 25, 20, 25, 24, 40 ]
					},
					{
						name : 'R&D',
						type : 'bar',
						data : [ 15, 20, 35, 33, 40, 35 ]
					}]
				};
				myChart.setOption(option);
			}
			
			/*
			 * 쉘에서 init 이벤트 발생 시 호출.
			 */
			function onShl2Init(e){
				var shl2 = e.control;
				if(e.content) {
					e.preventDefault();
				}
			};
			// End - User Script
			
			// Header
			
			app.supportMedia("all and (min-width: 1320px)", "eXFrame");
			app.supportMedia("all and (min-width: 1020px) and (max-width: 1319px)", "default");
			app.supportMedia("all and (min-width: 760px) and (max-width: 1019px)", "tablet");
			app.supportMedia("all and (max-width: 759px)", "mobile");
			
			// Configure root container
			var container = app.getContainer();
			container.style.css({
				"width" : "100%",
				"height" : "100%"
			});
			
			// Layout
			var verticalLayout_1 = new cpr.controls.layouts.VerticalLayout();
			container.setLayout(verticalLayout_1);
			
			// UI Configuration
			var group_1 = new cpr.controls.Container("grpHeader");
			// Layout
			var verticalLayout_2 = new cpr.controls.layouts.VerticalLayout();
			verticalLayout_2.spacing = 0;
			group_1.setLayout(verticalLayout_2);
			(function(container){
				var userDefinedControl_1 = new udc.com.appHeader("appheader1");
				userDefinedControl_1.initializeYn = "N";
				userDefinedControl_1.searchBoxId = "grpHeader";
				container.addChild(userDefinedControl_1, {
					"width": "500px",
					"height": "30px"
				});
			})(group_1);
			container.addChild(group_1, {
				"autoSize": "height",
				"width": "400px",
				"height": "30px"
			});
			
			var group_2 = new cpr.controls.Container("grpData");
			// Layout
			var verticalLayout_3 = new cpr.controls.layouts.VerticalLayout();
			verticalLayout_3.spacing = 20;
			verticalLayout_3.leftMargin = 50;
			verticalLayout_3.rightMargin = 50;
			verticalLayout_3.topMargin = 20;
			verticalLayout_3.bottomMargin = 60;
			group_2.setLayout(verticalLayout_3);
			(function(container){
				var group_3 = new cpr.controls.Container();
				// Layout
				var verticalLayout_4 = new cpr.controls.layouts.VerticalLayout();
				verticalLayout_4.spacing = 30;
				verticalLayout_4.leftMargin = 0;
				verticalLayout_4.rightMargin = 0;
				verticalLayout_4.topMargin = 20;
				verticalLayout_4.bottomMargin = 40;
				group_3.setLayout(verticalLayout_4);
				(function(container){
					var output_1 = new cpr.controls.Output();
					output_1.value = "쉘";
					output_1.style.css({
						"font-weight" : "700",
						"font-size" : "2.5rem",
						"font-family" : "sans-serif , 'Malgun Gothic' , 'Noto Sans KR'"
					});
					container.addChild(output_1, {
						"autoSize": "height",
						"width": "100px",
						"height": "45px"
					});
					var output_2 = new cpr.controls.Output();
					output_2.value = "Third-party widget을 끼워 넣을 수 있는 컨트롤입니다.\r\n\r\n쉘은 사용자 라이브러리를 등록하여 사용하는 컨트롤입니다. 사용자 라이브러리는 쉘에서 컴포넌트로 활용할 수 있습니다. ";
					container.addChild(output_2, {
						"autoSize": "height",
						"width": "100px",
						"height": "150px"
					});
					var group_4 = new cpr.controls.Container();
					group_4.style.setClasses(["attach-box"]);
					group_4.style.css({
						"border-right-style" : "solid",
						"border-top-width" : "1px",
						"border-bottom-color" : "#babfc7",
						"border-right-width" : "1px",
						"border-left-color" : "#babfc7",
						"border-right-color" : "#babfc7",
						"border-left-width" : "1px",
						"border-top-style" : "solid",
						"background-color" : "#e9e9e9",
						"border-left-style" : "solid",
						"border-bottom-width" : "1px",
						"border-top-color" : "#babfc7",
						"border-bottom-style" : "solid"
					});
					// Layout
					var flowLayout_1 = new cpr.controls.layouts.FlowLayout();
					flowLayout_1.scrollable = false;
					flowLayout_1.horizontalSpacing = 40;
					flowLayout_1.verticalSpacing = 20;
					flowLayout_1.horizontalAlign = "center";
					flowLayout_1.verticalAlign = "middle";
					flowLayout_1.leftMargin = 20;
					flowLayout_1.rightMargin = 20;
					flowLayout_1.topMargin = 20;
					flowLayout_1.bottomMargin = 20;
					group_4.setLayout(flowLayout_1);
					(function(container){
						var group_5 = new cpr.controls.Container("grp1");
						// Layout
						var formLayout_1 = new cpr.controls.layouts.FormLayout();
						formLayout_1.scrollable = true;
						formLayout_1.topMargin = "0px";
						formLayout_1.rightMargin = "0px";
						formLayout_1.bottomMargin = "0px";
						formLayout_1.leftMargin = "0px";
						formLayout_1.horizontalSpacing = "5px";
						formLayout_1.verticalSpacing = "5px";
						formLayout_1.setColumns(["1fr"]);
						formLayout_1.setRows(["1fr", "20px", "20px"]);
						group_5.setLayout(formLayout_1);
						(function(container){
							var output_3 = new cpr.controls.Output();
							output_3.value = "<컨트롤 동적 생성 코드>";
							output_3.style.setClasses(["text-center"]);
							container.addChild(output_3, {
								"colIndex": 0,
								"rowIndex": 1
							});
							var userDefinedControl_2 = new udc.tmp.Ace("ace2");
							userDefinedControl_2.value = "var uIControlShell_1 = new cpr.controls.UIControlShell(\"shlCdMr\");";
							container.addChild(userDefinedControl_2, {
								"colIndex": 0,
								"rowIndex": 0
							});
							var output_4 = new cpr.controls.Output();
							output_4.value = "<codemirror라는 thirdparty 라이브러리를 사용한 쉘 컨트롤>";
							output_4.style.setClasses(["text-center"]);
							container.addChild(output_4, {
								"colIndex": 0,
								"rowIndex": 2
							});
						})(group_5);
						container.addChild(group_5, {
							"autoSize": "both",
							"width": "450px",
							"height": "300px"
						});
					})(group_4);
					container.addChild(group_4, {
						"autoSize": "height",
						"width": "1220px",
						"height": "381px"
					});
				})(group_3);
				container.addChild(group_3, {
					"autoSize": "height",
					"width": "400px",
					"height": "700px"
				});
				var group_6 = new cpr.controls.Container();
				group_6.style.setClasses(["card-inner"]);
				// Layout
				var verticalLayout_5 = new cpr.controls.layouts.VerticalLayout();
				verticalLayout_5.spacing = 30;
				verticalLayout_5.leftMargin = 0;
				verticalLayout_5.rightMargin = 0;
				verticalLayout_5.topMargin = 20;
				verticalLayout_5.bottomMargin = 40;
				group_6.setLayout(verticalLayout_5);
				(function(container){
					var output_5 = new cpr.controls.Output();
					output_5.value = "자주 사용되는 속성";
					output_5.style.setClasses(["h1", "pl-3", "bg-primary", "text-white"]);
					output_5.style.css({
						"font-weight" : "700",
						"font-size" : "26px",
						"font-family" : "sans-serif , 'Malgun Gothic' , 'Noto Sans KR'"
					});
					container.addChild(output_5, {
						"autoSize": "none",
						"width": "1220px",
						"height": "38px"
					});
					var output_6 = new cpr.controls.Output();
					output_6.value = "자주 사용되는 속성과 시나리오를 통한 예제를 확인할 수 있습니다. 자세한 사항은 Help Contents를 참조하시기 바랍니다.";
					container.addChild(output_6, {
						"autoSize": "height",
						"width": "100px",
						"height": "141px"
					});
					var group_7 = new cpr.controls.Container();
					group_7.style.setClasses(["card-inner"]);
					// Layout
					var verticalLayout_6 = new cpr.controls.layouts.VerticalLayout();
					verticalLayout_6.spacing = 25;
					verticalLayout_6.leftMargin = 40;
					verticalLayout_6.rightMargin = 40;
					verticalLayout_6.topMargin = 20;
					verticalLayout_6.bottomMargin = 40;
					group_7.setLayout(verticalLayout_6);
					(function(container){
						var output_7 = new cpr.controls.Output();
						output_7.value = "쉘에 인풋박스 삽입";
						output_7.style.css({
							"color" : "#2263b3",
							"font-weight" : "700",
							"font-size" : "20px",
							"font-family" : "sans-serif , 'Malgun Gothic' , 'Noto Sans KR'"
						});
						container.addChild(output_7, {
							"autoSize": "none",
							"width": "1220px",
							"height": "38px"
						});
						var group_8 = new cpr.controls.Container();
						group_8.style.css({
							"background-color" : "#e9eff7",
							"background-image" : "none"
						});
						// Layout
						var verticalLayout_7 = new cpr.controls.layouts.VerticalLayout();
						verticalLayout_7.leftMargin = 30;
						verticalLayout_7.rightMargin = 30;
						verticalLayout_7.topMargin = 20;
						verticalLayout_7.bottomMargin = 20;
						group_8.setLayout(verticalLayout_7);
						(function(container){
							var output_8 = new cpr.controls.Output();
							output_8.value = "쉘 컨트롤에 일반 컨트롤을 삽입하여 사용할 수 있습니다.";
							output_8.style.css({
								"font-weight" : "700"
							});
							container.addChild(output_8, {
								"autoSize": "height",
								"width": "100px",
								"height": "40px"
							});
						})(group_8);
						container.addChild(group_8, {
							"autoSize": "height",
							"width": "1140px",
							"height": "80px"
						});
						var group_9 = new cpr.controls.Container();
						group_9.style.setClasses(["attach-box"]);
						group_9.style.css({
							"border-right-style" : "solid",
							"border-top-width" : "1px",
							"border-bottom-color" : "#babfc7",
							"border-right-width" : "1px",
							"border-left-color" : "#babfc7",
							"border-right-color" : "#babfc7",
							"border-left-width" : "1px",
							"border-top-style" : "solid",
							"background-color" : "#e9e9e9",
							"border-left-style" : "solid",
							"border-bottom-width" : "1px",
							"border-top-color" : "#babfc7",
							"border-bottom-style" : "solid",
							"background-image" : "none"
						});
						// Layout
						var flowLayout_2 = new cpr.controls.layouts.FlowLayout();
						flowLayout_2.scrollable = false;
						flowLayout_2.horizontalSpacing = 20;
						flowLayout_2.verticalSpacing = 20;
						flowLayout_2.horizontalAlign = "center";
						flowLayout_2.verticalAlign = "middle";
						flowLayout_2.leftMargin = 20;
						flowLayout_2.rightMargin = 20;
						flowLayout_2.topMargin = 20;
						flowLayout_2.bottomMargin = 20;
						group_9.setLayout(flowLayout_2);
						(function(container){
							var group_10 = new cpr.controls.Container();
							// Layout
							var formLayout_2 = new cpr.controls.layouts.FormLayout();
							formLayout_2.topMargin = "0px";
							formLayout_2.rightMargin = "0px";
							formLayout_2.bottomMargin = "0px";
							formLayout_2.leftMargin = "0px";
							formLayout_2.horizontalSpacing = "5px";
							formLayout_2.verticalSpacing = "5px";
							formLayout_2.setColumns(["1fr"]);
							formLayout_2.setRows(["1fr", "20px"]);
							group_10.setLayout(formLayout_2);
							(function(container){
								var output_9 = new cpr.controls.Output();
								output_9.value = "<기능 확인 컨트롤>";
								output_9.style.setClasses(["text-center"]);
								container.addChild(output_9, {
									"colIndex": 0,
									"rowIndex": 1
								});
								var uIControlShell_1 = new cpr.controls.UIControlShell("shl1");
								if(typeof onShl1Load == "function") {
									uIControlShell_1.addEventListener("load", onShl1Load);
								}
								container.addChild(uIControlShell_1, {
									"colIndex": 0,
									"rowIndex": 0
								});
							})(group_10);
							container.addChild(group_10, {
								"autoSize": "both",
								"width": "200px",
								"height": "50px"
							});
							var group_11 = new cpr.controls.Container("grp2");
							// Layout
							var formLayout_3 = new cpr.controls.layouts.FormLayout();
							formLayout_3.scrollable = true;
							formLayout_3.topMargin = "0px";
							formLayout_3.rightMargin = "0px";
							formLayout_3.bottomMargin = "0px";
							formLayout_3.leftMargin = "0px";
							formLayout_3.horizontalSpacing = "5px";
							formLayout_3.verticalSpacing = "5px";
							formLayout_3.setColumns(["1fr"]);
							formLayout_3.setRows(["1fr", "20px"]);
							group_11.setLayout(formLayout_3);
							(function(container){
								var output_10 = new cpr.controls.Output();
								output_10.value = "<쉘 컨트롤에 인풋박스 삽입 코드>";
								output_10.style.setClasses(["text-center"]);
								container.addChild(output_10, {
									"colIndex": 0,
									"rowIndex": 1
								});
								var userDefinedControl_3 = new udc.tmp.Ace("ace3");
								userDefinedControl_3.value = "var input = document.createElement(\"input\");\r\ninput.value = Math.round(Math.random() * 100);\r\ne.content.appendChild(input);";
								container.addChild(userDefinedControl_3, {
									"colIndex": 0,
									"rowIndex": 0
								});
							})(group_11);
							container.addChild(group_11, {
								"autoSize": "both",
								"width": "450px",
								"height": "300px"
							});
						})(group_9);
						container.addChild(group_9, {
							"autoSize": "height",
							"width": "1220px",
							"height": "337px"
						});
					})(group_7);
					container.addChild(group_7, {
						"autoSize": "height",
						"width": "1220px",
						"height": "780px"
					});
					var group_12 = new cpr.controls.Container();
					group_12.style.setClasses(["card-inner"]);
					// Layout
					var verticalLayout_8 = new cpr.controls.layouts.VerticalLayout();
					verticalLayout_8.spacing = 15;
					verticalLayout_8.leftMargin = 40;
					verticalLayout_8.rightMargin = 40;
					verticalLayout_8.topMargin = 20;
					verticalLayout_8.bottomMargin = 40;
					group_12.setLayout(verticalLayout_8);
					(function(container){
						var output_11 = new cpr.controls.Output();
						output_11.value = "쉘에 Echart 라이브러리 삽입";
						output_11.style.css({
							"color" : "#2263b3",
							"font-weight" : "700",
							"font-size" : "20px",
							"font-family" : "sans-serif , 'Malgun Gothic' , 'Noto Sans KR'"
						});
						container.addChild(output_11, {
							"autoSize": "none",
							"width": "1220px",
							"height": "38px"
						});
						var group_13 = new cpr.controls.Container("grp5");
						group_13.style.css({
							"background-color" : "#e9eff7",
							"background-image" : "none"
						});
						// Layout
						var verticalLayout_9 = new cpr.controls.layouts.VerticalLayout();
						verticalLayout_9.leftMargin = 30;
						verticalLayout_9.rightMargin = 30;
						verticalLayout_9.topMargin = 20;
						verticalLayout_9.bottomMargin = 20;
						group_13.setLayout(verticalLayout_9);
						(function(container){
							var output_12 = new cpr.controls.Output();
							output_12.value = "Echart라는 third-party 라이브러리를 쉘에 구현한 화면입니다.";
							output_12.style.css({
								"font-weight" : "700"
							});
							container.addChild(output_12, {
								"autoSize": "height",
								"width": "100px",
								"height": "40px"
							});
						})(group_13);
						container.addChild(group_13, {
							"autoSize": "height",
							"width": "1140px",
							"height": "80px"
						});
						var group_14 = new cpr.controls.Container();
						group_14.style.setClasses(["attach-box"]);
						group_14.style.css({
							"border-right-style" : "solid",
							"border-top-width" : "1px",
							"border-bottom-color" : "#babfc7",
							"border-right-width" : "1px",
							"border-left-color" : "#babfc7",
							"border-right-color" : "#babfc7",
							"border-left-width" : "1px",
							"border-top-style" : "solid",
							"background-color" : "#e9e9e9",
							"border-left-style" : "solid",
							"border-bottom-width" : "1px",
							"border-top-color" : "#babfc7",
							"border-bottom-style" : "solid",
							"background-image" : "none"
						});
						// Layout
						var verticalLayout_10 = new cpr.controls.layouts.VerticalLayout();
						group_14.setLayout(verticalLayout_10);
						(function(container){
							var group_15 = new cpr.controls.Container("grp4");
							// Layout
							var formLayout_4 = new cpr.controls.layouts.FormLayout();
							formLayout_4.topMargin = "0px";
							formLayout_4.rightMargin = "0px";
							formLayout_4.bottomMargin = "0px";
							formLayout_4.leftMargin = "0px";
							formLayout_4.horizontalSpacing = "5px";
							formLayout_4.verticalSpacing = "5px";
							formLayout_4.setColumns(["1fr"]);
							formLayout_4.setRows(["1fr", "20px"]);
							group_15.setLayout(formLayout_4);
							(function(container){
								var output_13 = new cpr.controls.Output();
								output_13.value = "<기능 확인 컨트롤>";
								output_13.style.setClasses(["text-center"]);
								container.addChild(output_13, {
									"colIndex": 0,
									"rowIndex": 1
								});
								var uIControlShell_2 = new cpr.controls.UIControlShell("shl2");
								if(typeof onShl2Load == "function") {
									uIControlShell_2.addEventListener("load", onShl2Load);
								}
								if(typeof onShl2Init == "function") {
									uIControlShell_2.addEventListener("init", onShl2Init);
								}
								container.addChild(uIControlShell_2, {
									"colIndex": 0,
									"rowIndex": 0
								});
							})(group_15);
							container.addChild(group_15, {
								"width": "200px",
								"height": "300px"
							});
							var group_16 = new cpr.controls.Container("grp3");
							// Layout
							var formLayout_5 = new cpr.controls.layouts.FormLayout();
							formLayout_5.scrollable = true;
							formLayout_5.topMargin = "0px";
							formLayout_5.rightMargin = "0px";
							formLayout_5.bottomMargin = "0px";
							formLayout_5.leftMargin = "0px";
							formLayout_5.horizontalSpacing = "5px";
							formLayout_5.verticalSpacing = "5px";
							formLayout_5.setColumns(["1fr"]);
							formLayout_5.setRows(["1fr", "20px"]);
							group_16.setLayout(formLayout_5);
							(function(container){
								var output_14 = new cpr.controls.Output();
								output_14.value = "<쉘 컨트롤에 echart 서드파티 삽입 코드>";
								output_14.style.setClasses(["text-center"]);
								container.addChild(output_14, {
									"colIndex": 0,
									"rowIndex": 1
								});
								var userDefinedControl_4 = new udc.tmp.Ace("ace4");
								userDefinedControl_4.value = "var shellDiv = e.content\r\nvar myChart = echarts.init(shellDiv);\r\nmyChart.resize();\r\nvar option = {\r\n\ttitle : {\r\n\t\ttext : 'ECharts 연동 예제'\r\n\t},\r\n\ttooltip : {},\r\n\tlegend : {\r\n\t\tdata : [ 'Sales' , 'Marketing', \"R&D\"]\r\n\t},\r\n\txAxis : {\r\n\t\tdata : [ \"shirt\", \"cardign\", \"chiffon shirt\", \"pants\", \"heels\", \"socks\" ]\r\n\t},\r\n\tyAxis : {},\r\n\tseries : [ {\r\n\t\tname : 'Sales',\r\n\t\ttype : 'bar',\r\n\t\tdata : [ 5, 20, 36, 10, 10, 20 ]\r\n\t},\t\t\r\n\t{\r\n\t\tname : 'Marketing',\r\n\t\ttype : 'line',\r\n\t\tdata : [ 15, 25, 20, 25, 24, 40 ]\r\n\t},\r\n\t{\r\n\t\tname : 'R&D',\r\n\t\ttype : 'bar',\r\n\t\tdata : [ 15, 20, 35, 33, 40, 35 ]\r\n\t}]\r\n};\r\nmyChart.setOption(option);";
								container.addChild(userDefinedControl_4, {
									"colIndex": 0,
									"rowIndex": 0
								});
							})(group_16);
							container.addChild(group_16, {
								"autoSize": "height",
								"width": "450px",
								"height": "300px"
							});
						})(group_14);
						container.addChild(group_14, {
							"autoSize": "height",
							"width": "1220px",
							"height": "600px"
						});
					})(group_12);
					container.addChild(group_12, {
						"autoSize": "height",
						"width": "1220px",
						"height": "780px"
					});
				})(group_6);
				container.addChild(group_6, {
					"autoSize": "height",
					"width": "1100px",
					"height": "4400px"
				});
			})(group_2);
			container.addChild(group_2, {
				"autoSize": "height",
				"width": "400px",
				"height": "5200px"
			});
		}
	});
	app.title = "쉘 관련 속성";
	cpr.core.Platform.INSTANCE.register(app);
})();
