/*
 * App URI: app/exam/appSmpl/faq&qna/gridRowSwitch
 * Source Location: app/exam/appSmpl/faq&qna/gridRowSwitch.clx
 *
 * This file was generated by eXbuilder6 compiler, Don't edit manually.
 */
(function(){
	var app = new cpr.core.App("app/exam/appSmpl/faq&qna/gridRowSwitch", {
		onPrepare: function(loader){
		},
		onCreate: function(/* cpr.core.AppInstance */ app, exports){
			var linker = {};
			// Start - User Script
			/************************************************
			* gridRowSwitch.js
			 * Created at 2022. 3. 21. 오후 2:33:05.
			 *
			 * @author 1amthomas
			 ************************************************/
			
			
			//QnA나 FAQ 예제가 아닌 경우 삭제
			/*
			 * "https://techdom.tomatosystem.co.kr/p/00001" 버튼(btn5)에서 click 이벤트 발생 시 호출.
			 * 사용자가 컨트롤을 클릭할 때 발생하는 이벤트.
			 */
			function onBtn5Click2(e){
				//질의문자열 중 ps의 value 값에 해당 qna,faq 요청번호 입력
			    //ex) window.open('https://techdom.tomatosystem.co.kr/p/00019/?bn=eXBuilder6&tn=qna&ps=12461');
				var selOpt = app.lookup("selOpt").value;
				var selNum = app.lookup("selNum").value;
				var vsLink = "https://techdom.tomatosystem.co.kr/p/00019/?bn=eXBuilder6&tn="+selOpt+"&ps="+selNum;
				window.open(vsLink);
			}
			
			/*
			 * "실행" 버튼(btn3)에서 click 이벤트 발생 시 호출.
			 * 사용자가 컨트롤을 클릭할 때 발생하는 이벤트.
			 */
			function onBtn3Click(e){
				changeRow();
			}
			
			function changeRow() {
				var sampleGrd = app.lookup('sampleGrd');
				var dsList = app.lookup('dsList');
				
				//선택한 row 배열
				var voRows = sampleGrd.getSelectedRowIndices();
				
				if (voRows.length == 2) {
					//row끼리 위치 바꾸기
					dsList.changeRowIndex(voRows[0], voRows[1]);
					
					/* 에디터에 소스 표시 */
					var vcAceEditor = app.lookup("ace2");
					vcAceEditor.value = changeRow;
				} else {
					alert('그리드의 행을 2개 선택하세요.');
				}
				sampleGrd.redraw();
			}
			// End - User Script
			
			// Header
			var dataSet_1 = new cpr.data.DataSet("dsList");
			dataSet_1.parseData({
				"columns": [
					{"name": "empId"},
					{"name": "empNm"},
					{"name": "email"},
					{"name": "phone"},
					{"name": "address"},
					{"name": "rgstDt"}
				],
				"rows": [
					{"empId": "594-38-4655", "empNm": "Lane Considine", "email": "rbissell0@de.vu", "phone": "010-1886-6554", "address": "12 Burning Wood Avenue", "rgstDt": "20200920"},
					{"empId": "314-39-2150", "empNm": "Selma Fay", "email": "lairton1@amazon.de", "phone": "010-2043-2275", "address": "36 Darwin Avenue", "rgstDt": "20200912"},
					{"empId": "164-62-6156", "empNm": "Neal Zieme", "email": "mjindra2@so-net.ne.jp", "phone": "010-6299-8957", "address": "98 Drewry Junction", "rgstDt": "20200615"},
					{"empId": "484-19-2604", "empNm": "Meggan Auer", "email": "skennet3@dropbox.com", "phone": "010-3187-3090", "address": "9 Montana Terrace", "rgstDt": "20200312"},
					{"empId": "559-13-4942", "empNm": "Araceli Smith", "email": "dhocking4@t.co", "phone": "010-1622-5856", "address": "40863 Scofield Circle", "rgstDt": "20200128"},
					{"empId": "840-42-2888", "empNm": "Mickey Erdman", "email": "hcollins5@stanford.edu", "phone": "010-2768-3424", "address": "556 West Court", "rgstDt": "20200901"},
					{"empId": "144-26-0513", "empNm": "Rosalva Jerde", "email": "olettsom6@addtoany.com", "phone": "010-6745-6895", "address": "20858 Center Parkway", "rgstDt": "20200806"},
					{"empId": "450-28-5237", "empNm": "Teodoro Sanford", "email": "pclampett7@twitpic.com", "phone": "010-8681-1087", "address": "8 Oak Hill", "rgstDt": "20200430"},
					{"empId": "748-53-9610", "empNm": "Shaquana Murazik", "email": "sglaum8@moonfruit.com", "phone": "010-4246-2969", "address": "19885 4th Terrace", "rgstDt": "20191204"},
					{"empId": "437-25-7106", "empNm": "Cliff Green", "email": "mdrever9@adobe.com", "phone": "010-8757-3058", "address": "355 Hanover Hill", "rgstDt": "20200627"},
					{"empId": "203-62-7094", "empNm": "Roberto Padberg", "email": "csisslanda@bizjournals.com", "phone": "010-4603-1770", "address": "7 Texas Center", "rgstDt": "20200809"},
					{"empId": "560-52-8330", "empNm": "Danielle Fisher", "email": "ameadusb@columbia.edu", "phone": "010-7703-5098", "address": "88244 Gerald Point", "rgstDt": "20191215"},
					{"empId": "880-25-8413", "empNm": "Ambrose Senger", "email": "kbeelsc@ezinearticles.com", "phone": "010-0806-5101", "address": "09 Bobwhite Lane", "rgstDt": "20200911"},
					{"empId": "782-76-2048", "empNm": "Demarcus Brown", "email": "dblakeyd@51.la", "phone": "010-4239-8279", "address": "94917 Delladonna Drive", "rgstDt": "20200327"},
					{"empId": "883-93-1783", "empNm": "Johnathan Quigley", "email": "wpaule@networkadvertising.org", "phone": "010-5475-6965", "address": "95647 Erie Lane", "rgstDt": "20200223"},
					{"empId": "359-94-5504", "empNm": "Elias Leannon", "email": "jgilmourf@bandcamp.com", "phone": "010-6736-0761", "address": "21161 Stoughton Center", "rgstDt": "20200906"},
					{"empId": "873-47-4854", "empNm": "Brande Jast", "email": "mmowlamg@seattletimes.com", "phone": "010-4977-3504", "address": "476 Havey Road", "rgstDt": "20200709"},
					{"empId": "807-57-5913", "empNm": "Sebastian Walsh", "email": "gtrobeh@hibu.com", "phone": "010-4218-0433", "address": "85 Novick Pass", "rgstDt": "20200318"},
					{"empId": "702-08-3511", "empNm": "Hortensia Kuvalis", "email": "psnoadi@cnet.com", "phone": "010-7493-6305", "address": "18 Shoshone Street", "rgstDt": "20200321"},
					{"empId": "165-52-8840", "empNm": "Claris Mills", "email": "gswindonj@mlb.com", "phone": "010-1040-8459", "address": "7722 Warrior Plaza", "rgstDt": "20200528"},
					{"empId": "141-30-3913", "empNm": "Renna Labadie", "email": "agunnk@nbcnews.com", "phone": "010-0081-4172", "address": "5 Canary Pass", "rgstDt": "20200408"},
					{"empId": "131-64-7984", "empNm": "Janetta Gorczany", "email": "wkobierzyckil@springer.com", "phone": "010-4318-5862", "address": "171 Caliangt Point", "rgstDt": "20191128"},
					{"empId": "363-53-6686", "empNm": "Claude White", "email": "lsivillsm@shop-pro.jp", "phone": "010-6589-5906", "address": "612 Troy Center", "rgstDt": "20200509"},
					{"empId": "164-58-0443", "empNm": "Jaime Fay", "email": "wabrahamoffn@wikispaces.com", "phone": "010-6049-3853", "address": "47 Merchant Plaza", "rgstDt": "20200726"},
					{"empId": "833-09-3725", "empNm": "Yasmine Towne", "email": "wchallenoro@engadget.com", "phone": "010-6497-9056", "address": "61 Grasskamp Place", "rgstDt": "20201029"},
					{"empId": "253-63-2956", "empNm": "Raymundo Howe", "email": "kbarterp@mediafire.com", "phone": "010-4545-3584", "address": "941 Leroy Way", "rgstDt": "20200612"},
					{"empId": "726-08-0595", "empNm": "Russell Paucek", "email": "tnottleq@hatena.ne.jp", "phone": "010-9167-2117", "address": "0 Charing Cross Road", "rgstDt": "20201121"},
					{"empId": "879-74-5236", "empNm": "Wilfred Greenfelder", "email": "tlafayer@comcast.net", "phone": "010-4639-7552", "address": "14 Maryland Plaza", "rgstDt": "20191203"},
					{"empId": "837-27-0001", "empNm": "Jacinto Wilkinson", "email": "kwalass@ovh.net", "phone": "010-6138-0842", "address": "76123 Cordelia Terrace", "rgstDt": "20200204"}
				]
			});
			app.register(dataSet_1);
			
			app.supportMedia("all and (min-width: 1320px)", "eXFrame");
			app.supportMedia("all and (min-width: 1020px) and (max-width: 1319px)", "default");
			app.supportMedia("all and (min-width: 760px) and (max-width: 1019px)", "tablet");
			app.supportMedia("all and (max-width: 759px)", "mobile");
			
			// Configure root container
			var container = app.getContainer();
			container.style.css({
				"width" : "100%",
				"height" : "100%"
			});
			
			// Layout
			var verticalLayout_1 = new cpr.controls.layouts.VerticalLayout();
			container.setLayout(verticalLayout_1);
			
			// UI Configuration
			var group_1 = new cpr.controls.Container("grpHeader");
			// Layout
			var verticalLayout_2 = new cpr.controls.layouts.VerticalLayout();
			group_1.setLayout(verticalLayout_2);
			(function(container){
				var userDefinedControl_1 = new udc.com.appHeader("appheader1");
				container.addChild(userDefinedControl_1, {
					"width": "500px",
					"height": "30px"
				});
			})(group_1);
			container.addChild(group_1, {
				"autoSize": "height",
				"width": "1320px",
				"height": "30px"
			});
			
			var group_2 = new cpr.controls.Container();
			// Layout
			var verticalLayout_3 = new cpr.controls.layouts.VerticalLayout();
			verticalLayout_3.leftMargin = 20;
			verticalLayout_3.rightMargin = 30;
			verticalLayout_3.topMargin = 30;
			verticalLayout_3.bottomMargin = 30;
			group_2.setLayout(verticalLayout_3);
			(function(container){
				var group_3 = new cpr.controls.Container("grpTitle");
				// Layout
				var verticalLayout_4 = new cpr.controls.layouts.VerticalLayout();
				verticalLayout_4.spacing = 30;
				verticalLayout_4.topMargin = 20;
				verticalLayout_4.bottomMargin = 40;
				group_3.setLayout(verticalLayout_4);
				(function(container){
					var group_4 = new cpr.controls.Container();
					// Layout
					var formLayout_1 = new cpr.controls.layouts.FormLayout();
					formLayout_1.scrollable = false;
					formLayout_1.rightMargin = "50px";
					formLayout_1.horizontalSpacing = "5px";
					formLayout_1.verticalSpacing = "5px";
					formLayout_1.setColumns(["300px", "100px"]);
					formLayout_1.setColumnAutoSizing(0, true);
					formLayout_1.setColumnAutoSizing(1, true);
					formLayout_1.setRows(["1fr"]);
					group_4.setLayout(formLayout_1);
					(function(container){
						var output_1 = new cpr.controls.Output("optTitle");
						output_1.value = "그리드에서 2개의 row위치를 변경하는 방법";
						output_1.style.css({
							"font-weight" : "bold",
							"padding-left" : "1rem",
							"font-size" : "2.5rem"
						});
						container.addChild(output_1, {
							"colIndex": 0,
							"rowIndex": 0
						});
					})(group_4);
					container.addChild(group_4, {
						"autoSize": "height",
						"width": "1270px",
						"height": "40px"
					});
					var output_2 = new cpr.controls.Output("optSummary");
					output_2.value = "이 문서는 그리드 컨트롤에서 2개의 row 위치를 서로 바꾸는 방법에 대해서 설명합니다.";
					output_2.style.setClasses(["opt-tmpl"]);
					output_2.style.css({
						"padding-left" : "1rem",
						"font-size" : "1rem"
					});
					container.addChild(output_2, {
						"autoSize": "height",
						"width": "1210px",
						"height": "46px"
					});
				})(group_3);
				container.addChild(group_3, {
					"autoSize": "height",
					"width": "1270px",
					"height": "150px"
				});
				var group_5 = new cpr.controls.Container("scenarioGrp");
				// Layout
				var verticalLayout_5 = new cpr.controls.layouts.VerticalLayout();
				verticalLayout_5.spacing = 30;
				verticalLayout_5.topMargin = 10;
				verticalLayout_5.bottomMargin = 30;
				group_5.setLayout(verticalLayout_5);
				(function(container){
					var output_3 = new cpr.controls.Output();
					output_3.value = "시나리오";
					output_3.style.setClasses(["h1", "pl-3", "bg-primary", "text-white"]);
					output_3.style.css({
						"font-weight" : "bold",
						"padding-left" : "1rem",
						"font-size" : "1.75rem"
					});
					container.addChild(output_3, {
						"width": "100px",
						"height": "40px"
					});
					var output_4 = new cpr.controls.Output();
					output_4.value = "1. ctrl을 누른 상태로 행을 클릭하여 2개의 행을 선택합니다.\r\n2. 실행버튼을 클릭하여 행 위치가 바뀌는지 확인합니다.";
					output_4.style.setClasses(["opt-tmpl"]);
					output_4.style.css({
						"padding-left" : "1rem",
						"font-size" : "1rem"
					});
					container.addChild(output_4, {
						"autoSize": "height",
						"width": "1210px",
						"height": "107px"
					});
				})(group_5);
				container.addChild(group_5, {
					"autoSize": "height",
					"width": "1270px",
					"height": "370px"
				});
				var group_6 = new cpr.controls.Container("grpFunction");
				// Layout
				var verticalLayout_6 = new cpr.controls.layouts.VerticalLayout();
				group_6.setLayout(verticalLayout_6);
				(function(container){
					var group_7 = new cpr.controls.Container("grpFuncFloating");
					group_7.userAttr({"floating-header": "true"});
					// Layout
					var verticalLayout_7 = new cpr.controls.layouts.VerticalLayout();
					verticalLayout_7.bottomMargin = 30;
					group_7.setLayout(verticalLayout_7);
					(function(container){
						var output_5 = new cpr.controls.Output();
						output_5.value = "기능확인";
						output_5.style.setClasses(["h1", "pl-3", "bg-primary", "text-white"]);
						output_5.style.css({
							"font-weight" : "bold",
							"padding-left" : "1rem",
							"font-size" : "1.75rem"
						});
						container.addChild(output_5, {
							"autoSize": "none",
							"width": "1270px",
							"height": "40px"
						});
						var group_8 = new cpr.controls.Container();
						group_8.style.css({
							"border-right-style" : "solid",
							"border-top-width" : "1px",
							"border-bottom-color" : "#dedede",
							"border-right-width" : "1px",
							"border-left-color" : "#dedede",
							"border-right-color" : "#dedede",
							"border-left-width" : "1px",
							"border-top-style" : "solid",
							"background-color" : "#F0F0F0",
							"border-left-style" : "solid",
							"border-bottom-width" : "1px",
							"border-top-color" : "#dedede",
							"border-bottom-style" : "solid"
						});
						// Layout
						var verticalLayout_8 = new cpr.controls.layouts.VerticalLayout();
						verticalLayout_8.leftMargin = 30;
						verticalLayout_8.rightMargin = 30;
						verticalLayout_8.topMargin = 5;
						verticalLayout_8.bottomMargin = 10;
						group_8.setLayout(verticalLayout_8);
						(function(container){
							var group_9 = new cpr.controls.Container();
							// Layout
							var formLayout_2 = new cpr.controls.layouts.FormLayout();
							formLayout_2.topMargin = "0px";
							formLayout_2.rightMargin = "0px";
							formLayout_2.bottomMargin = "0px";
							formLayout_2.leftMargin = "0px";
							formLayout_2.horizontalSpacing = "5px";
							formLayout_2.verticalSpacing = "5px";
							formLayout_2.setColumns(["1fr"]);
							formLayout_2.setRows(["1fr", "20px"]);
							group_9.setLayout(formLayout_2);
							(function(container){
								var output_6 = new cpr.controls.Output();
								output_6.value = "<기능 확인 컨트롤>";
								output_6.style.setClasses(["text-center"]);
								container.addChild(output_6, {
									"colIndex": 0,
									"rowIndex": 1
								});
								var grid_1 = new cpr.controls.Grid("sampleGrd");
								grid_1.init({
									"dataSet": app.lookup("dsList"),
									"columnMovable": true,
									"selectionMulti": "multi",
									"resizableColumns": "all",
									"columns": [
										{"width": "25px"},
										{"width": "50px"},
										{"width": "100px"},
										{"width": "100px"},
										{"width": "100px"},
										{"width": "100px"},
										{"width": "100px"},
										{"width": "100px"}
									],
									"header": {
										"rows": [{"height": "35px"}],
										"cells": [
											{
												"constraint": {"rowIndex": 0, "colIndex": 0},
												"configurator": function(cell){
													cell.filterable = false;
													cell.sortable = false;
													cell.columnType = "checkbox";
												}
											},
											{
												"constraint": {"rowIndex": 0, "colIndex": 1},
												"configurator": function(cell){
													cell.filterable = false;
													cell.sortable = false;
												}
											},
											{
												"constraint": {"rowIndex": 0, "colIndex": 2},
												"configurator": function(cell){
													cell.targetColumnName = "empId";
													cell.filterable = false;
													cell.sortable = false;
													cell.text = "empId";
												}
											},
											{
												"constraint": {"rowIndex": 0, "colIndex": 3},
												"configurator": function(cell){
													cell.targetColumnName = "empNm";
													cell.filterable = false;
													cell.sortable = false;
													cell.text = "empNm";
												}
											},
											{
												"constraint": {"rowIndex": 0, "colIndex": 4},
												"configurator": function(cell){
													cell.targetColumnName = "email";
													cell.filterable = false;
													cell.sortable = false;
													cell.text = "email";
												}
											},
											{
												"constraint": {"rowIndex": 0, "colIndex": 5},
												"configurator": function(cell){
													cell.targetColumnName = "phone";
													cell.filterable = false;
													cell.sortable = false;
													cell.text = "phone";
												}
											},
											{
												"constraint": {"rowIndex": 0, "colIndex": 6},
												"configurator": function(cell){
													cell.targetColumnName = "address";
													cell.filterable = false;
													cell.sortable = false;
													cell.text = "address";
												}
											},
											{
												"constraint": {"rowIndex": 0, "colIndex": 7},
												"configurator": function(cell){
													cell.targetColumnName = "rgstDt";
													cell.filterable = false;
													cell.sortable = false;
													cell.text = "rgstDt";
												}
											}
										]
									},
									"detail": {
										"rows": [{"height": "30px"}],
										"cells": [
											{
												"constraint": {"rowIndex": 0, "colIndex": 0},
												"configurator": function(cell){
													cell.columnType = "checkbox";
												}
											},
											{
												"constraint": {"rowIndex": 0, "colIndex": 1},
												"configurator": function(cell){
													cell.columnType = "rowindex";
												}
											},
											{
												"constraint": {"rowIndex": 0, "colIndex": 2},
												"configurator": function(cell){
													cell.columnName = "empId";
												}
											},
											{
												"constraint": {"rowIndex": 0, "colIndex": 3},
												"configurator": function(cell){
													cell.columnName = "empNm";
												}
											},
											{
												"constraint": {"rowIndex": 0, "colIndex": 4},
												"configurator": function(cell){
													cell.columnName = "email";
												}
											},
											{
												"constraint": {"rowIndex": 0, "colIndex": 5},
												"configurator": function(cell){
													cell.columnName = "phone";
												}
											},
											{
												"constraint": {"rowIndex": 0, "colIndex": 6},
												"configurator": function(cell){
													cell.columnName = "address";
												}
											},
											{
												"constraint": {"rowIndex": 0, "colIndex": 7},
												"configurator": function(cell){
													cell.columnName = "rgstDt";
												}
											}
										]
									}
								});
								container.addChild(grid_1, {
									"colIndex": 0,
									"rowIndex": 0
								});
							})(group_9);
							container.addChild(group_9, {
								"autoSize": "none",
								"width": "200px",
								"height": "450px"
							});
						})(group_8);
						container.addChild(group_8, {
							"autoSize": "height",
							"width": "1210px",
							"height": "400px"
						});
					})(group_7);
					container.addChild(group_7, {
						"autoSize": "height",
						"width": "1270px",
						"height": "450px"
					});
				})(group_6);
				container.addChild(group_6, {
					"autoSize": "height",
					"width": "1270px",
					"height": "450px"
				});
				var output_7 = new cpr.controls.Output();
				output_7.value = "주요코드";
				output_7.style.setClasses(["h1", "pl-3", "bg-primary", "text-white"]);
				output_7.style.css({
					"font-weight" : "bold",
					"padding-left" : "1rem",
					"font-size" : "1.75rem"
				});
				container.addChild(output_7, {
					"autoSize": "none",
					"width": "1210px",
					"height": "40px"
				});
				var group_10 = new cpr.controls.Container();
				// Layout
				var formLayout_3 = new cpr.controls.layouts.FormLayout();
				formLayout_3.userResizingMode = "standard";
				formLayout_3.topMargin = "0px";
				formLayout_3.rightMargin = "0px";
				formLayout_3.bottomMargin = "0px";
				formLayout_3.leftMargin = "0px";
				formLayout_3.horizontalSpacing = "5px";
				formLayout_3.verticalSpacing = "5px";
				formLayout_3.setColumns(["1fr", "700px"]);
				formLayout_3.setRows(["1fr"]);
				group_10.setLayout(formLayout_3);
				(function(container){
					var group_11 = new cpr.controls.Container();
					group_11.style.setClasses(["form-box"]);
					// Layout
					var verticalLayout_9 = new cpr.controls.layouts.VerticalLayout();
					group_11.setLayout(verticalLayout_9);
					(function(container){
						var userDefinedControl_2 = new udc.tmp.Ace("ace2");
						container.addChild(userDefinedControl_2, {
							"autoSize": "height",
							"width": "418px",
							"height": "295px"
						});
					})(group_11);
					container.addChild(group_11, {
						"colIndex": 1,
						"rowIndex": 0
					});
					var group_12 = new cpr.controls.Container();
					// Layout
					var formLayout_4 = new cpr.controls.layouts.FormLayout();
					formLayout_4.horizontalSpacing = "5px";
					formLayout_4.verticalSpacing = "10px";
					formLayout_4.setColumns(["1fr", "10px"]);
					formLayout_4.setColumnAutoSizing(1, true);
					formLayout_4.setRows(["1fr"]);
					group_12.setLayout(formLayout_4);
					(function(container){
						var userDefinedControl_3 = new udc.com.udcSplit("udcsplit1");
						userDefinedControl_3.leftGrpId = "grp6";
						userDefinedControl_3.rightGrpId = "grp7";
						container.addChild(userDefinedControl_3, {
							"colIndex": 1,
							"rowIndex": 0,
							"colSpan": 1,
							"rowSpan": 1,
							"horizontalAlign": "right",
							"width": 9
						});
						var group_13 = new cpr.controls.Container();
						// Layout
						var formLayout_5 = new cpr.controls.layouts.FormLayout();
						formLayout_5.scrollable = false;
						formLayout_5.topMargin = "0px";
						formLayout_5.rightMargin = "0px";
						formLayout_5.bottomMargin = "0px";
						formLayout_5.leftMargin = "0px";
						formLayout_5.horizontalSpacing = "10px";
						formLayout_5.verticalSpacing = "10px";
						formLayout_5.setColumns(["1fr"]);
						formLayout_5.setRows(["40px", "1fr"]);
						formLayout_5.setRowAutoSizing(0, true);
						group_13.setLayout(formLayout_5);
						(function(container){
							var group_14 = new cpr.controls.Container("grpFormFunc");
							group_14.style.setClasses(["form-box"]);
							// Layout
							var formLayout_6 = new cpr.controls.layouts.FormLayout();
							formLayout_6.topMargin = "5px";
							formLayout_6.rightMargin = "5px";
							formLayout_6.bottomMargin = "5px";
							formLayout_6.leftMargin = "5px";
							formLayout_6.horizontalSpacing = "5px";
							formLayout_6.verticalSpacing = "5px";
							formLayout_6.setColumns(["1fr"]);
							formLayout_6.setRows(["25px", "25px", "25px", "25px", "25px", "25px", "25px", "25px"]);
							formLayout_6.setRowAutoSizing(1, true);
							formLayout_6.setRowAutoSizing(2, true);
							formLayout_6.setRowAutoSizing(3, true);
							formLayout_6.setRowAutoSizing(4, true);
							formLayout_6.setRowAutoSizing(5, true);
							formLayout_6.setRowAutoSizing(6, true);
							formLayout_6.setRowAutoSizing(7, true);
							group_14.setLayout(formLayout_6);
							(function(container){
								var group_15 = new cpr.controls.Container("grp1");
								// Layout
								var formLayout_7 = new cpr.controls.layouts.FormLayout();
								formLayout_7.horizontalSpacing = "5px";
								formLayout_7.verticalSpacing = "5px";
								formLayout_7.setColumns(["24px", "1fr", "2fr", "1fr", "120px"]);
								formLayout_7.setRows(["25px"]);
								group_15.setLayout(formLayout_7);
								(function(container){
									var output_8 = new cpr.controls.Output();
									output_8.value = "No";
									output_8.style.css({
										"background-color" : "#e1edfe",
										"background-image" : "none",
										"text-align" : "center"
									});
									container.addChild(output_8, {
										"colIndex": 0,
										"rowIndex": 0
									});
									var output_9 = new cpr.controls.Output();
									output_9.value = "API";
									output_9.style.css({
										"background-color" : "#e1edfe",
										"background-image" : "none",
										"text-align" : "center"
									});
									container.addChild(output_9, {
										"colIndex": 1,
										"rowIndex": 0
									});
									var output_10 = new cpr.controls.Output();
									output_10.value = "설명";
									output_10.style.css({
										"background-color" : "#e1edfe",
										"background-image" : "none",
										"text-align" : "center"
									});
									container.addChild(output_10, {
										"colIndex": 2,
										"rowIndex": 0
									});
									var output_11 = new cpr.controls.Output();
									output_11.value = "입력값";
									output_11.style.css({
										"background-color" : "#e1edfe",
										"background-image" : "none",
										"text-align" : "center"
									});
									container.addChild(output_11, {
										"colIndex": 3,
										"rowIndex": 0
									});
									var output_12 = new cpr.controls.Output();
									output_12.value = "동작";
									output_12.style.css({
										"background-color" : "#e1edfe",
										"background-image" : "none",
										"text-align" : "center"
									});
									container.addChild(output_12, {
										"colIndex": 4,
										"rowIndex": 0
									});
								})(group_15);
								container.addChild(group_15, {
									"colIndex": 0,
									"rowIndex": 0,
									"colSpan": 1,
									"rowSpan": 1
								});
								var group_16 = new cpr.controls.Container("grp2");
								// Layout
								var formLayout_8 = new cpr.controls.layouts.FormLayout();
								formLayout_8.horizontalSpacing = "5px";
								formLayout_8.verticalSpacing = "5px";
								formLayout_8.setColumns(["24px", "1fr", "2fr", "1fr", "120px"]);
								formLayout_8.setRows(["25px"]);
								formLayout_8.setRowAutoSizing(0, true);
								group_16.setLayout(formLayout_8);
								(function(container){
									var output_13 = new cpr.controls.Output();
									output_13.value = "1";
									output_13.style.css({
										"background-color" : "#e1edfe",
										"border-right-style" : "none",
										"border-left-style" : "none",
										"border-bottom-style" : "none",
										"background-image" : "none",
										"border-top-style" : "none",
										"text-align" : "center"
									});
									container.addChild(output_13, {
										"colIndex": 0,
										"rowIndex": 0
									});
									var inputBox_1 = new cpr.controls.InputBox("ipb2");
									inputBox_1.readOnly = true;
									inputBox_1.value = "changeRowIndex";
									container.addChild(inputBox_1, {
										"colIndex": 1,
										"rowIndex": 0
									});
									var inputBox_2 = new cpr.controls.InputBox("ipb3");
									inputBox_2.readOnly = true;
									inputBox_2.value = "선택한 두 행의 위치를 바꿉니다.";
									container.addChild(inputBox_2, {
										"colIndex": 2,
										"rowIndex": 0
									});
									var button_1 = new cpr.controls.Button("btn3");
									button_1.value = "실행";
									button_1.style.setClasses(["btn-primary"]);
									if(typeof onBtn3Click == "function") {
										button_1.addEventListener("click", onBtn3Click);
									}
									container.addChild(button_1, {
										"colIndex": 4,
										"rowIndex": 0
									});
								})(group_16);
								container.addChild(group_16, {
									"colIndex": 0,
									"rowIndex": 1,
									"colSpan": 1,
									"rowSpan": 1
								});
							})(group_14);
							container.addChild(group_14, {
								"colIndex": 0,
								"rowIndex": 1
							});
							var group_17 = new cpr.controls.Container("grpRslt");
							group_17.style.setClasses(["form-box"]);
							// Layout
							var formLayout_9 = new cpr.controls.layouts.FormLayout();
							formLayout_9.scrollable = false;
							formLayout_9.topMargin = "5px";
							formLayout_9.rightMargin = "30px";
							formLayout_9.bottomMargin = "5px";
							formLayout_9.leftMargin = "5px";
							formLayout_9.horizontalSpacing = "5px";
							formLayout_9.verticalSpacing = "5px";
							formLayout_9.setColumns(["100px", "1fr"]);
							formLayout_9.setRows(["1fr"]);
							group_17.setLayout(formLayout_9);
							(function(container){
								var output_14 = new cpr.controls.Output();
								output_14.value = "결과값";
								output_14.style.css({
									"background-color" : "#e1edfe",
									"background-image" : "none",
									"padding-right" : "1rem"
								});
								container.addChild(output_14, {
									"colIndex": 0,
									"rowIndex": 0
								});
								var output_15 = new cpr.controls.Output("optRslt");
								output_15.value = "";
								output_15.style.css({
									"background-color" : "white",
									"border-right-style" : "none",
									"border-left-style" : "none",
									"padding-left" : "1rem",
									"border-bottom-style" : "none",
									"border-top-style" : "none",
									"text-align" : "left"
								});
								container.addChild(output_15, {
									"colIndex": 1,
									"rowIndex": 0
								});
							})(group_17);
							container.addChild(group_17, {
								"colIndex": 0,
								"rowIndex": 0
							});
						})(group_13);
						container.addChild(group_13, {
							"colIndex": 0,
							"rowIndex": 0,
							"colSpan": 1,
							"rowSpan": 1
						});
					})(group_12);
					container.addChild(group_12, {
						"colIndex": 0,
						"rowIndex": 0,
						"colSpan": 1,
						"rowSpan": 1
					});
				})(group_10);
				container.addChild(group_10, {
					"autoSize": "none",
					"width": "1270px",
					"height": "295px"
				});
				var group_18 = new cpr.controls.Container("grpThirdParty");
				group_18.style.setClasses(["card-inner"]);
				// Layout
				var verticalLayout_10 = new cpr.controls.layouts.VerticalLayout();
				verticalLayout_10.spacing = 15;
				verticalLayout_10.leftMargin = 0;
				verticalLayout_10.rightMargin = 0;
				verticalLayout_10.topMargin = 20;
				verticalLayout_10.bottomMargin = 40;
				group_18.setLayout(verticalLayout_10);
				(function(container){
					var output_16 = new cpr.controls.Output();
					output_16.value = "최소 요구 버전";
					output_16.style.setClasses(["h1", "pl-3", "bg-primary", "text-white"]);
					output_16.style.css({
						"font-weight" : "bold",
						"padding-left" : "1rem",
						"font-size" : "1.75rem"
					});
					container.addChild(output_16, {
						"autoSize": "none",
						"width": "1270px",
						"height": "40px"
					});
					var group_19 = new cpr.controls.Container();
					group_19.style.css({
						"background-color" : "#FFF5EF"
					});
					// Layout
					var verticalLayout_11 = new cpr.controls.layouts.VerticalLayout();
					verticalLayout_11.leftMargin = 30;
					verticalLayout_11.rightMargin = 30;
					verticalLayout_11.topMargin = 20;
					verticalLayout_11.bottomMargin = 20;
					group_19.setLayout(verticalLayout_11);
					(function(container){
						var output_17 = new cpr.controls.Output();
						output_17.value = "1.0.2344 릴리즈 버전";
						output_17.style.css({
							"color" : "#FF9149",
							"font-weight" : "bolder"
						});
						container.addChild(output_17, {
							"width": "100px",
							"height": "25px"
						});
						var output_18 = new cpr.controls.Output();
						output_18.value = "changeRowIndex, moveRowIndex를 통해 원본 데이터가 이동되게 되면\r\nrefresh()를 사용하는 sort, filter시에도 이동된 행을 원본 위치로 기억하여 해당 위치로 보이게 됩니다.";
						output_18.style.css({
							"color" : "#FF9149"
						});
						container.addChild(output_18, {
							"autoSize": "height",
							"width": "100px",
							"height": "25px"
						});
					})(group_19);
					container.addChild(group_19, {
						"autoSize": "height",
						"width": "1040px",
						"height": "100px"
					});
				})(group_18);
				container.addChild(group_18, {
					"autoSize": "height",
					"width": "1100px",
					"height": "500px"
				});
				var group_20 = new cpr.controls.Container("grpTechdom");
				group_20.style.setClasses(["card-inner"]);
				// Layout
				var verticalLayout_12 = new cpr.controls.layouts.VerticalLayout();
				verticalLayout_12.spacing = 15;
				verticalLayout_12.leftMargin = 0;
				verticalLayout_12.rightMargin = 0;
				verticalLayout_12.topMargin = 20;
				verticalLayout_12.bottomMargin = 40;
				group_20.setLayout(verticalLayout_12);
				(function(container){
					var output_19 = new cpr.controls.Output();
					output_19.value = "토마토 시스템 기술지원(Techdom)";
					output_19.style.setClasses(["h1", "pl-3", "bg-primary", "text-white"]);
					output_19.style.css({
						"font-weight" : "bold",
						"padding-left" : "1rem",
						"font-size" : "1.75rem"
					});
					container.addChild(output_19, {
						"autoSize": "none",
						"width": "1270px",
						"height": "40px"
					});
					var group_21 = new cpr.controls.Container();
					group_21.style.css({
						"background-color" : "#fef6e0",
						"background-image" : "none"
					});
					// Layout
					var verticalLayout_13 = new cpr.controls.layouts.VerticalLayout();
					verticalLayout_13.leftMargin = 30;
					verticalLayout_13.rightMargin = 30;
					verticalLayout_13.topMargin = 20;
					verticalLayout_13.bottomMargin = 20;
					group_21.setLayout(verticalLayout_13);
					(function(container){
						var output_20 = new cpr.controls.Output();
						output_20.style.css({
							"color" : "#FF9149",
							"font-weight" : "bolder"
						});
						output_20.bind("value").toExpression("#selOpt.value + ' ' + #selNum.value");
						container.addChild(output_20, {
							"width": "100px",
							"height": "25px"
						});
						var output_21 = new cpr.controls.Output("selOpt");
						output_21.visible = false;
						output_21.value = "FAQ";
						output_21.style.css({
							"color" : "#FF9149"
						});
						container.addChild(output_21, {
							"autoSize": "height",
							"width": "1210px",
							"height": "25px"
						});
						var output_22 = new cpr.controls.Output("selNum");
						output_22.visible = false;
						output_22.value = "96";
						output_22.style.css({
							"color" : "#FF9149"
						});
						container.addChild(output_22, {
							"autoSize": "height",
							"width": "100px",
							"height": "25px"
						});
						var output_23 = new cpr.controls.Output();
						output_23.value = "우측하단 '이동' 버튼을 통해 관련글을 조회할 수 있습니다.";
						output_23.style.css({
							"color" : "#FF9149"
						});
						container.addChild(output_23, {
							"autoSize": "height",
							"width": "1210px",
							"height": "25px"
						});
						var group_22 = new cpr.controls.Container();
						// Layout
						var formLayout_10 = new cpr.controls.layouts.FormLayout();
						formLayout_10.scrollable = false;
						formLayout_10.topMargin = "0px";
						formLayout_10.rightMargin = "0px";
						formLayout_10.bottomMargin = "0px";
						formLayout_10.leftMargin = "0px";
						formLayout_10.horizontalSpacing = "0px";
						formLayout_10.verticalSpacing = "0px";
						formLayout_10.setColumns(["1fr", "50px"]);
						formLayout_10.setRows(["1fr"]);
						group_22.setLayout(formLayout_10);
						(function(container){
							var button_2 = new cpr.controls.Button("moveButton");
							button_2.value = "이동";
							button_2.ariaButtonType = "link";
							button_2.style.css({
								"border-right-style" : "none",
								"color" : "#FF9149",
								"border-bottom-color" : "none",
								"font-weight" : "bolder",
								"border-left-color" : "none",
								"border-right-color" : "none",
								"border-top-style" : "none",
								"background-color" : "#fef6e0",
								"border-left-style" : "none",
								"border-top-color" : "none",
								"border-bottom-style" : "none",
								"background-image" : "none",
								"text-align" : "center"
							});
							if(typeof onBtn5Click2 == "function") {
								button_2.addEventListener("click", onBtn5Click2);
							}
							container.addChild(button_2, {
								"colIndex": 1,
								"rowIndex": 0
							});
						})(group_22);
						container.addChild(group_22, {
							"width": "400px",
							"height": "20px"
						});
					})(group_21);
					container.addChild(group_21, {
						"autoSize": "height",
						"width": "1040px",
						"height": "200px"
					});
				})(group_20);
				container.addChild(group_20, {
					"autoSize": "height",
					"width": "1270px",
					"height": "300px"
				});
			})(group_2);
			container.addChild(group_2, {
				"autoSize": "height",
				"width": "1320px",
				"height": "2800px"
			});
		}
	});
	app.title = "FAQ96";
	cpr.core.Platform.INSTANCE.register(app);
})();
