/*
 * App URI: app/system/POPUP
 * Source Location: app/system/POPUP.clx
 *
 * This file was generated by eXbuilder6 compiler, Don't edit manually.
 */
(function(){
	var app = new cpr.core.App("app/system/POPUP", {
		onPrepare: function(loader){
		},
		onCreate: function(/* cpr.core.AppInstance */ app, exports){
			var linker = {};
			// Start - User Script
			
			
			/*
			 * "초기화 비밀번호 부여" 버튼(btnMdl1)에서 click 이벤트 발생 시 호출.
			 * 사용자가 컨트롤을 클릭할 때 발생하는 이벤트.
			 */
			function onBtnMdl1Click2(e){
				var btnMdl1 = e.control;
				app.getRootAppInstance().openDialog("app/system/PUI_CM_039_01-04", {width: 500, height: 198}, function(dialog){
			
				});
			}
			
			/*
			 * "회원탈퇴 요청" 버튼(btnMdl2)에서 click 이벤트 발생 시 호출.
			 * 사용자가 컨트롤을 클릭할 때 발생하는 이벤트.
			 */
			function onBtnMdl2Click2(e){
				var btnMdl2 = e.control;
				app.getRootAppInstance().openDialog("app/system/PUI_CM_039_03-02", {width: 500, height: 152}, function(dialog){
			//		dialog.style.addClass("modal-green");
				});
			}
			
			/*
			 * "세션 만료 안내" 버튼(btnMdl5)에서 click 이벤트 발생 시 호출.
			 * 사용자가 컨트롤을 클릭할 때 발생하는 이벤트.
			 */
			function onBtnMdl5Click2(e){
				var btnMdl5 = e.control;
				app.getRootAppInstance().openDialog("app/system/PUI_CM_040_02-01", {width: 500, height: 190}, function(dialog){
			//		dialog.style.addClass("modal-green");
				});
			}
			
			/*
			 * "계정 잠금 알림" 버튼(btnMdl3)에서 click 이벤트 발생 시 호출.
			 * 사용자가 컨트롤을 클릭할 때 발생하는 이벤트.
			 */
			function onBtnMdl3Click2(e){
				var btnMdl3 = e.control;
				app.getRootAppInstance().openDialog("app/system/PUI_CM_040_03-02", {width: 500, height: 210}, function(dialog){
			//		dialog.style.addClass("modal-green");
				});
			}
			
			/*
			 * "도움말 등록 메뉴 선택" 버튼(btnMdl4)에서 click 이벤트 발생 시 호출.
			 * 사용자가 컨트롤을 클릭할 때 발생하는 이벤트.
			 */
			function onBtnMdl4Click(e){
				var btnMdl4 = e.control;
				app.getRootAppInstance().openDialog("app/system/PUI_CM_043_02-04", {width: 500, height: 392}, function(dialog){
			//		dialog.style.addClass("modal-green");
				});
			};
			// End - User Script
			
			// Header
			
			app.supportMedia("all and (min-width: 1280px)", "default");
			app.supportMedia("all and (max-width: 1279px)", "tablet");
			
			// Configure root container
			var container = app.getContainer();
			container.style.css({
				"width" : "100%",
				"height" : "100%"
			});
			
			// Layout
			var verticalLayout_1 = new cpr.controls.layouts.VerticalLayout();
			container.setLayout(verticalLayout_1);
			
			// UI Configuration
			var userDefinedControl_1 = new udc.com.appHeader("appheader");
			container.addChild(userDefinedControl_1, {
				"autoSize": "none",
				"width": "1680px",
				"height": "30px"
			});
			
			var group_1 = new cpr.controls.Container();
			// Layout
			var verticalLayout_2 = new cpr.controls.layouts.VerticalLayout();
			verticalLayout_2.scrollable = false;
			verticalLayout_2.spacing = 10;
			group_1.setLayout(verticalLayout_2);
			(function(container){
				var output_1 = new cpr.controls.Output();
				output_1.value = "아래의 버튼을 클릭하여 팝업화면을 확인하세요. (윈도우 팝업이 아닌 컴포넌트로 작성함)";
				container.addChild(output_1, {
					"width": "100px",
					"height": "24px"
				});
				var group_2 = new cpr.controls.Container();
				// Layout
				var flowLayout_1 = new cpr.controls.layouts.FlowLayout();
				flowLayout_1.scrollable = false;
				flowLayout_1.horizontalSpacing = 5;
				group_2.setLayout(flowLayout_1);
				(function(container){
					var button_1 = new cpr.controls.Button("btnMdl1");
					button_1.value = "초기화 비밀번호 부여";
					button_1.style.setClasses(["btn-primary"]);
					if(typeof onBtnMdl1Click2 == "function") {
						button_1.addEventListener("click", onBtnMdl1Click2);
					}
					if(typeof onBtnMdl1Click == "function") {
						button_1.addEventListener("click", onBtnMdl1Click);
					}
					container.addChild(button_1, {
						"width": "140px",
						"height": "25px"
					});
					var button_2 = new cpr.controls.Button("btnMdl2");
					button_2.value = "회원탈퇴 요청";
					button_2.style.setClasses(["btn-primary"]);
					if(typeof onBtnMdl2Click == "function") {
						button_2.addEventListener("click", onBtnMdl2Click);
					}
					if(typeof onBtnMdl2Click2 == "function") {
						button_2.addEventListener("click", onBtnMdl2Click2);
					}
					container.addChild(button_2, {
						"width": "90px",
						"height": "25px"
					});
					var button_3 = new cpr.controls.Button("btnMdl5");
					button_3.value = "세션 만료 안내";
					button_3.style.setClasses(["btn-primary"]);
					if(typeof onBtnMdl5Click == "function") {
						button_3.addEventListener("click", onBtnMdl5Click);
					}
					if(typeof onBtnMdl5Click2 == "function") {
						button_3.addEventListener("click", onBtnMdl5Click2);
					}
					container.addChild(button_3, {
						"autoSize": "none",
						"width": "100px",
						"height": "25px"
					});
					var button_4 = new cpr.controls.Button("btnMdl3");
					button_4.value = "계정 잠금 알림";
					button_4.style.setClasses(["btn-primary"]);
					if(typeof onBtnMdl3Click == "function") {
						button_4.addEventListener("click", onBtnMdl3Click);
					}
					if(typeof onBtnMdl3Click2 == "function") {
						button_4.addEventListener("click", onBtnMdl3Click2);
					}
					container.addChild(button_4, {
						"width": "100px",
						"height": "25px"
					});
					var button_5 = new cpr.controls.Button("btnMdl4");
					button_5.value = "도움말 등록 메뉴 선택";
					button_5.style.setClasses(["btn-primary"]);
					if(typeof onButtonClick == "function") {
						button_5.addEventListener("click", onButtonClick);
					}
					if(typeof onBtnMdl4Click == "function") {
						button_5.addEventListener("click", onBtnMdl4Click);
					}
					container.addChild(button_5, {
						"autoSize": "none",
						"width": "140px",
						"height": "25px"
					});
				})(group_2);
				container.addChild(group_2, {
					"autoSize": "height",
					"width": "400px",
					"height": "25px"
				});
			})(group_1);
			container.addChild(group_1, {
				"autoSize": "height",
				"width": "1220px",
				"height": "79px"
			});
		}
	});
	app.title = "POPUP";
	cpr.core.Platform.INSTANCE.register(app);
})();
