/*
 * App URI: app/exam/appSmpl/languageChange
 * Source Location: app/exam/appSmpl/languageChange.clx
 *
 * This file was generated by eXbuilder6 compiler, Don't edit manually.
 */
(function(){
	var app = new cpr.core.App("app/exam/appSmpl/languageChange", {
		onPrepare: function(loader){
		},
		onCreate: function(/* cpr.core.AppInstance */ app, exports){
			var linker = {};
			// Start - User Script
			/************************************************
			 * CTmpl.js
			 * Created at 2022. 2. 25. 오후 4:40:31.
			 *
			 * @author 1amthomas
			 ************************************************/
			
			/*
			 * 콤보 박스에서 selection-change 이벤트 발생 시 호출.
			 * ComboBox Item을 선택하여 선택된 값이 저장된 후에 발생하는 이벤트.
			 */
			function onCmbLangSelectionChange(e){
				/** 
				 * @type cpr.controls.ComboBox
				 */
				
				/* 언어 코드에 따른 다국어 설정 */
				cpr.I18N.INSTANCE.currentLanguage = app.lookup("cmbLang").getSelectionLast().value;
			}
			
			/*
			 * 사용자 정의 컨트롤에서 afterLoad 이벤트 발생 시 호출.
			 */
			function onAce1AfterLoad(e){
				/* 에디터에 소스 표시 */
				var vcAceEditor = app.lookup("ace1");
				vcAceEditor.value = onCmbLangSelectionChange;
			};
			// End - User Script
			
			// Header
			
			app.supportMedia("all and (min-width: 1320px)", "eXFrame");
			app.supportMedia("all and (min-width: 1020px) and (max-width: 1319px)", "default");
			app.supportMedia("all and (min-width: 760px) and (max-width: 1019px)", "tablet");
			app.supportMedia("all and (max-width: 759px)", "mobile");
			
			// Configure root container
			var container = app.getContainer();
			container.style.css({
				"width" : "100%",
				"height" : "100%"
			});
			
			// Layout
			var verticalLayout_1 = new cpr.controls.layouts.VerticalLayout();
			container.setLayout(verticalLayout_1);
			
			// UI Configuration
			var group_1 = new cpr.controls.Container("grpHeader");
			// Layout
			var verticalLayout_2 = new cpr.controls.layouts.VerticalLayout();
			group_1.setLayout(verticalLayout_2);
			(function(container){
				var userDefinedControl_1 = new udc.com.appHeader("appheader1");
				container.addChild(userDefinedControl_1, {
					"width": "500px",
					"height": "30px"
				});
			})(group_1);
			container.addChild(group_1, {
				"autoSize": "height",
				"width": "1320px",
				"height": "30px"
			});
			
			var group_2 = new cpr.controls.Container("grpData");
			// Layout
			var verticalLayout_3 = new cpr.controls.layouts.VerticalLayout();
			verticalLayout_3.leftMargin = 20;
			verticalLayout_3.rightMargin = 30;
			verticalLayout_3.topMargin = 30;
			verticalLayout_3.bottomMargin = 30;
			group_2.setLayout(verticalLayout_3);
			(function(container){
				var group_3 = new cpr.controls.Container("grp1");
				// Layout
				var verticalLayout_4 = new cpr.controls.layouts.VerticalLayout();
				verticalLayout_4.spacing = 30;
				verticalLayout_4.topMargin = 20;
				verticalLayout_4.bottomMargin = 40;
				group_3.setLayout(verticalLayout_4);
				(function(container){
					var group_4 = new cpr.controls.Container("grp3");
					// Layout
					var formLayout_1 = new cpr.controls.layouts.FormLayout();
					formLayout_1.scrollable = false;
					formLayout_1.rightMargin = "50px";
					formLayout_1.horizontalSpacing = "5px";
					formLayout_1.verticalSpacing = "5px";
					formLayout_1.setColumns(["300px", "100px"]);
					formLayout_1.setColumnAutoSizing(0, true);
					formLayout_1.setColumnAutoSizing(1, true);
					formLayout_1.setRows(["1fr"]);
					group_4.setLayout(formLayout_1);
					(function(container){
						var output_1 = new cpr.controls.Output();
						output_1.value = "다국어 샘플";
						output_1.style.css({
							"font-weight" : "bold",
							"padding-left" : "1rem",
							"font-size" : "2.5rem"
						});
						container.addChild(output_1, {
							"colIndex": 0,
							"rowIndex": 0
						});
					})(group_4);
					container.addChild(group_4, {
						"autoSize": "height",
						"width": "1270px",
						"height": "40px"
					});
					var output_2 = new cpr.controls.Output();
					output_2.value = "eXBuilder6에서는 언어 파일(source-path/language.json)을 이용하여 바인딩 타겟에 값을 제공합니다. 언어 뷰에서 등록된 항목을 바인딩 타겟 컨트롤에 드래그 앤 드롭하거나 바인딩 편집 대화상자에서 바인딩 유형을 다국어 사전 바인딩으로 지정한 후 용어 키에 키 패스를 지정하여 값을 제공합니다.";
					output_2.style.setClasses(["opt-tmpl"]);
					output_2.style.css({
						"padding-left" : "1rem",
						"font-size" : "1rem"
					});
					container.addChild(output_2, {
						"autoSize": "height",
						"width": "1210px",
						"height": "46px"
					});
				})(group_3);
				container.addChild(group_3, {
					"autoSize": "height",
					"width": "1270px",
					"height": "150px"
				});
				var group_5 = new cpr.controls.Container("grp2");
				// Layout
				var verticalLayout_5 = new cpr.controls.layouts.VerticalLayout();
				verticalLayout_5.spacing = 30;
				verticalLayout_5.topMargin = 10;
				verticalLayout_5.bottomMargin = 30;
				group_5.setLayout(verticalLayout_5);
				(function(container){
					var output_3 = new cpr.controls.Output();
					output_3.value = "시나리오";
					output_3.style.setClasses(["h1", "pl-3", "bg-primary", "text-white"]);
					output_3.style.css({
						"font-weight" : "bold",
						"padding-left" : "1rem",
						"font-size" : "1.75rem"
					});
					container.addChild(output_3, {
						"width": "100px",
						"height": "40px"
					});
					var output_4 = new cpr.controls.Output("ipbScenario");
					output_4.value = "1. 다국어 변경 콤보박스에서 각 언어를 선택합니다.\r\n2. 다른 컨트롤들에 언어가 콤보박스에서 선택한 언어로 일괄 변경되는지 확인합니다.";
					output_4.style.setClasses(["opt-tmpl"]);
					output_4.style.css({
						"padding-left" : "1rem",
						"font-size" : "1rem"
					});
					container.addChild(output_4, {
						"autoSize": "height",
						"width": "1210px",
						"height": "107px"
					});
				})(group_5);
				container.addChild(group_5, {
					"autoSize": "height",
					"width": "1270px",
					"height": "300px"
				});
				var group_6 = new cpr.controls.Container("grpFunction");
				// Layout
				var verticalLayout_6 = new cpr.controls.layouts.VerticalLayout();
				group_6.setLayout(verticalLayout_6);
				(function(container){
					var group_7 = new cpr.controls.Container("grpFuncFloating");
					group_7.userAttr({"floating-header": "true"});
					// Layout
					var verticalLayout_7 = new cpr.controls.layouts.VerticalLayout();
					verticalLayout_7.bottomMargin = 30;
					group_7.setLayout(verticalLayout_7);
					(function(container){
						var output_5 = new cpr.controls.Output();
						output_5.value = "기능확인";
						output_5.style.setClasses(["h1", "pl-3", "bg-primary", "text-white"]);
						output_5.style.css({
							"font-weight" : "bold",
							"padding-left" : "1rem",
							"font-size" : "1.75rem"
						});
						container.addChild(output_5, {
							"autoSize": "none",
							"width": "1270px",
							"height": "40px"
						});
						var group_8 = new cpr.controls.Container("grp11");
						group_8.style.css({
							"border-right-style" : "solid",
							"border-top-width" : "1px",
							"border-bottom-color" : "#dedede",
							"border-right-width" : "1px",
							"border-left-color" : "#dedede",
							"border-right-color" : "#dedede",
							"border-left-width" : "1px",
							"border-top-style" : "solid",
							"background-color" : "#F0F0F0",
							"border-left-style" : "solid",
							"border-bottom-width" : "1px",
							"border-top-color" : "#dedede",
							"border-bottom-style" : "solid"
						});
						// Layout
						var verticalLayout_8 = new cpr.controls.layouts.VerticalLayout();
						verticalLayout_8.leftMargin = 30;
						verticalLayout_8.rightMargin = 30;
						verticalLayout_8.topMargin = 5;
						verticalLayout_8.bottomMargin = 10;
						group_8.setLayout(verticalLayout_8);
						(function(container){
							var userDefinedControl_2 = linker.userDefinedControl_2 = new udc.com.comFormTitle("comformtitle1");
							container.addChild(userDefinedControl_2, {
								"autoSize": "none",
								"width": "1320px",
								"height": "25px"
							});
							var group_9 = linker.group_9 = new cpr.controls.Container("grpForm");
							group_9.fieldLabel = "다국어 변경";
							// Layout
							var formLayout_2 = new cpr.controls.layouts.FormLayout();
							formLayout_2.topMargin = "0px";
							formLayout_2.rightMargin = "0px";
							formLayout_2.bottomMargin = "0px";
							formLayout_2.leftMargin = "0px";
							formLayout_2.horizontalSpacing = "5px";
							formLayout_2.verticalSpacing = "5px";
							formLayout_2.setColumns(["1fr"]);
							formLayout_2.setRows(["25px", "1fr"]);
							formLayout_2.setRowAutoSizing(0, true);
							group_9.setLayout(formLayout_2);
							(function(container){
								var group_10 = new cpr.controls.Container("grp4");
								// Layout
								var flowLayout_1 = new cpr.controls.layouts.FlowLayout();
								group_10.setLayout(flowLayout_1);
								(function(container){
									var comboBox_1 = new cpr.controls.ComboBox("cmbLang");
									(function(comboBox_1){
										comboBox_1.addItem((function(){
											var treeItem_1 = new cpr.controls.Item("한국어", "ko");
											treeItem_1.bind("label").toLanguage("NLS-UI-M003");
											return treeItem_1;
										})());
										comboBox_1.addItem((function(){
											var treeItem_2 = new cpr.controls.Item("영어", "en");
											treeItem_2.bind("label").toLanguage("NLS-UI-M004");
											return treeItem_2;
										})());
										comboBox_1.addItem((function(){
											var treeItem_3 = new cpr.controls.Item("일본어", "ja");
											treeItem_3.bind("label").toLanguage("NLS-UI-M005");
											return treeItem_3;
										})());
										comboBox_1.addItem((function(){
											var treeItem_4 = new cpr.controls.Item("중국어", "zh");
											treeItem_4.bind("label").toLanguage("NLS-UI-M006");
											return treeItem_4;
										})());
									})(comboBox_1);
									if(typeof onCmbLangSelectionChange == "function") {
										comboBox_1.addEventListener("selection-change", onCmbLangSelectionChange);
									}
									container.addChild(comboBox_1, {
										"autoSize": "none",
										"width": "120px",
										"height": "30px"
									});
									var output_6 = new cpr.controls.Output();
									output_6.value = "\u203b 콤보박스의 언어에 따라 라벨 값이 변경됩니다.";
									container.addChild(output_6, {
										"autoSize": "none",
										"width": "350px",
										"height": "25px"
									});
								})(group_10);
								container.addChild(group_10, {
									"colIndex": 0,
									"rowIndex": 0,
									"colSpan": 1,
									"rowSpan": 1
								});
								var group_11 = new cpr.controls.Container("grp10");
								group_11.userAttr({
									"mobile-column-count": "1",
									"tablet-column-count": "1"
								});
								// Layout
								var formLayout_3 = new cpr.controls.layouts.FormLayout();
								formLayout_3.topMargin = "0px";
								formLayout_3.rightMargin = "0px";
								formLayout_3.bottomMargin = "0px";
								formLayout_3.leftMargin = "0px";
								formLayout_3.horizontalSpacing = "20px";
								formLayout_3.verticalSpacing = "20px";
								formLayout_3.setColumns(["1fr", "1fr"]);
								formLayout_3.setRows(["250px", "1fr"]);
								formLayout_3.setRowAutoSizing(0, true);
								group_11.setLayout(formLayout_3);
								(function(container){
									var group_12 = new cpr.controls.Container("grp12");
									group_12.style.setClasses(["card"]);
									// Layout
									var verticalLayout_9 = new cpr.controls.layouts.VerticalLayout();
									verticalLayout_9.spacing = 16;
									verticalLayout_9.leftMargin = 20;
									verticalLayout_9.rightMargin = 20;
									verticalLayout_9.topMargin = 20;
									verticalLayout_9.bottomMargin = 20;
									group_12.setLayout(verticalLayout_9);
									(function(container){
										var output_7 = new cpr.controls.Output();
										output_7.value = "폼 컨트롤";
										output_7.style.setClasses(["card-title"]);
										output_7.bind("value").toLanguage("NLS-UI-M016");
										container.addChild(output_7, {
											"width": "100px",
											"height": "25px"
										});
										var group_13 = new cpr.controls.Container("grp13");
										// Layout
										var formLayout_4 = new cpr.controls.layouts.FormLayout();
										formLayout_4.topMargin = "0px";
										formLayout_4.rightMargin = "0px";
										formLayout_4.bottomMargin = "0px";
										formLayout_4.leftMargin = "0px";
										formLayout_4.horizontalSpacing = "8px";
										formLayout_4.verticalSpacing = "8px";
										formLayout_4.setColumns(["1fr"]);
										formLayout_4.setRows(["20px", "32px"]);
										group_13.setLayout(formLayout_4);
										(function(container){
											var output_8 = new cpr.controls.Output();
											output_8.value = "텍스트";
											output_8.bind("value").toLanguage("NLS-UI-M007");
											container.addChild(output_8, {
												"colIndex": 0,
												"rowIndex": 0
											});
											var inputBox_1 = new cpr.controls.InputBox("ipb1");
											inputBox_1.bind("placeholder").toLanguage("NLS-INF-M054");
											container.addChild(inputBox_1, {
												"colIndex": 0,
												"rowIndex": 1
											});
										})(group_13);
										container.addChild(group_13, {
											"width": "400px",
											"height": "60px"
										});
										var group_14 = new cpr.controls.Container("grp14");
										// Layout
										var formLayout_5 = new cpr.controls.layouts.FormLayout();
										formLayout_5.topMargin = "0px";
										formLayout_5.rightMargin = "0px";
										formLayout_5.bottomMargin = "0px";
										formLayout_5.leftMargin = "0px";
										formLayout_5.horizontalSpacing = "8px";
										formLayout_5.verticalSpacing = "8px";
										formLayout_5.setColumns(["1fr"]);
										formLayout_5.setRows(["20px", "32px"]);
										group_14.setLayout(formLayout_5);
										(function(container){
											var output_9 = new cpr.controls.Output();
											output_9.value = "텍스트";
											output_9.bind("value").toLanguage("NLS-UI-M008");
											container.addChild(output_9, {
												"colIndex": 0,
												"rowIndex": 0
											});
											var inputBox_2 = new cpr.controls.InputBox("ipb2");
											inputBox_2.value = "12345!@#$%";
											inputBox_2.secret = true;
											inputBox_2.bind("placeholder").toLanguage("NLS-INF-M054");
											container.addChild(inputBox_2, {
												"colIndex": 0,
												"rowIndex": 1
											});
										})(group_14);
										container.addChild(group_14, {
											"width": "400px",
											"height": "60px"
										});
										var group_15 = new cpr.controls.Container("grp16");
										// Layout
										var formLayout_6 = new cpr.controls.layouts.FormLayout();
										formLayout_6.topMargin = "0px";
										formLayout_6.rightMargin = "0px";
										formLayout_6.bottomMargin = "0px";
										formLayout_6.leftMargin = "0px";
										formLayout_6.horizontalSpacing = "8px";
										formLayout_6.verticalSpacing = "8px";
										formLayout_6.setColumns(["1fr"]);
										formLayout_6.setRows(["20px", "32px"]);
										group_15.setLayout(formLayout_6);
										(function(container){
											var output_10 = new cpr.controls.Output();
											output_10.value = "텍스트";
											output_10.bind("value").toLanguage("NLS-UI-M009");
											container.addChild(output_10, {
												"colIndex": 0,
												"rowIndex": 0
											});
											var inputBox_3 = new cpr.controls.InputBox("ipb3");
											inputBox_3.value = "name@example.com";
											inputBox_3.bind("placeholder").toLanguage("NLS-INF-M054");
											container.addChild(inputBox_3, {
												"colIndex": 0,
												"rowIndex": 1
											});
										})(group_15);
										container.addChild(group_15, {
											"width": "400px",
											"height": "60px"
										});
										var group_16 = new cpr.controls.Container("grp17");
										// Layout
										var formLayout_7 = new cpr.controls.layouts.FormLayout();
										formLayout_7.topMargin = "0px";
										formLayout_7.rightMargin = "0px";
										formLayout_7.bottomMargin = "0px";
										formLayout_7.leftMargin = "0px";
										formLayout_7.horizontalSpacing = "8px";
										formLayout_7.verticalSpacing = "8px";
										formLayout_7.setColumns(["1fr"]);
										formLayout_7.setRows(["20px", "32px"]);
										group_16.setLayout(formLayout_7);
										(function(container){
											var output_11 = new cpr.controls.Output();
											output_11.value = "텍스트";
											output_11.bind("value").toLanguage("NLS-UI-M010");
											container.addChild(output_11, {
												"colIndex": 0,
												"rowIndex": 0
											});
											var comboBox_2 = new cpr.controls.ComboBox("cmb2");
											(function(comboBox_2){
												comboBox_2.addItem(new cpr.controls.Item("1", "1"));
												comboBox_2.addItem(new cpr.controls.Item("2", "2"));
												comboBox_2.addItem(new cpr.controls.Item("3", "3"));
												comboBox_2.addItem(new cpr.controls.Item("4", "4"));
												comboBox_2.addItem(new cpr.controls.Item("5", "5"));
											})(comboBox_2);
											container.addChild(comboBox_2, {
												"colIndex": 0,
												"rowIndex": 1
											});
										})(group_16);
										container.addChild(group_16, {
											"width": "400px",
											"height": "60px"
										});
										var group_17 = new cpr.controls.Container("grp18");
										// Layout
										var formLayout_8 = new cpr.controls.layouts.FormLayout();
										formLayout_8.topMargin = "0px";
										formLayout_8.rightMargin = "0px";
										formLayout_8.bottomMargin = "0px";
										formLayout_8.leftMargin = "0px";
										formLayout_8.horizontalSpacing = "8px";
										formLayout_8.verticalSpacing = "8px";
										formLayout_8.setColumns(["1fr"]);
										formLayout_8.setRows(["20px", "95px"]);
										group_17.setLayout(formLayout_8);
										(function(container){
											var output_12 = new cpr.controls.Output();
											output_12.value = "텍스트";
											output_12.bind("value").toLanguage("NLS-UI-M011");
											container.addChild(output_12, {
												"colIndex": 0,
												"rowIndex": 0
											});
											var listBox_1 = new cpr.controls.ListBox("lbx1");
											listBox_1.multiple = true;
											(function(listBox_1){
												listBox_1.addItem(new cpr.controls.Item("1", "1"));
												listBox_1.addItem(new cpr.controls.Item("2", "2"));
												listBox_1.addItem(new cpr.controls.Item("3", "3"));
												listBox_1.addItem(new cpr.controls.Item("4", "4"));
												listBox_1.addItem(new cpr.controls.Item("5", "5"));
											})(listBox_1);
											container.addChild(listBox_1, {
												"colIndex": 0,
												"rowIndex": 1
											});
										})(group_17);
										container.addChild(group_17, {
											"width": "400px",
											"height": "123px"
										});
										var group_18 = new cpr.controls.Container("grp19");
										// Layout
										var formLayout_9 = new cpr.controls.layouts.FormLayout();
										formLayout_9.topMargin = "0px";
										formLayout_9.rightMargin = "0px";
										formLayout_9.bottomMargin = "0px";
										formLayout_9.leftMargin = "0px";
										formLayout_9.horizontalSpacing = "8px";
										formLayout_9.verticalSpacing = "8px";
										formLayout_9.setColumns(["1fr"]);
										formLayout_9.setRows(["20px", "80px"]);
										group_18.setLayout(formLayout_9);
										(function(container){
											var output_13 = new cpr.controls.Output();
											output_13.value = "텍스트";
											output_13.bind("value").toLanguage("NLS-UI-M012");
											container.addChild(output_13, {
												"colIndex": 0,
												"rowIndex": 0
											});
											var textArea_1 = new cpr.controls.TextArea("txa1");
											container.addChild(textArea_1, {
												"colIndex": 0,
												"rowIndex": 1
											});
										})(group_18);
										container.addChild(group_18, {
											"width": "400px",
											"height": "108px"
										});
									})(group_12);
									container.addChild(group_12, {
										"colIndex": 0,
										"rowIndex": 0,
										"colSpan": 1,
										"rowSpan": 2
									});
									var group_19 = new cpr.controls.Container("grp20");
									group_19.userAttr({"needs-auto-height": "true"});
									group_19.style.setClasses(["card"]);
									// Layout
									var verticalLayout_10 = new cpr.controls.layouts.VerticalLayout();
									verticalLayout_10.spacing = 16;
									verticalLayout_10.leftMargin = 20;
									verticalLayout_10.rightMargin = 20;
									verticalLayout_10.topMargin = 20;
									verticalLayout_10.bottomMargin = 20;
									group_19.setLayout(verticalLayout_10);
									(function(container){
										var output_14 = new cpr.controls.Output();
										output_14.value = "폼 컨트롤";
										output_14.style.setClasses(["card-title"]);
										output_14.bind("value").toLanguage("NLS-UI-M016");
										container.addChild(output_14, {
											"width": "100px",
											"height": "25px"
										});
										var group_20 = new cpr.controls.Container("grp21");
										// Layout
										var formLayout_10 = new cpr.controls.layouts.FormLayout();
										formLayout_10.topMargin = "0px";
										formLayout_10.rightMargin = "0px";
										formLayout_10.bottomMargin = "0px";
										formLayout_10.leftMargin = "0px";
										formLayout_10.horizontalSpacing = "8px";
										formLayout_10.verticalSpacing = "8px";
										formLayout_10.setColumns(["1fr"]);
										formLayout_10.setRows(["20px", "45px"]);
										formLayout_10.setRowAutoSizing(1, true);
										group_20.setLayout(formLayout_10);
										(function(container){
											var output_15 = new cpr.controls.Output();
											output_15.value = "텍스트";
											output_15.bind("value").toLanguage("NLS-UI-M014");
											container.addChild(output_15, {
												"colIndex": 0,
												"rowIndex": 0
											});
											var checkBoxGroup_1 = new cpr.controls.CheckBoxGroup("cbg1");
											checkBoxGroup_1.values = ["value2"];
											checkBoxGroup_1.colCount = 1;
											(function(checkBoxGroup_1){
												checkBoxGroup_1.addItem((function(){
													var item_1 = new cpr.controls.Item("체크박스", "value1");
													item_1.bind("label").toLanguage("NLS-UI-M014");
													return item_1;
												})());
												checkBoxGroup_1.addItem((function(){
													var item_2 = new cpr.controls.Item("체크박스", "value2");
													item_2.bind("label").toLanguage("NLS-UI-M014");
													return item_2;
												})());
											})(checkBoxGroup_1);
											container.addChild(checkBoxGroup_1, {
												"colIndex": 0,
												"rowIndex": 1
											});
										})(group_20);
										container.addChild(group_20, {
											"autoSize": "height",
											"width": "400px",
											"height": "73px"
										});
										var group_21 = new cpr.controls.Container("grp22");
										// Layout
										var formLayout_11 = new cpr.controls.layouts.FormLayout();
										formLayout_11.topMargin = "0px";
										formLayout_11.rightMargin = "0px";
										formLayout_11.bottomMargin = "0px";
										formLayout_11.leftMargin = "0px";
										formLayout_11.horizontalSpacing = "8px";
										formLayout_11.verticalSpacing = "8px";
										formLayout_11.setColumns(["1fr"]);
										formLayout_11.setRows(["20px", "45px"]);
										formLayout_11.setRowAutoSizing(1, true);
										group_21.setLayout(formLayout_11);
										(function(container){
											var output_16 = new cpr.controls.Output();
											output_16.value = "텍스트";
											output_16.bind("value").toLanguage("NLS-UI-M015");
											container.addChild(output_16, {
												"colIndex": 0,
												"rowIndex": 0
											});
											var radioButton_1 = new cpr.controls.RadioButton("rdb1");
											radioButton_1.value = "value2";
											radioButton_1.colCount = 1;
											(function(radioButton_1){
												radioButton_1.addItem((function(){
													var item_1 = new cpr.controls.Item("라디오", "value1");
													item_1.bind("label").toLanguage("NLS-UI-M015");
													return item_1;
												})());
												radioButton_1.addItem((function(){
													var item_2 = new cpr.controls.Item("라디오", "value2");
													item_2.bind("label").toLanguage("NLS-UI-M015");
													return item_2;
												})());
											})(radioButton_1);
											container.addChild(radioButton_1, {
												"colIndex": 0,
												"rowIndex": 1
											});
										})(group_21);
										container.addChild(group_21, {
											"autoSize": "height",
											"width": "400px",
											"height": "73px"
										});
									})(group_19);
									container.addChild(group_19, {
										"colIndex": 1,
										"rowIndex": 0
									});
								})(group_11);
								container.addChild(group_11, {
									"colIndex": 0,
									"rowIndex": 1
								});
							})(group_9);
							container.addChild(group_9, {
								"autoSize": "height",
								"width": "1320px",
								"height": "594px"
							});
						})(group_8);
						container.addChild(group_8, {
							"autoSize": "height",
							"width": "1210px",
							"height": "800px"
						});
					})(group_7);
					container.addChild(group_7, {
						"autoSize": "height",
						"width": "1270px",
						"height": "800px"
					});
				})(group_6);
				container.addChild(group_6, {
					"autoSize": "height",
					"width": "1270px",
					"height": "800px"
				});
				var output_17 = new cpr.controls.Output();
				output_17.value = "주요코드";
				output_17.style.setClasses(["h1", "pl-3", "bg-primary", "text-white"]);
				output_17.style.css({
					"font-weight" : "bold",
					"padding-left" : "1rem",
					"font-size" : "1.75rem"
				});
				container.addChild(output_17, {
					"autoSize": "none",
					"width": "1210px",
					"height": "40px"
				});
				var group_22 = new cpr.controls.Container("grp15");
				// Layout
				var verticalLayout_11 = new cpr.controls.layouts.VerticalLayout();
				verticalLayout_11.spacing = 20;
				verticalLayout_11.leftMargin = 30;
				verticalLayout_11.rightMargin = 30;
				verticalLayout_11.topMargin = 0;
				verticalLayout_11.bottomMargin = 0;
				group_22.setLayout(verticalLayout_11);
				(function(container){
					var group_23 = new cpr.controls.Container("grp7");
					// Layout
					var formLayout_12 = new cpr.controls.layouts.FormLayout();
					formLayout_12.scrollable = false;
					formLayout_12.topMargin = "0px";
					formLayout_12.rightMargin = "0px";
					formLayout_12.bottomMargin = "0px";
					formLayout_12.leftMargin = "0px";
					formLayout_12.horizontalSpacing = "5px";
					formLayout_12.verticalSpacing = "5px";
					formLayout_12.setColumns(["1fr"]);
					formLayout_12.setRows(["1fr"]);
					group_23.setLayout(formLayout_12);
					(function(container){
						var group_24 = new cpr.controls.Container("grp9");
						group_24.style.setClasses(["form-box"]);
						// Layout
						var verticalLayout_12 = new cpr.controls.layouts.VerticalLayout();
						group_24.setLayout(verticalLayout_12);
						(function(container){
							var userDefinedControl_3 = new udc.tmp.Ace("ace1");
							if(typeof onAce1AfterLoad == "function") {
								userDefinedControl_3.addEventListener("afterLoad", onAce1AfterLoad);
							}
							container.addChild(userDefinedControl_3, {
								"autoSize": "height",
								"width": "300px",
								"height": "300px"
							});
						})(group_24);
						container.addChild(group_24, {
							"colIndex": 0,
							"rowIndex": 0
						});
					})(group_23);
					container.addChild(group_23, {
						"autoSize": "height",
						"width": "1210px",
						"height": "310px"
					});
				})(group_22);
				container.addChild(group_22, {
					"autoSize": "height",
					"width": "1270px",
					"height": "350px"
				});
			})(group_2);
			container.addChild(group_2, {
				"autoSize": "height",
				"width": "1320px",
				"height": "2056px"
			});
			// Linking
			linker.userDefinedControl_2.ctrl = linker.group_9;
		}
	});
	app.title = "다국어 샘플";
	cpr.core.Platform.INSTANCE.register(app);
})();
